### ISSUE TITLE
Specify value attribute on ordered list items

### ISSUE THREAD

**Issue by hkdobrev** [erusev/parsedown#101]
This is an extension to #100.

[The HTML5 spec specifies a `value` attribute for `li` elements inside `ol` elements](http://www.w3.org/TR/html5/grouping-content.html#attr-li-value).

So a Markdown list like:

``` md
5. fifth
6. sixth
7. seventh
```

could produce HTML like:

``` html
<ol>
<li value="5">fifth</li>
<li value="6">sixth</li>
<li value="7">seventh</li>
</ol>
```

**Comment by aidantwoods** [comment]
I think this is out of scope for now since it isn't part of CommonMark or the GitHub Flavoured extension.
