### ISSUE TITLE
em and strong fail if html with _ inside

### ISSUE THREAD

**Issue by Cerdic** [erusev/parsedown#107]
This test case works fine
`___em strong <a href="http://parsedown.org/" class='externallink'>Parsedown</a>___`

Whereas this fails
`___em strong <a href="http://parsedown.org/" class='external_link'>Parsedown</a>___`

**Comment by Cerdic** [comment]
Too bad :(
I had to patch last version again in https://github.com/Cerdic/parsedown/commit/870839bc63b8ec617bfa181863116d2d7de45643 as the use-case I initialy described is quite frequent in the CMS I'm using where URL in plain text are auto-changed into link with a class containing underscore char :
`___em strong <a href="http://parsedown.org/" class='external_link'>Parsedown</a>___` 

I understand that the patch doesn't fix all cases, especialy the one described in #588 but I think that ignoring html tags in the regexp as proposed gives a much better robustness for a not a such perf impact.

**Comment by aidantwoods** [comment]
What happens if you try something like `___em strong <a href="http://parsedown.org/" class='external_link'>foo_bar</a>___` with the patched regex?

**Comment by Cerdic** [comment]
it fails :(

**Comment by aidantwoods** [comment]
If there were an easy fix for most cases then I'd definitely be up for getting Parsedown to behave a bit better. I think the regex only really addresses the specific case of delimiters between angle brackets though (which is fine if that's all you need! :) ).

Sure, we could patch the regex to try to find closing tags, but then what about ``* foo `bar* baz` boo*``? If we keep special casing then we'd end up putting an entire copy of the parser in each inline.
