### ISSUE TITLE
Integrate tests from MarkDown Test Suite

### ISSUE THREAD

**Issue by Cerdic** [erusev/parsedown#112]
A MarkDown TestSuite has been initiated by Karl Dubost 
https://github.com/karlcow/markdown-testsuite

It would be interesting to integrate it and be sure ParseDown is compliant to this test suite.

**Comment by aidantwoods** [comment]
As mentioned in #99

> We now test against (but do not currently pass all of) the CommonMark examples. CommonMark is a bit more specific than John Gruber's original Markdown spec, so I think that testing against John Gruber's suite is probably no longer needed :)

Looks like the test suite linked ceased development in favour of CommonMark :)
