### ISSUE TITLE
elements within multiple lines

### ISSUE THREAD

**Issue by wkpark** [erusev/parsedown#132]
these examples are not specifically described in the Markdown spec. but I guess it is not quite difficult to make parsedown compatible with other dialects.

`code` elements within multiple lines

http://johnmacfarlane.net/babelmark2/?text=normal+text+%60inline+code%0Acode%60+normal+text%0A%0Anormal+text+%60inline+code%0A++++code%60+normal+text%0A

~~~
normal text `inline code
code` normal text

normal text `inline code
    code` normal text
~~~

`emph` elements within multiple lines

http://johnmacfarlane.net/babelmark2/?text=normal+text+*inline+code%0Acode*+normal+text%0A%0Anormal+text+*inline+code%0A++++code*+normal+text%0A

~~~
normal text *inline code
code* normal text

normal text *inline code
    code* normal text
~~~

labels with a break within multiple lines (see also #104)

http://johnmacfarlane.net/babelmark2/?text=normal+text+%5Bline%0Abreak%5D+normal+text%0A%0Anormal+text+%5Bline%0A++++break%5D+normal+text%0A%0A%5Bline+break%5D%3A+%2Furl
~~~
normal text [line
break] normal text

normal text [line
    break] normal text

    [line break]: /url "4-spaces prepended to show this label to workaround GFM"
~~~

html inline elements within multilines

http://johnmacfarlane.net/babelmark2/?text=normal+text+%3Cspan%0Aclass%3D%22foobar%22%3Eline%3C%2Fspan%3E+normal+text%0A%0Anormal+text+%3Cspan%0A++++class%3D%22foobar%22%3Eline%3C%2Fspan%3E+normal+text%0A
~~~
normal text <span
class="foobar">line</span> normal text

normal text <span
    class="foobar">line</span> normal text
~~~

**Comment by erusev** [comment]
I believe that this is resolved in the latest release.
