### ISSUE TITLE
Failed test with images (runs in Markdown PHP 1.3 but not in Parsedown)

### ISSUE THREAD

**Issue by queirozfcom** [erusev/parsedown#146]
Hello. This is a small example of a little post with Images I've written which gets parsed OK when run in Markdown 1.3 (as shown in the demo page). When I try to parse it using Parsedown, the image references don't get rendered into the actual images:

Here is the link: http://pastie.org/pastes/8962289/text

(I've added it to pastie because when I try to write it here, github parses it and you can't see the original text.)

**Comment by erusev** [comment]
This is resolved now.
