### ISSUE TITLE
Undefined index: content type

### ISSUE THREAD

**Issue by khromov** [erusev/parsedown#153]
Full error:

```
Notice: Undefined index: content type in /var/www/html/site/trunk/wp-content/plugins/corporate-help/includes/Parsedown.php on line 890
```

Here is the document which creates the error:  
https://dl.dropboxusercontent.com/u/2758854/index.md

**Comment by bjornpost** [comment]
@erusev, can you reopen this issue? I'm getting the same error (`Undefined index: content type (8)`), on this input:

    echo (new \Parsedown)->parse("\nFoo\n___\nBar\n");

Tested against master

**Comment by hkdobrev** [comment]
@bjornpost This input is working fine for me. Are you still getting it on latest master? If yes, could you share information about your setup - PHP version, OS?

**Comment by bjornpost** [comment]
Can't reproduce it here anymore as well, you can close this issue. I'll reopen if it occurs again.
