### ISSUE TITLE
Align tables with 'style' attribute instead with 'align'

### ISSUE THREAD

**Issue by kminchev** [erusev/parsedown#156]
This is how Parsedown parses aligned tables:

```
| A1 | B1 | C1 |
| :- | - | - |
| a1 | b1 | c1 |
```

`<td align="left">a1</td>`

Since web and CSS are slowly moving toward HTML5, you should use 'style' attribute:

`<td style="text-align: left;">a1</td>`

**Comment by erusev** [comment]
@kminchev 

Could you do some research and link to or quote official documents on the subject?

**Comment by kminchev** [comment]
This is what I had in mind when I started this issue: http://www.w3schools.com/tags/tag_td.asp

**Comment by kminchev** [comment]
Appreciated!

PS: thoughts on my comment about header row above?

**Comment by erusev** [comment]
> By the way, I think the header row should always be centered. So, the colon should affect only <td> elements.

I'm not sure about this. It doesn't seem to be a part of the spec and it might be a bit controversial.

**Comment by kminchev** [comment]
Controversial how? I can't imagine someone right-aligning their header row. And tables aren't part of the spec to begin with :P 
Here's something you might want to consider: http://www.w3schools.com/tags/tag_th.asp
Now, I know it says regular cells are left-aligned by default, but that's not always the case. Usually columns with numbers are right-aligned, but I can't think of a reason why header should be anything but centered.
I'll be happy to see other people's opinions about this.

**Comment by erusev** [comment]
@kminchev 

Parsedown already uses `th` tags for table headers.

**Comment by naNuke** [comment]
Aligning content with specified user input "inserting colon" is one thing, if user wants to align header rows with colon, it's up to them, but enforcing any kind of style, like aligning headers to center is just plain wrong. I don't see any harm allowing specific alignment of header rows.

If you want your headers to be centered only, just make a css rule with !important.

**Comment by hkdobrev** [comment]
@kminchev That's just my way of thinking, but table headers in HTML are left-aligned by default. Therefore they should be left-aligned by default in GFM.

**Comment by kminchev** [comment]
@hkdobrev, according to the link I pasted above, `th` are centered by default and `td` are lefted.

@naNuke, I know that, I was just thinking out loud if this approach is good enough to make it hardcoded. Anyway, thanks all for your inputs!

**Comment by naNuke** [comment]
@kminchev if th are aligned to center by default, why should parsedown do it then.

**Comment by kminchev** [comment]
@naNuke, in case the user placed a colon on the left.

**Comment by cebe** [comment]
@kminchev in that case the only thing the colon does is changing the alignment to left so it may be used to achieve exactly that. The other columns should not change as `<td>` is left aligned anyway.

Btw, w3schools is not a good source for things like this, here is HTML spec:
http://www.w3.org/TR/html5/tabular-data.html#the-th-element
http://www.w3.org/TR/html401/struct/tables.html#h-11.2.6

Both do not explicitly say to align center but note that it is commonly displayed as such.

**Comment by Ayesh** [comment]
I know this is already resolved and Parsedown uses style tags, but I was bit with a Content-Security-Policy today, because I had blocked inline styles. I'm now using my own markdown class that extends `Parsedown`, and overrides `blockTable` and `blockTableContinue`. 

GitHub still appears to use HTML `align` attributes, and I wish Parsedown had stayed with `align` attributes, but that ship has sailed :)
