### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hkdobrev** [erusev/parsedown#159]
Parsedown is approaching a stable version and it needs some kind of documentation (see #133).
### Implementation

Here are possible implementations:
- Markdown files in the repository;
- Separate repository with Markdown files;
- GitHub wiki;
- HTML files in [`gh-pages`](https://pages.github.com/) branch.

Markdown approaches allow using the files/pages for documentation generators like https://readthedocs.org/ if needed.

I personally prefer the Markdown files to be in the same repository, because:
- Documentation could be written using the same issue tracker and pull requests like the code.
- A single pull request about a piece of code could include a related change in the documentation.
### Contents

What should be documented?

I suggest:
- Public interface - most common use cases.
- Extensibility - writing your own extensions with modifications to the parsing and compiling.
- Tests structure and how/why to add more tests. Also how to test local modifications.
- Porting guide - how to easily port Parsedown to another language. E.g. Describe the algorithm.

**Comment by erusev** [comment]
I added a wiki page about writing extensions.

**Comment by lazlo-bonin** [comment]
The wiki page seems to have been deleted.
