### ISSUE TITLE
Safe Mode

### ISSUE THREAD

**Issue by clphillips** [erusev/parsedown#161]
Parsedown offers no safe option for rendering, so, for those of us who allow **no** HTML content within markdown text, we must sanitize prior to feeding to Parsedown. As a result, Parsedown double encodes HTML entities (see #50).

Instead, Parsedown should offer a "safe" option.

``` php
function text($text, $safe_mode = false) {
    $this->safe_mode = $safe_mode;
    if ($safe_mode) {
        $text = htmlentities($text, ENT_QUOTES, 'UTF-8');
    }
    ...
}
```

Usage:

``` php
$parsedown = new ParseDown();
$text = "<script>alert('unsafe text');</script>";
echo $parsedown->text($text, true);
```

Output:

```
&lt;script&gt;alert(&quote;unsafe text&quote;);&lt/script&gt;
```

**Comment by ckzhou** [comment]
[xss](http://"onmouseover="alert(1))
This vector can pop a alert box in firefox!

**Comment by xorock** [comment]
For several years I used Textile https://github.com/textile/php-textile and there is textileRestricted method which is suitable for untrusted input. As I understand there is no such thing in this library?

**Comment by erusev** [comment]
Would someone like to create a simple set of test data that includes `.md` and `.html` files with input and expected safe output.

**Comment by clphillips** [comment]
@erusev You want that as a PR, or what? Examples here: [XSS Filter Evasion Cheat Sheet](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet).

**Comment by erusev** [comment]
@clphillips Sure, but let's start simple, 5 to 10 pairs to see if this test driven approach would work.

**Comment by erusev** [comment]
Perhaps, we could start with something like: https://github.com/markdown-it/markdown-it/blob/019bbda5f5ee8b7d00f2633340aef3b0d000e3f1/test/fixtures/markdown-it/xss.txt

**Comment by dariuszp** [comment]
Hi, any ETA on this? I need markdown in my latest project. I was thinking of using parsedown but it will be for user generated content.
Because of this issue I had to abandon this library.

**Comment by BboyKeen** [comment]
I'm interested too. Any news for the safe mode ?

**Comment by erusev** [comment]
I've been thinking about this and I do plan to implement it, hopefully in January.

**Comment by hootlex** [comment]
any update on this?

**Comment by erusev** [comment]
Not yet, but perhaps soon.

**Comment by hootlex** [comment]
Great, looking forward.

**Comment by Penagwin** [comment]
Is there any word on this right now?

**Comment by m1guelpf** [comment]
Updates?

**Comment by erusev** [comment]
Not yet, it's taking me some time :(

**Comment by sdkcarlos** [comment]
Well, for me worked perfectly by using the setMarkupEscaped option to true:

```php
$markdown = "The markdown of the following image ... ";

$Parsedown = new Parsedown();

$Parsedown->setMarkupEscaped(true);

echo $Parsedown->text($markdown);
```

For example, the following markdown:

![image](https://user-images.githubusercontent.com/11634719/27253266-8f5dc036-5371-11e7-832f-b80ee360f91e.png)

Would display in the browser the second alert if the `setMarkupEscaped` option isn't set to true. But if it does, it will generate the following HTML without being vulnerable to an XSS attack:

![image](https://user-images.githubusercontent.com/11634719/27253289-e34d8654-5371-11e7-9ee0-fa8a32ec5054.png)

Maybe it was so simple and is not what everybody needs ... but it worked for me and maybe for someone else is useful too.

**Comment by aidantwoods** [comment]
Hi @sdkcarlos,

Apologies for being blunt here, I'd just like to make sure that no one gets the wrong impression.

> it will generate the following HTML without being vulnerable to an XSS attack:

This is **not** the case. Parsedown is **not** safe with only `setMarkupEscaped` enabled.

Parsedown is still vulnerable to XSS attacks other than those introduced by inputting plain HTML tags, because Parsedown does not at present correctly encode data in attributes, nor does it sanitise link destinations (thus allowing use of the `javascript:` scheme).

I'd highly encourage you to take a look at #495 if you would like a version of Parsedown that is safe from XSS.

**Comment by sdkcarlos** [comment]
Thanks for the suggestion @aidantwoods , i've just updated my `composer.json` to [require your version instead](https://github.com/erusev/parsedown/tree/bbb7687f31d6904f3a0e11e97bc61852a62cfe90):

```json
{
    "require": {
        "erusev/parsedown": "dev-master#bbb7687f31d6904f3a0e11e97bc61852a62cfe90",
    }
}
```

now i'm able to use `setSafeMode` and `setMarkupEscaped` 👍

**Comment by aidantwoods** [comment]
`setSafeMode` will flip all the switches that `setMarkupEscaped` would (so no need to set the latter – only `setSafeMode` is needed). Hopefully we can get that patch merged soon, and out as a proper release (updates are always nice – unfortunately can't really do that with fixed version).

Maybe use the following so that your composer will prefer the next stable Parsedown (once it is available)

```json
"require": {
    "erusev/parsedown": "^1.7.0 || dev-master#bbb7687f31d6904f3a0e11e97bc61852a62cfe90",
}
```

(Assuming that the minor version would deserve a bump when this new feature is merged, @erusev 
 could confirm though).

**Comment by aidantwoods** [comment]
Hi @sdkcarlos,

I've implemented the anti-xss patch as a Parsedown extension, so you can now instead require `aidantwoods/secureparsedown` in your `composer.json` – which has the benefit of keeping both Parsedown and the anti-xss extension up to date.

Hopefully we'll see it in Parsedown core at some point though :)
