### ISSUE TITLE
Add ability to add custom attributes

### ISSUE THREAD

**Issue by Lakhman** [erusev/parsedown#172]
Would it be possible to add the ability to add custom attributes to elements that have been parsed? - So we can add things like a `nofollow` tag to links (as well as other things like adding a class to the `<pre>` tags (so we can use it with prettyprint (syntax highlighting) e.g: `<pre class="prettyprint lang-html">` )

So say I generate a link like so:
```
[`Google`](http://google.com "followed link")
```

Perhaps something like adding a `!` after the URL opening bracket?

```
[`Google`](!http://google.com "no-followed-link")
```

Or is this feature already there and am I just missing how to do it?

**Comment by erusev** [comment]
It is possible and quite easy to do through an extension. You can see the wiki for more details.

**Comment by Lakhman** [comment]
Thanks, I haven't had a chance to play with the latest version, it looks awesome!! I'll try write up an extension on the weekend for all my needs!!

Many thanks!
