### ISSUE TITLE
Wrong parser

### ISSUE THREAD

**Issue by ovr** [erusev/parsedown#174]
-   #316  - static property variable concat with variable)
#316 is not header

Please fix it

**Comment by svivian** [comment]
I'm also suffering from this issue. Any chance this will be fixed soon?

**Comment by aidantwoods** [comment]
When #553 is sorted, the new internal features from #433 could be used by an extension to disable nesting of certain select parser elements. I would probably vote against this being default though, since it goes against the commonmark spec.

**Comment by aidantwoods** [comment]
#433 was included in version 1.7.1 so I think that could be used to solve this in an extension relatively easily. Please reopen if that is not the case though :)
