### ISSUE TITLE
Fix nested links

### ISSUE THREAD

**Issue by hkdobrev** [erusev/parsedown#178]
``` md
[link to http://autolink.com/](http://normallink.com/)

---

[link to [another](http://nestedlink.com)](http://normallink.com)
```

---

``` html
<p><a href="http://normallink.com/">link to <a href="http://autolink.com/">http://autolink.com/</a></a></p>
<hr />
<p><a href="http://normallink.com">link to <a href="http://nestedlink.com">another</a></a></p>
```

**Comment by bastianallgeier** [comment]
Any news on this? Kirby users still run into this issue constantly.

**Comment by erusev** [comment]
For the next release, I'm adding a setter that would disable automatic linking of URLs. 

Would that help? 

The reason that the original Markdown extra doesn't have this problem is because it doesn't support automatic linking of URLs.

**Comment by erusev** [comment]
I'm thinking that, perhaps, for Parsedown Extra, it should be disabled by default.

**Comment by erusev** [comment]
@bastianallgeier 

The latest release has a `UrlsLinked` option. Setting it to `false` would disable automatic linking of URLs and prevent the issue.

Alternatively, you could encode the `:` in URLs to make them unrecognisable for the parser (e.g. `http&#58;//parsedown.org`).

I believe that any other solution would introduce too much complexity.

**Comment by bastianallgeier** [comment]
@erusev that's perfect! Thanks for the great update!

**Comment by erusev** [comment]
I'm glad to hear that.

I'm closing the issue.
