### ISSUE TITLE
img wrapped in p

### ISSUE THREAD

**Issue by fxck** [erusev/parsedown#180]
is there a way of disabling wrapping of certain elements(like images) with paragraph?

`![](image.jpg)`

ends up as

`<p><img src="image.jpg" /></p>`

I'd like it to be just 

`<img src="image.jpg" />`

I tried changing few things around in the code, but without much of a success..

**Comment by fxck** [comment]
@erusev has anything changed in recent versions of parsedown? because what @apfelbox posted doesn't really work anymore(`buildParagraph` renamed perhaps)?

also parsedown is wrapping custom elements, be it angular directives or web components in `<p>`, which is in most cases undesirable, I still stand by that there could/should be an option to defined which elements should be wrapped in paragraph and which should not..

**Comment by erusev** [comment]
@fxck Yes. The name of that method changed. It's called just `paragraph` in the latest version.

**Comment by fxck** [comment]
`Argument 1 passed to Parsedown::element() must be of the type array, null given`

when either `$this->inlineLink($Line['text']);` or `$this->inlineLink($Line);` used

**Comment by fxck** [comment]
`$this->inlineImage()` works

**Comment by erusev** [comment]
@fxck 

Right.

It'd be great if you could update the gist.

**Comment by fxck** [comment]
Can't really, it's @apfelbox's here a new one though https://gist.github.com/fxck/d65255218de3611df3cd

**Comment by erusev** [comment]
@fxck 

Great, thanks.

**Comment by apfelbox** [comment]
(I updated my gist to reflect the latest changes)

**Comment by kantoniak** [comment]
Updated the gist to work with 1.7.1 and wrap images in `<figure>` instead of leaving them as-is:
https://gist.github.com/kantoniak/b1a5c7889e5583824487dc78d93da7cd
