### ISSUE TITLE
Pipe character can not be used within tables

### ISSUE THREAD

**Issue by Seldaek** [erusev/parsedown#184]
Source:

```
Foo | Bar | State
------ | ------ | -----
`Code | Pipe` | Broken | Blank
`Escaped Code \| Pipe` | Broken | Blank
Escaped \| Pipe | Broken | Blank
```

Current Output (github markdown is also affected so this works as a demo of the problem):

Foo | Bar | State
------ | ------ | -----
`Code | Pipe` | Broken | Blank
`Escaped Code \| Pipe` | Broken | Blank
Escaped \| Pipe | Broken | Blank

Expected:

Foo | Bar | State
------ | ------ | -----
<code>Code &#124; Pipe</code> | Broken | Blank
<code>Escaped Code \\&#124; Pipe</code> | Broken | Blank
Escaped &#124; Pipe | Broken | Blank

**Comment by erusev** [comment]
I believe that the latest release resolves this. You can test it in [the demo](http://parsedown.org/demo).

**Comment by cebe** [comment]
Looks great, a little thing remaining:

```
`Escaped Code \| Pipe`
```

Parse result is ``Escaped Code | Pipe`` inside of tables but `Escaped Code \| Pipe` out side.

**Comment by erusev** [comment]
@cebe 

Right. I'm working on that.

**Comment by erusev** [comment]
Thanks to the idea of @cebe this seems to be completely resolved now.
