### ISSUE TITLE
Might want to include this example

### ISSUE THREAD

**Issue by mofosyne** [erusev/parsedown#185]
This is an alternative to "include" for those who want a simple way to quickly include text from a file to a page. This would be useful under example pages, if you have any.

~~~~
function parsedownInclude($f){
	require_once 'Parsedown.php';
	$Parsedown = new Parsedown();
	echo is_readable($f) ? $Parsedown->text(file_get_contents($f)) : "File Not Found".htmlspecialchars($f);
}
~~~~

edit: thanks hkdobrev, noted
2nd edit: Used ternary operators to make it more elegant

**Comment by erusev** [comment]
@mofosyne 

I can see the value in this, but don't think that it solves a popular enough problem for it to be in the documentation. I appreciate the contribution, but I'm going to close this.
