### ISSUE TITLE
XSS Image Tag

### ISSUE THREAD

**Issue by xLink** [erusev/parsedown#210]
Hey im using your parser in a laravel install, just had someone post 
```md
![" onerror="alert(1)](0 ""alert(2);")
``` 

and it return
 
```html
<img alt="" onerror="alert(1)" src="0" title=""alert(2);" />
```
with this the alert(1) was fired, is there anyway to have this fixed? I am already doing an escape within my code before the markdown gets parsed, but ofc it wouldnt pick this up :/

**Comment by erusev** [comment]
I'm closing this as a duplicate of #161.
