### ISSUE TITLE
Make parsedown 'CommonMark' ready/compliant

### ISSUE THREAD

**Issue by vkbansal** [erusev/parsedown#213]
Is parsedown [CommonMark](http://commonmark.org/) ready/compliant?

Edit: Standard markdown is now CommonMark
source: http://blog.codinghorror.com/standard-markdown-is-now-common-markdown/

**Comment by aleemb** [comment]
I keep coming back to this issue every few weeks, especially as higher-order frameworks are favouring embedding CommonMark libs now as their default implementations.

ParseDown still has way better performance and combined with CommonMark compliance, it would be a big win. Hope there can be a single flag to turn CommonMark compliance on/off and get full test coverage.

At the moment 276 of 598 tests failed for CommonMark. The tests themselves need updating as well.

**Comment by erusev** [comment]
@aleemb the next version will have much better compliance

**Comment by aleemb** [comment]
@erusev glad to hear it. I first test drove Parsedown following your HN comment[1] some months back and was really impressed by the commitment to perf.

There isn't any branch for the dev version. Do you plan to do internal dev and then release it to master? Just curious as to the progress of it and your release process.

  [1]: https://news.ycombinator.com/item?id=8796457

**Comment by anthonywilliams** [comment]
There's an outstanding pull request from my fork which adds some commonmark compliance features:
https://github.com/erusev/parsedown/pull/334

**Comment by grangeway** [comment]
@anthonywilliams can I just ask what testsuite are you using to get to 653 tests (the common mark suite seems to have 599 at the moment which is similar to the number aleemb mentioned - so i'm just wondering where the difference is coming from)

**Comment by grangeway** [comment]
@erusev - and does "next version will have better support" mean work has started or it's worthwhile looking at antony's current pull request and giving feedback/additional fixes?

**Comment by erusev** [comment]
@grangeway i have thoughts on what the implementation should look like, but before that, I'd like to finish "save mode"

**Comment by grangeway** [comment]
in which case, will leave it to you :)

**Comment by anthonywilliams** [comment]
@grangeway I just ran "phpunit --bootstrap test/bootstrap.php test" in the working directory
@erusev If you're working on this, that's great :-)

**Comment by aidantwoods** [comment]
I'm going to close this for the same reasoning as in #588:

CommonMark (or more specifically the GitHub flavoured extension) is definitely a goal. But as mentioned in https://github.com/erusev/parsedown/issues/588#issuecomment-377221179 there are some things that Parsedown won't be able to get right without major compromises in speed (or at least a complete design overhaul: this would almost certainly involve Parsedown having to do *a lot* more work than it currently does).

Assuming the absence of a complete rewrite, this issue would *technically* never be closable as resolved (in a fully-compliant sense). As an acknowledgement of this limitation I'm closing it more as a "won't-fix". That said, still please open issues for individual non-compliances, hopefully we can get most of them fixed :)

For a list of issues solved recently—most aiming at CommonMark compliance—take a look at: https://github.com/erusev/parsedown/milestone/2?closed=1
