### ISSUE TITLE
Making a Joomla plugin with Parsedown

### ISSUE THREAD

**Issue by smanzi** [erusev/parsedown#219]
Hi,

I'm developing a Joomla plugin using your Parsedown code and I'm willing to contribute it to the Joomla community as a free extension: I'm wondering if it is OK to ship your code together with my extension...

Also, I'm modifying your code to apply a *class="parsedown"* attribute to some elements (tags) (e.g. 'table', 'pre', 'ul', etc.), so that they can be styled in a different way. What do you think?

Regards,

Sergio

**Comment by erusev** [comment]
@smanzi 

> Thanks for answering and... great library, it works like a charm!
I'm unsure to understand you when you talk about "implement this in an extension": do you have any doc/example to point me at?

You could have a look at Parsedown Extra.

Adding classes to elements should be easy. You'd nee to override the corresponding method and change its result. For example, to add classes to tables, you'd need to override `blockTable`.
