### ISSUE TITLE
About Recursive Regex

### ISSUE THREAD

**Issue by joyqi** [erusev/parsedown#223]
Hi, I'm working on a CoffeeScript port of Parsedown (https://github.com/joyqi/parsedown-coffee).
I migrate the php code to CoffeeScript line by line, so they will render the same HTML code at the end.

But there is a recursive regex in method `identifyLink`, and javascript don't support recursive regex. Do you have some suggestions?

```php
    protected function identifyLink($Excerpt)
    {
        $extent = $Excerpt['text'][0] === '!' ? 1 : 0;

        if (strpos($Excerpt['text'], ']') and preg_match('/\[((?:[^][]|(?R))*)\]/', $Excerpt['text'], $matches))
        {
```

**Comment by erusev** [comment]
@joyqi 

It doesn't have to be recursive. You can have a look at the regex that I added in https://github.com/erusev/parsedown/commit/9ed72ccd0943436f1c47d6ea6e528857bdc0da3c and use the same principle.
