### ISSUE TITLE
Why is Parsedown removing all line breaks?

### ISSUE THREAD

**Issue by stonetwig** [erusev/parsedown#227]
```
# trim line breaks
$markup = trim($markup, "\n");
return $markup;
```

In my code, I need to break up the markup afterwards to do some operations on it and since all line breaks are removed this causes problem for me and I will have to convert the markdown line for line. 

Why is all line breaks removed?

My guess is that in the future people may have the same issue since this is kind of unexpected behavior, an idea would be functionality to skip that last trim with a parameter or something :)

**Comment by erusev** [comment]
@stonetwig 

I'm not sure I understand.

> Because when the markdown is converted to html, I want to be able to add attributes and classes to the html to be able to style the html that comes out.

How would having new line characters around the output help you with that?
