### ISSUE TITLE
Rendering issue: links that contain asterisks in lists in markdown blocks

### ISSUE THREAD

**Issue by maxfenton** [erusev/parsedown#230]
I found a strange rendering bug that appears when making a list item inside a `<div markdown="1">` block that contains an ampersand (&) in either a link or link title.

Expected: links would be rendered in a list the same as outside of a `<div markdown="1">` block.

Raw markdown:
https://gist.githubusercontent.com/maxfenton/ea17ad4affe5de8f37d7/raw/b55a19aadef23263244c764ce788088b3486f53c/kirby-panelmarkdown-test.md

Output: 
![screen shot 2014-09-30 at 5 51 34 pm](https://cloud.githubusercontent.com/assets/906502/4467084/f8de220a-48eb-11e4-97c5-4a127e6d78cb.png)

**Comment by erusev** [comment]
I believe that this is resolved in the latest release.

**Comment by maxfenton** [comment]
Thank you!
