### ISSUE TITLE
Rendering ```php+html issues

### ISSUE THREAD

**Issue by harikt** [erusev/parsedown#232]
When rendering this source https://github.com/harikt/aurav2book/blob/186fb12a5bfedbb62b45c9fd5d9224f3cc22deb5/manuscript/helpers.md#a-a it is producing wrong output .

See http://ghdocs.herokuapp.com/harikt/aurav2book/186fb12a5bfedbb62b45c9fd5d9224f3cc22deb5/manuscript/helpers.md#a

Tag is like 

```
html+php
<?php
echo $this->a(
    'http://auraphp.com',       // (string) href
    'Aura Project',             // (string) text
    array('id' => 'aura-link')  // (array) optional attributes
);
?>
<a href="http://auraphp.com" id="aura-link">Aura Project</a>
```

Removed the 3 ticks.

**Comment by erusev** [comment]
@harikt 

What part of the output is wrong?

**Comment by harikt** [comment]
Did you noticed the link and the syntax I wrote :) .

**Comment by erusev** [comment]
It'd be best if you could provide a short Markdown text together the expected HTML.

**Comment by hkdobrev** [comment]
I think when there is a `+` character after the "```" characters it doesn't get parsed as a code block, because of the regex used or something similar.

**Comment by harikt** [comment]
This is markdown. I wonder whether you will see the real markdown for this will be rendered by github .

    ```html+php
    <?php
    echo $this->a(
        'http://auraphp.com',       // (string) href
        'Aura Project',             // (string) text
        array('id' => 'aura-link')  // (array) optional attributes
    );
    ?>
    <a href="http://auraphp.com" id="aura-link">Aura Project</a>
    ```

The expected output is 

```php
<?php
echo $this->a(
    'http://auraphp.com',       // (string) href
    'Aura Project',             // (string) text
    array('id' => 'aura-link')  // (array) optional attributes
);
?>
<a href="http://auraphp.com" id="aura-link">Aura Project</a>
```

and what it produce is 

```
```html+php <?php echo $this->a(

'http://auraphp.com',       // (string) href
'Aura Project',             // (string) text
array('id' => 'aura-link')  // (array) optional attributes
); ?>
```

**Comment by harikt** [comment]
Hey @aidantwoods , 

I guess the problem is with the finding of regex . ` ```html+php ` , ie a wild guess.

Eg : This one uses two languages, html and php. So may be if I change to make use of only php this issue will be fixed I guess.

Not a major issue for me. Thanks once again.

**Comment by harikt** [comment]
Hi @erusev ,

Looking into this issue, I noticed I didn't replied to you properly or on time. I may have carried away with something else. Sorry for the behaviour. And thank you for the wonderful library.
