### ISSUE TITLE
Edge cases I commonly run into

### ISSUE THREAD

**Issue by skyzyx** [erusev/parsedown#233]
This can probably be filed under CommonMark-parity.

https://gist.github.com/skyzyx/2b3183cd890affd877a4

**Comment by erusev** [comment]
@skyzyx 

What part of the output that Parsedown produces is in conflict with your expectations?

**Comment by aidantwoods** [comment]
Please feel free to reopen with more info – unfortunately I'm not entirely sure what the issue is in this case.
