### ISSUE TITLE
I add setImagePath

### ISSUE THREAD

**Issue by wooygcom** [erusev/parsedown#245]
First of all... Thanks for this awesome program. ^^

I have a suggestion.

When I use this with image file.
I have a problem.

Let say I have a files like below...

program/read.php
data/sample.md
data/image.jpg
data/movie.mov

And it makes error when I use ** ![Image](./image.jpg) ** in sample.md

so I little bit change

--------------------------------------------------------------------------------

```
class markdown {
..................
    function setImagePath($imagePath)
    {
        $this->imagePath = $imagePath;

        return true;
    }

    private $imagePath = '.';

.....................

// I use $imagePath Here~ :-)
    $markup .= '<img alt="'.$element['text'].'" src="'. $this->imagePath .$element['link'].'" style="width:100%;" ';

.....................
}
```

--------------------------------------------------------------------------------

Have a good day~

**Comment by erusev** [comment]
I see the value in this, but I'm not sure it belongs to the core Parsedown class. You could implement it with a quite simple extension. It'd have to override the inlineLink method and modify the result of the parent method. That's all.

**Comment by erusev** [comment]
You can see a working example in [the wiki](https://github.com/erusev/parsedown/wiki/Writing-Extensions).

**Comment by wooygcom** [comment]
Wow... cool.. Thank you for reply. Have a nice day. :-)
