### ISSUE TITLE
parse link error

### ISSUE THREAD

**Issue by muhas** [erusev/parsedown#246]
```
  ><footer><cite> [links](http://google.com) </cite></footer>
```

generate

```
  <blockquote>
  <footer><cite> [links](http://google.com) </cite></footer>
  </blockquote>
```

ps. github parser normal, so http://pastebin.com/DSSDmSmH

**Comment by erusev** [comment]
@muhas 

What is the output that you'd expect?

**Comment by muhas** [comment]
@erusev 
    <blockquote>
    <footer><cite> <a href="http://google.com">http://google.com</a> </cite></footer>
    </blockquote>

**Comment by aidantwoods** [comment]
The current result seems to mirror CommonMark, which says that markdown shouldn't be parsed when inside HTML in this way.
