### ISSUE TITLE
How to embed video?

### ISSUE THREAD

**Issue by dmiepub** [erusev/parsedown#256]
How to embed video using parsedown, please reply.

**Comment by 9v-kz** [comment]
@erusev ![image](image_link)
!![video](video_link)

**Comment by 9v-kz** [comment]
@erusev image
```
!![image](image_link)
!![youtube_video](youtube_video_link)
```

**Comment by lordadamson** [comment]
just paste the embed code in the middle of your markdown code and it should work.

Example:
```
# some markdown title
<iframe width="560" height="315" src="https://www.youtube.com/embed/WJT38OdTPQU" frameborder="0" allowfullscreen></iframe>
* more markdown stuff
* amazing list
```

Note however that github doesn't support embedding videos. So the workaround is usually placing a photo link to the youtube video.
