### ISSUE TITLE
Markdown not parsed after figure tag in same paragraph

### ISSUE THREAD

**Issue by bastianallgeier** [erusev/parsedown#257]
I just found an issue with figure tags in paragraphs, which break the parser afterwards. Here's the example, which you can try in the demo and see the difference between PHP Markdown and Parsedown: 

```
<figure></figure> Some text with **markdown**
```

**Comment by erusev** [comment]
Since `figure` is a block-level element (or isn't a text-level element), it needs to follow the rules for block-level elements in order to get parsed correctly:

> The only restrictions are that block-level HTML elements — e.g. <div>, <table>, <pre>, <p>, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) <p> tags around HTML block-level tags.

Here's an example that should work:

```
paragraph

<figure>
    <img attr="value" />
</figure>

paragraph
```

**Comment by bastianallgeier** [comment]
You are right! Sorry for reporting this as an issue.
