### ISSUE TITLE
Handling of Invalid HTML

### ISSUE THREAD

**Issue by pchri** [erusev/parsedown#259]
I want to use Parsedown on a site that I run for a small group of people. Currently the users can write plain text messages on the site, but I would like to use Parsedown to allow them to make the text look a little more interesting. However, obviously I have no control over what the users write, but I would like to have control over what HTML gets generated so that it doesn't break the rest of the site.

My problem is, that the users might try to add HTML to their text. And that it is not necessarily valid HTML.

For the input

```
<div><p>
```

Parsedown generates

```
<p><div><p></p>
```

Obviously this is illegal HTML in any context (paragraph inside paragraph), but it also leaves an open div-element that will break the layout of the rest of my site.

(The simpler case with just the div start element is not such a big problem, because browsers will close the div when they see the paragraph end element)

I know that no sane person would write this input, but I still think that Parsedown should generate valid HTML for any input.

I have found a site that [compares the HTML generated by various Markdown implemetations](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Cdiv%3E%3Cp%3E), and this shows that almost none of the tested implementations get it right.

Currently my workaround is to feed the output of Parsedown into an XML parser, and print it back out. This ensures that there are no open tags, but I have very little control. Another possible workaround could be to use javascript to add the generated HTML to the innerHTML of a div element, but again I feel this shouldn't be necessary.

**Comment by erusev** [comment]
What is the output that you'd expect?

**Comment by pchri** [comment]
Ah, yes I should have stated that in my first post...

Actually I'm not so fuzzy about that. 

I would consider an empty output as perfectly acceptable, but I would like to see something like

    <div><p></p></div>

or

    <p></p><div><p></p></div>

I.e. close any open tags.

Another problem is when the source tries to close tags that are not open, i.e.

    </div>

The current output is

    <p></div></p>

which is not good. Again I'm not particularly fuzzy about the output as long as it is valid. I would accept an empty output, or any of

    <p></p>
    <p><div></div></p>
    <p>&lt;div&gt;</p>

I really appreciate, that you take time to look at this.

**Comment by smz** [comment]
@pchri 

>... but I still think that Parsedown should generate valid HTML for any input.

I'm afraid your expectations far exceeds what is reasonable to expect: Parsedown will generate valid HTML from **markdown** that it is feed of, but you can't expect it to be a magic wand fixing invalid HTML.

My personal advice in your case would be to sanitize user input by stripping **any** HTML before passing it to Markdown.

Loooooong decades ago, when I first approached programming, I learned about an acronym that I think is still holds: GIGO (Garbage In - Garbage Out) :stuck_out_tongue_winking_eye:

**Comment by hkdobrev** [comment]
Even if Parsedown does improve the validity of the output a bit in these, it cannot be enough for you. It is not hard at all with Markdown to generate input which would be either invalid or unspecified. You could use HTMLTidy to literally "tidy" the output. It has quite good options for invalid HTML, empty elements, blacklisting and whitelisting etc. And even if Parsedown does indeed output correct HTML, it would not be in its current scope to blacklist iframes for example.

**Comment by pchri** [comment]
@smz
I don't necessarily expect parsedown to fix the HTML input. It can ignore the html or treat it as text and generate html-entities for it for all I care. My last example shows just that. So I don't expect parsedown to fix the html, but I still expect the output to be valid.

I am familiar with GIGO, but having a background that includes compiler construction I have always felt that GIGO is a sign of low quality in software. (I'm **not** saying that parsedown is low quality. It is free, and easy to use and it does what it says on the package and I can work around the problems I encounter). Imagine a compiler (or interpreter) for a programming language. GIGO allows the compiler to erase the entire harddisk when it encounters a syntax error. A good compiler produces a helpful error message and does *not* generate false code.

I guess I see parsedown as a compiler translating markdown to HTML and I would actually also be happy if parsedown gave me an error indication on the invalid input.

@hkdobrev 
Unfortunately my hosting service does not support HTMLTidy or the PHP Tidy extension. As stated I use an XML parser to do some tidying up, and it would be fairly easy for me to blacklist iframes in that context if I wanted that.

Anyway, thank you for your time.

**Comment by smz** [comment]
@pchri 
> I guess I see parsedown as a compiler translating markdown to HTML and I would actually also be happy if parsedown gave me an error indication on the invalid input.

That's correct. But to achieve what you are expecting Parsedown should also be able to parse HTML (to judge on its validity) and this, I think, is beyond its scope.

**Comment by aidantwoods** [comment]
Parsedown has a safe mode which can be enabled to escape HTML all together, (as well as preventing other dangerous things like javascript links). I think it is out of scope to try and ascertain the validity of HTML given by the user though – this could perhaps be done by an external library which specialises in parsing HTML.

**Comment by smz** [comment]
Nice to see this has been finally solved, @aidantwoods !

Have you taken parsedown in your hands?

**Comment by aidantwoods** [comment]
> Nice to see this has been finally solved

No worries! :) You can read a bit about enabling safe mode [here](https://github.com/erusev/parsedown#security).

> Have you taken parsedown in your hands?

Parsedown is still @erusev's, I've been helping out with some things this past month though :)

**Comment by smz** [comment]
> Parsedown is still @erusev's, I've been helping out with some things this past month though :)

Good! I once wrote a Joomla plugin for Parsedown... maybe I'll update when a new release will be available... Thanks for your effort!

(BTW, last hour I was reading your personal site... fascinating stuff! +1!)
