### ISSUE TITLE
angular directives / web components treated as inline elements and wrapped with paragraph

### ISSUE THREAD

**Issue by fxck** [erusev/parsedown#263]
If I create an element directive called `gallery`, it's gonna end up wrapped with paragraph(most likely because parsedown doesn't recognize it as a block element).

So 

```
<gallery
  images="1,2,4,7"
  type="accordion"
  foo="bar">
</gallery>
```

becomes

```
<p><gallery
  images="1,2,4,7"
  type="accordion"
  foo="bar">
</gallery><p>
```

which is in most cases undesirable.

I wish there could be an array of elements that should be considered block, similar to `$voidElements` and `$textLevelElements`(which I have no idea what are used for).

**Comment by erusev** [comment]
In order for Parsedown to recognise this as an HTML element, the opening tag should be on a single line.

**Comment by fxck** [comment]
no way around it? given the number of attributes angular directives can possibly have it's pretty much unreadable when all in one line..

**Comment by erusev** [comment]
You could wrap your markup in a tag that means nothing or that has no effect on your output.

**Comment by fxck** [comment]
So it's not problem of gallery being treated as inline element, it's a problem of opening tag not being on a single line. Wrapping it with a `<div>` "way around it", but could you consider some better solution?

I mean this could easily happen as well 

```
<div
  class="something"
  
  some-directive
  some-additional-attribute
  
  ng-if="1 == 2"
  ng-class="{
   'foo': bar
  }>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis auctor purus sed cursus hendrerit. Maecenas vulputate elit sit amet tempor porta.

</div>
```

and it's gonna end up even worse than my gallery example..

```
<p>&lt;div
class=&quot;something&quot;</p>
<p>some-directive
some-additional-attribute</p>
<p>ng-if=&quot;1 == 2&quot;
ng-class=&quot;{
'foo': bar
}&gt;</p>
<p>hey</p>
<p></div></p>
```

**Comment by erusev** [comment]
> So it's not problem of gallery being treated as an inline element, it's a problem of opening tag not being on a single line.

That's correct.

> could you consider some better solution?

I thought about it, but the solutions that come to mind are too complicated.

I'll let you know if I think of a simple solution, though.

**Comment by fxck** [comment]
Alright, thanks.

Disadvantage of this line by line approach I suppose.
