### ISSUE TITLE
Broken Headlines in the latest version

### ISSUE THREAD

**Issue by bastianallgeier** [erusev/parsedown#265]
Unfortunately the latest version comes with this pretty massive bug: 

```
##heading
```
is being converted to

```
<p>##heading</p>
```

**Comment by erusev** [comment]
@bastianallgeier 

This is expected. Headers need a space between the `#` and the text. This is dictated by the CommonMark spec. You are the second person to complain about it. I should perhaps change it back.

**Comment by rhukster** [comment]
Even in the **not-so-specific** Gruber spec, they have spaces:

http://daringfireball.net/projects/markdown/syntax#header

**Comment by erusev** [comment]
@rhukster 

True, but it's likely that a huge number of Markdown texts don't have these spaces.

**Comment by bastianallgeier** [comment]
I didn't even find it myself. I added it to Kirby's develop branch a couple hours ago and already got a ticket for it. I get that it's officially not documented that way, but I'm sure that lots of people write it like that.

**Comment by erusev** [comment]
@bastianallgeier 

I believe that to be true. I'll release a patch within the next 10 min.

**Comment by rhukster** [comment]
True, I guess it depends on how close to the CommonMark spec you are trying to get.  Is it possible to have a toggle/option at some point to enforce markdown or legacy?

**Comment by bastianallgeier** [comment]
@erusev awesome! I think it's a lot about usability in this case, so I'm glad you see it this way as well.

**Comment by bastianallgeier** [comment]
@rhukster @erusev I wouldn't add too many "toggles". They add complexity and probably negatively affect the performance. Where's the harm if it does follow the specs but also is slightly more forgiving?

**Comment by erusev** [comment]
The release is out.

**Comment by erusev** [comment]
@rhukster 

It is possible. It could be just one toggle. I'm considering it.

**Comment by cebe** [comment]
The only conflict this has is that if you write markdown like this:

```

- #123 abc
- #456 def

```

you will get headlines instead of issue numbers...

**Comment by rhukster** [comment]
Well in this case the CommonMark explicitly says:

> The opening sequence of # characters cannot be followed directly by a nonspace character.

http://spec.commonmark.org/0.14/#atx-headers

If the spec didn't mention it, then it would be fine.  But the whole point of CommonMark is to tidy up issues related to lack of detail in the original spec. 

I know changes like this could potentially break lots of people's content, hence the idea for the toggle.  This forgiving change actually makes Parsedown less CommonMark compatible.

**Comment by rhukster** [comment]
Here's an even better CommonMark spec quote:

> A space is required between the # characters and the header’s contents. Note that many implementations currently do not require the space. However, the space was required by the original ATX implementation, and it helps prevent things like the following from being parsed as headers:

**Comment by naNuke** [comment]
Why is this an issue that needs to be solved by parsedown, if the goal is to follow commonmark, then it should, users who cant spend time to fix their markdown files and add spaces after # (which isnt that hard) can just extend the parser and remove that rule?

**Comment by erusev** [comment]
@rhukster 

I agree. Ideally, the parser would be tolerant to existing Markdown texts and have an option that deals with things like this. It could be done without adding too much complexity.

**Comment by bastianallgeier** [comment]
@erusev if the toggle is easy to add and doesn't add much complexity, it's probably the best way to please us all :) Personally I think the power of Markdown has always been the focus on writers — even those without a technical background. The specs are a great tool to tidy stuff, but in the end it's all about the users/writers.

**Comment by erusev** [comment]
@naNuke 

This might be true, but before we make changes that would break existing texts Parsedown should at least provide that extension that would make the existing texts work. I'm in favour of compliance, but I believe that it should be done without breaking things.

**Comment by naNuke** [comment]
@erusev 

I completely agree, as long as compliance is not given up in favor of supporting every single possibility of different markup style (which can lead to more problems than it is worth), thats what the spec is for anyway.
Maybe in future things like this could be unified under single "strict" setter, where strict parsing would mean fast and reliable while "non-strict" might be slower and possibly broken in some edge-cases.

**Comment by erusev** [comment]
@naNuke 

I'm glad to hear that. A "strict" setter sounds good .

**Comment by rhukster** [comment]
I like it :+1:
