### ISSUE TITLE
elements() no longer accept text

### ISSUE THREAD

**Issue by jtojnar** [erusev/parsedown#268]
I created an [extension](https://gist.github.com/jtojnar/3a69cd23b1b57f699497
) which adds HTML5 details block. In recent update, unfortunately it stopped working. I already updated new method names but I can’t create the element because Parsedown no longer allows me to pass text to elements method ([relevant commit](https://github.com/erusev/parsedown/commit/ac68800717be80cd27d385c628ced303b221e347#diff-ed0d3da57330712681e64f838087ea47L953)).

How should I change my code?

Currently I am using [modified parsedown](https://github.com/jtojnar/parsedown/compare/erusev:21a3e8790a876865f99540757fe74197df528ea7...master).

**Comment by erusev** [comment]
The `element` of blocks can no longer be a string. However, blocks are no longer required to have an `element`. Instead, they can have a `markup` and `markup` must be a string.

The `blockMarkup` and `blockComment` methods use it. You should check them out.

**Comment by jtojnar** [comment]
Thanks. I changed it accordingly. [ParsedownExtended.php](https://github.com/jtojnar/eudyptes/blob/2d34f9d7a22a35917c494417b45c696c8300e995/vendor/others/ParsedownExtended.php)
