### ISSUE TITLE
unmarkedInlineUrl callback

### ISSUE THREAD

**Issue by xPaw** [erusev/parsedown#269]
I am doing some filtering on URLs and appending extra attributes when needed (by using `inlineLink` and `inlineUrl` functions), but `unmarkedInlineUrl` replaces with a `<a>` element directly, making it harder to apply same logic. Anything that could be done about this?

**Comment by naNuke** [comment]
Atm, the best solution I could come with is to just copy/paste whole unmarkedInlineUrl function into your extension and do your changes there. Also will need to copy the $urlsLinked property because it is private and cant access it from extension.

**Comment by erusev** [comment]
@naNuke Thanks for bringing that up. We should definitely update these properties to make them protected. 

@xPaw I'll see what I can do.

**Comment by erusev** [comment]
@xPaw 

The latest release should address your issue. The `unmarkedInlineUrl` method became `inlineUrl` and `inlineUrl` became `inlineUrlTag`. Both methods return associative arrays with an `element` field that holds the structure of the HTML element that they would produce. I've updated the wiki to address the changes.

**Comment by xPaw** [comment]
Thanks, it worked.
