### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by schucan** [erusev/parsedown#272]
Is there a changelog anywhere?

I track this repository thorugh versioneye and see all the new versions. But I somehow couldn't find an easy way to see what is being added/changed and why it is a minor or bugfix version bump.

**Comment by kminchev** [comment]
No. Parsedown is developed in a GIT based repository. ChangeLog is part of SVN. Closest thing you can get is https://github.com/erusev/parsedown/commits/master

**Comment by hkdobrev** [comment]
I don't think @schucan had SVN ChangeLog in mind. Perhaps something more like: https://github.com/twbs/bootstrap/releases

For the time being you could compare two releases this way: https://github.com/erusev/parsedown/compare/1.4.5...1.5.0

**Comment by schucan** [comment]
Thank you! Actually, I was thinking more about something marketingy and human-readable. Maybe "release notes" is a more appropriate.
Like this: https://github.com/michelf/php-markdown#version-history
Specifically, I would love to directly see why a new release is a minor or bugfix version bump.

**Comment by hkdobrev** [comment]
@schucan FYI http://semver.org/

**Comment by schucan** [comment]
@hkdobrev that's exactly what I mean. As it says there:

    MAJOR version when you make incompatible API changes,

--> This should be in the release notes in the case of a MAJOR version jump:  
what are the **incompatible API changes**?

    MINOR version when you add functionality in a backwards-compatible manner, and

--> This should be in the release notes in the case of a MINOR version jump:  
what is the **added functionality**?

    PATCH version when you make backwards-compatible bug fixes.

--> This should be in the release notes in the case of a PATCH version jump:  
what are the **bug fixes**? **<-- this is the point answered by your previous answer**

Just to be very clear: I am perfectly aware that this is an added effort for you the developers! I would just really appreciate it - and so would others, I suppose. Otherwise, I have to read through all the bugs and changeset comments to figure out the consequences for my use of parsedown.

Keep up the really nice work - and thank you!

**Comment by hkdobrev** [comment]
Just an idea: https://github.com/tj/git-extras/wiki/Commands#git-changelog

**Comment by cebe** [comment]
> Just an idea: https://github.com/tj/git-extras/wiki/Commands#git-changelog

This would require every git commit to have a meaningful message and actually be relevant.
A CHANGELOG is additional to the git history to contain more userfriendly description about which changes are relevant if you upgrade to this verson.

**Comment by erusev** [comment]
I'm convinced. I'll make an effort to describe changes in future releases. Perhaps, with the exception of releases that are patches.

**Comment by schucan** [comment]
Thanks Emanuil!

**Comment by avindra** [comment]
+1. I noticed a new release but there wasn't any documentation. Release notes are important to us when we are deciding if integrating an update will cause any breakages or not.

**Comment by cebe** [comment]
@erusev a good example imo: https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md
Adding a short description when you make a change and commit it directly will make it easier to remember what has been done when long time is between releases.

**Comment by rhukster** [comment]
We use a simple markdown format for our changelog that we can easily style with CSS to make it look pretty:

https://github.com/getgrav/grav/blob/develop/CHANGELOG.md

http://getgrav.org/downloads/#changelog

**Comment by erusev** [comment]
Thanks for the suggestions! I'll take them into consideration.

**Comment by Narno** [comment]
I suggests the approach of http://keepachangelog.com

**Comment by avindra** [comment]
Another release, no changelog. Is this up yet?

**Comment by erusev** [comment]
@avindra The last release was a patch release. Since I release a lot of patches and most of them consist of a single commit, I don't think it makes much sense to spend time on writing change logs for them.
