### ISSUE TITLE
Parsedown eats closing ) after a link

### ISSUE THREAD

**Issue by xPaw** [erusev/parsedown#274]
Try this in Parsedown:
```markdown
### Test ([source](https://google.com))
```

it will be rendered as
```html
<h3>Test (<a href="https://google.com)">source</a></h3>
```

PHP Markdown gets it right, and here's a test with GitHub's parser:
### Test ([source](https://google.com))

**Comment by erusev** [comment]
I'll see what i can do. Give me by the end of the week.
