### ISSUE TITLE
URLs are converted to links

### ISSUE THREAD

**Issue by alehandrof** [erusev/parsedown#278]
Given this input:
```
<a href="http://example.com">http://example.com</a>
```

Parsedown outputs:
```
<p><a href="http://example.com"><a href="http://example.com">http://example.com</a></a></p>
```

Clearly this is not desirable.

(P.S. I'm coming from the Statamic forums, where [this issue](https://lodge.statamic.com/support/1113-parsedown-is-parsing-raw-urls-as-simple-) was documented.)

**Comment by erusev** [comment]
You can prevent this by disabling automatic linking of URLs: `$Parsedown->setUrlsLinked(false)`.

**Comment by alehandrof** [comment]
Thanks for the quick response and also for taking the time to cross-post it on the Statamic forums, as it would be something the Statamic devs would either choose to implement by default or expose via a configuration option.

**Comment by erusev** [comment]
@alehandrof Thanks for bringing the issue up.

**Comment by jasonvarga** [comment]
Statamic developer here. We've implemented the option to turn this off in the next version of Statamic (will be 1.10.3). Definitely not a Parsedown issue.

**Comment by erusev** [comment]
@jasonvarga 

Thanks. I appreciate the feedback.

p.s. Since you are a developer at Statamic, I was wondering if you might know something about https://github.com/erusev/parsedown/issues/266.
