### ISSUE TITLE
Parsedown is currently not compatible with PHP 7

### ISSUE THREAD

**Issue by kelunik** [erusev/parsedown#279]
PHP 7 doesn't allow this any longer: http://3v4l.org/62FEh
```php
<?php

class Foo {
    private $a = "php7";
    
    function bar(array $data) {
        return $this->$data['prop'];
    }
}

$foo = new Foo;

var_dump($foo->bar(['prop' => 'a']));
```

All code using something like this has to be changed to:
```php
<?php

class Foo {
    private $a = "php7";
    
    function bar(array $data) {
        return $this->{$data['prop']};
    }
}

$foo = new Foo;

var_dump($foo->bar(['prop' => 'a']));
```

e.g. here: https://github.com/erusev/parsedown/blob/master/Parsedown.php#L1405

**Comment by erusev** [comment]
Thanks! I'll look into it.

**Comment by kelunik** [comment]
That seems to be the only issue. Runs now successfully.

**Comment by kelunik** [comment]
Thanks, you may want to retag it as `issue` instead of `suggestion`. ;-)
