### ISSUE TITLE
Weird I can't figure out.

### ISSUE THREAD

**Issue by gamejerksnet** [erusev/parsedown#282]
Okay so I'm having an issue I can't figure out. Here is my extension:

``` php
<?php namespace App\Extensions;

use Parsedown;

class ParsedownExtension extends Parsedown {

    protected $InlineTypes, $inlineMarkerList;

    public function __construct()
    {
        $this->InlineTypes['@']     =   ['UserTag'];
        $this->inlineMarkerList     .=  '@';
    }

    public function inlineUserTag($Excerpt)
    {
        if (preg_match('/(?:@)([a-zA-Z0-9\_\-\.\=\@\[\]\{\}\(\)\<\>\,\\\*\&\^\%\#\@\!\/\:\;\|\~\`])+\b/', $Excerpt['text'], $matches))
        {
            return array(
                'extent' => strlen($matches[0]),
                'element' => array(
                    'name' => 'a',
                    'text' => '@' . $matches[0],
                    'attributes' => array(
                        'href' => 'http://www.gamejerks.net/members/testing',
                    ),
                ),
            );
        }
    }

}
```

And here is the exact bit that I'm calling it:

``` php
$parsedown = new \App\Extensions\ParsedownExtension();
$comment    =   $parsedown->text( $value );
```

I get error that no method `Parsedown::text()` exists, and when I die and dump `$parsedown` above and it only shows the child class `ParsedownExtension` and I have no clue why it isn't extending properly.

**Comment by erusev** [comment]
The extension looks correct to me. Could you see if it'd work outside of Laravel?

**Comment by gamejerksnet** [comment]
No I am currently pulling it purely as you see. I mean I haven't tried loading in a clean PHP file but I don't see Laravel causing any issues..

**Comment by erusev** [comment]
Could you try it, please?

**Comment by naNuke** [comment]
Dont you overwrite all the types and markers by writing ```protected $InlineTypes, $inlineMarkerList;```?

**Comment by gamejerksnet** [comment]
I'm not sure how I would go about pulling in autoloaded files outside of Laravel.

**Comment by erusev** [comment]
@gamejerksnet 

I asked not because I wanted to suggest to use extension outside of Laravel, but rather because it'd help us find the cause of the problem.

**Comment by aidantwoods** [comment]
Please reopen if there is some more info :)
