### ISSUE TITLE
Incorrect parse when comments followed by any character

### ISSUE THREAD

**Issue by litefeel** [erusev/parsedown#288]
```
<!-- sss -->abc

* abcd
* bbbb
* cccc
```

parse to 

```
s * abcd * bbbb * cccc
```

remove `abc`

```
<!-- sss -->

* abcd
* bbbb
* cccc
```

parse to

- abcd
- bbbb
- cccc

**Comment by skoop** [comment]
I can not reprodice this issue, it seems to work fine for me with current master.

**Comment by erusev** [comment]
@skoop ha, thanks for bringing that up
