### ISSUE TITLE
Create links for header elements

### ISSUE THREAD

**Issue by Abbe98** [erusev/parsedown#290]
Github Flavored Markdown creates links for header elements, for example `#header` would become:
```
<h1 id="header">header</h1>
```

It would be great to see this feature in Parsedown, it could be added as an option or included by default.

**Comment by hkdobrev** [comment]
@Abbe98 See #285.

**Comment by Abbe98** [comment]
Okay, but it would make sense as a option? As said in #285 it would be useful...

**Comment by hkdobrev** [comment]
@Abbe98 It would make sense as an extension. It is not included in Markdown or in GitHub Flavored Markdown. GitHub does use that in the rendering of files and wikis, but not anywhere else and has not included it in the GFM spec: https://help.github.com/articles/github-flavored-markdown/
