### ISSUE TITLE
Links aren't converted when there is a space in the structure

### ISSUE THREAD

**Issue by annando** [erusev/parsedown#291]
See this code:

````
### [Title](http://domain.tld/ )
````

It is converted to:
````
<h3>[Title](<a href="http://domain.tld/">http://domain.tld/</a> )</h3>
````

It works when the space is removed:
````
### [Title](http://domain.tld/)
<h3><a href="http://domain.tld/">Title</a></h3>
````

**Comment by GrahamCampbell** [comment]
I don't think a space is a valid character in a url, so this behaviour is expected.

**Comment by annando** [comment]
I'm parsing content from Diaspora - I cannot change the way they are working.

**Comment by GrahamCampbell** [comment]
They're doing it wrong then. They need to fix this.

**Comment by annando** [comment]
Since I just had another rendering issue I will try another library.
