### ISSUE TITLE
Auto parse image links

### ISSUE THREAD

**Issue by majimboo** [erusev/parsedown#293]
Is there a builtin function to auto parse image links and turn them into image markup?

**Comment by cebe** [comment]
what is an "image link"?

**Comment by naNuke** [comment]
There isnt, but you can modify the automatic link detection via extension, parse the url to see if its .jpg / .png or whatever images you want and change the resulting tag into <img> instead of <a>

**Comment by majimboo** [comment]
@cebe what @naNuke said. Thanks, I guess I'll just write the extension. Any documentation in writing the extension?

**Comment by naNuke** [comment]
@majimboo https://github.com/erusev/parsedown/wiki/Writing-Extensions

All you need to do is something like this:

**Comment by naNuke** [comment]
@majimboo https://github.com/erusev/parsedown/wiki/Writing-Extensions

all you need to do is to rewrite original function which parses inline links, call parent function of same name, catch the result, and if its an array, change the resulting element key from a to img and parameter href to src. :)
