### ISSUE TITLE
Release a new version compatible with PHP7

### ISSUE THREAD

**Issue by fonsecas72** [erusev/parsedown#294]
Hi, it seems to me that current version of parsedown is not compatible with PHP7 yet.
Can you please tag one more version? I think It's worth the effort. :)

**Comment by erusev** [comment]
Sure,

@hkdobrev 

Since u did that for [Base](https://github.com/erusev/base), do u think u could do it for Parsedown as well?

**Comment by hkdobrev** [comment]
I think Parsedown supports PHP 7 since version 1.5.3 and this could be closed now.
