### ISSUE TITLE
Automatic links don't parse correctly inside markdown="1" blocks

### ISSUE THREAD

**Issue by robinadr** [erusev/parsedown#296]
All of the following is from the demo (http://parsedown.org/extra/).

Input:

```
<div markdown="1">
Testing *this*.

<test@test.com>

<http://www.google.com/>
</div>
```

Expected output (also what PHP Markdown Extra shows):

```
<div>

<p>Testing <em>this</em>.</p>

<p><a href="&#109;&#x61;&#105;&#x6c;&#116;&#x6f;&#58;&#x74;&#101;&#x73;&#116;&#x40;&#116;&#x65;&#115;&#x74;&#46;&#x63;&#111;&#x6d;">&#x74;&#101;&#x73;&#116;&#x40;&#116;&#x65;&#115;&#x74;&#46;&#x63;&#111;&#x6d;</a></p>

<p><a href="http://www.google.com/">http://www.google.com/</a></p>

</div>
```

What actually gets output by Parsedown Extra:

```
<div>
<p>Testing <em>this</em>.</p>
<test><http:></http:></test>
</div>
```

**Comment by robinadr** [comment]
Any updates on this?

**Comment by hkdobrev** [comment]
@robinadr I suspect this should be actually reported in Parsedown Extra here: https://github.com/erusev/parsedown-extra/issues and this one should be closed. Sorry for not being much useful.

**Comment by robinadr** [comment]
Fair enough. I'll post it over there.

**Comment by robinadr** [comment]
https://github.com/erusev/parsedown-extra/issues/54
