### ISSUE TITLE
Blockquote has leading and ending <br/> although there are no newlines.

### ISSUE THREAD

**Issue by IngwiePhoenix** [erusev/parsedown#298]
o.o sorry for that long title.

I am sending the following to Parsedown through AJAX:

```
> I am
> A test.
```

But I get the following HTML:

```html
<blockquote>
    <br>
    <p>I am<br>A test</p>
    <br>
</blockquote>
```

How can I get rid of the two `<br>`s?

**Comment by erusev** [comment]
Does the issue reproduce in the demo: http://parsedown.org/demo

**Comment by IngwiePhoenix** [comment]
False warning. The jQuery plugin I use to display text in a bootstrap modal had a bug and caused the extra `<br>`s. I counter-checked on the command line and saw the actual output.

Sorry! :)
