### ISSUE TITLE
Support for GFM-style checkbox lists

### ISSUE THREAD

**Issue by GuzziGuy** [erusev/parsedown#300]
A la https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments - would be great!

**Comment by erusev** [comment]
It would be, indeed, but since it is not a part of the GFM spec, I think that it should be implemented as an extension.

**Comment by leblanc-simon** [comment]
I wrote an extension of ParsedownExtra that adds support of task list : https://github.com/leblanc-simon/parsedown-checkbox

**Comment by hkdobrev** [comment]
@leblanc-simon That's great! Could you please add a link to your extension to the wiki similar to other extensions? https://github.com/erusev/parsedown/wiki/Extensions-and-Related-Libraries Thanks!

**Comment by leblanc-simon** [comment]
Done. Thanks !
