### ISSUE TITLE
# in image title breaks parsing the image

### ISSUE THREAD

**Issue by petermolnar** [erusev/parsedown#304]
I can't tell if this is a feature or a bug: if there is a # in an image title, the image will not be parsed to html. I'm importing content from instagtram and I ended up with entries like this:

`![This is a #post from #Instagram](/path/to/file.jpg/){#id-552}`

Parsedown Extra is enabled and the image refuses to become HTML.

**Comment by hkdobrev** [comment]
I believe this is resolved in latest master. I've tried it both in Parsedown and Parsedown Extra.

**Comment by aidantwoods** [comment]
Seems to be fixed :)
