### ISSUE TITLE
language class should be configurable for <code> elements

### ISSUE THREAD

**Issue by Lakhman** [erusev/parsedown#305]
Hi,

I noticed the following issue when rendering a fenced code block.

    ```php
       <?php echo "some php code"; ?>
    ```

which renders as:

    <pre>
        <code class="language-php"><?php echo "hello world from php!"; ?></code>
    </pre>

---

It would be great if the `language` class prefix could be specified when creating a new instance of parsedown.

I found the line in question here:

https://github.com/erusev/parsedown/blob/master/Parsedown.php#L406

but not sure if it should be a public property that can be set, or if I should use getters and setters for it.

Would it be possible to add this as a property (so by default it uses `language`, - but can be overridden when creating an instance of parsedown (or parsedownExtra).

    $parsedown = new \ParsedownExtra();
    $parsedown->setCodeClass('custom-class-for-code'); // example `setter` for class

This would be awesome to have as various syntax highlighters use different classes, and is sometimes a pain to change it in the javascript, so having the option to do it when we parse the markdown would be a huge help!

Thanks!

**Comment by erusev** [comment]
This could be implemented with a very simple extension - see [writing extensions](https://github.com/erusev/parsedown/wiki/Writing-Extensions). It doesn't seem popular enough to be an option.
