### ISSUE TITLE
User mentions/hashtags support [extension]

### ISSUE THREAD

**Issue by ShNURoK42** [erusev/parsedown#307]
Hi all.
I'am writing user mentions support (like @username) for this markdown library. It's very easy changes for hashtags support (like #markdown).
https://gist.github.com/ShNURoK42/b5ce8baa570975db487c

This gist have two function, one of them extend parsedown for pasre message and find mentions in it. And second for find which users are mention in message.
As it was difficult for me I think it be useful to someone else.
If you have more beautiful code solution please say me, or say about errors in it.

Sorry for my bad English. Thanks.

**Comment by erusev** [comment]
Thanks. Feel free to add a link to the wiki: https://github.com/erusev/parsedown/wiki/List-of-Parsedown-extensions

**Comment by ShNURoK42** [comment]
Ok. Thanks.
