### ISSUE TITLE
Text Alignment Option

### ISSUE THREAD

**Issue by grimmdude** [erusev/parsedown#310]
Would be nice if text could be centered using this syntax:

`->test<-`

as described here: https://simplpost.com/markdown.html

-Garrett

**Comment by hkdobrev** [comment]
@grimmdude You could try creating an extension which does that. It is not a part of the Markdown specification. Check out https://github.com/erusev/parsedown/wiki/Writing-Extensions

Also you could add your extension or just the idea to the list of extensions here: https://github.com/erusev/parsedown/wiki/List-of-Parsedown-extensions

**Comment by erusev** [comment]
@grimmdude I agree with @hkdobrev. I'm closing this but feel free to create an extension and let us know about it.

**Comment by grimmdude** [comment]
Hi There,

Thanks for the response...finally getting back to this.  So to create an extension it's literally just a class extension, right?  It would be nice to have a 'plugin' type functionality in this repo that wouldn't require a new class extension for every third party option. For instance, what if I wanted to write an extension but also wanted to include the features from another extension?  Would I have to extend that extension?  Thanks,

-Garrett

**Comment by erusev** [comment]
@grimmdude I agree, a plug-in system would make sense.

**Comment by grimmdude** [comment]
Hi @erusev,

I added a basic hook functionality in my fork described in the readme if you're interested: https://github.com/grimmdude/parsedown

This should allow others to write 'plugins' without having to extend the core class.  Cheers

-Garrett

**Comment by erusev** [comment]
Thanks, looks interesting.
