### ISSUE TITLE
Anyway to parse .md files directly?

### ISSUE THREAD

**Issue by xiurobert** [erusev/parsedown#311]
The original parser can, so why not Parsedown?

**Comment by hkdobrev** [comment]
@xiurobert Do you have something like #275 in mind?

**Comment by scottchiefbaker** [comment]
@xiurobert I wrote this to do exactly what you're talking about.

https://github.com/scottchiefbaker/MarkdownCLI

**Comment by xiurobert** [comment]
So I decided to use file_get_contents() instead... anyways thanks for the help
