### ISSUE TITLE
Changing Line Combination Character in Paragraph

### ISSUE THREAD

**Issue by akkyie** [erusev/parsedown#320]
First of all, thanks a lot for your great work!

This time, I want to change the character which used to combine lines in paragraph. 
Concretely, this markdown:

``` md
This is
a markdown.
```

will be parsed into:

```
This is a markdown.
```

As you see a space was inserted, and this behavior is suitable for languages which use [word dividers](http://en.wikipedia.org/wiki/Word_divider), but not for some languages which doesn't use it such as Japanese or Chinese. So I want to remove this space.
I found that I can make it realized by changing `'\n'` to `''` on the line 242 in Parsedown.php, but I don't want to tinker the original code.
Is there any solution without changing Parsedown.php itself but with extension?
Thanks

**Comment by hkdobrev** [comment]
Just to confirm, you need

````
This is
a markdown.
```
 to become

```
This isa markdown.
```

Correct?

**Comment by Akkyie** [comment]
Yes, exactly.

**Comment by aidantwoods** [comment]
Something I would advise is opening this issue with the CommonMark spec, maybe a fix could be reached that could be applied to all parsers conforming to the spec in certain situations.
