### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by bobmulder** [erusev/parsedown#322]
Hey @erusev,

Thanks for this cool stuff.. It really helps me for http://cakemanager.org/docs/1.0/.

However, I have some ideas for some new features... I would like to add meta-tags to my pages.... So something like this:
```
meta: "metatag, metatag, metatag"
``` 

would be transformed to some html code...

Just let me know if you wanna talk ;)

Greetz

Bob

**Comment by erusev** [comment]
Sure, send me an email and we can talk.
