### ISSUE TITLE
Placement of functions

### ISSUE THREAD

**Issue by drdhaval2785** [erusev/parsedown#325]
Right now the functions used inside the class are not easy to follow.

If they can be arranged in such a manner that the functions are defined first and used later, it would be better.

Let me elaborate further.
If the function X also calls function Y within its body, function Y should precede function X in code.

**Comment by erusev** [comment]
There are good reasons for the current structure of the class. Hopefully, this will become clearer when I add some comments to the class.

**Comment by drdhaval2785** [comment]
It would be great if you can add some comments.
Waiting
