### ISSUE TITLE
Is it possible to have a fenced block be parsed?

### ISSUE THREAD

**Issue by jerry1970** [erusev/parsedown#331]
When having this:

    * a
    * b ~[](b.jpg)
    * c

the image in the list block is parsed.
But in this case:

    ```
    This is a test ~[](test.jpg).
    ```

the image is not rendered.

I have written an extension for some specific stuff (```*...*``` becomes ```<b class="artist">...</b>```) and getting to know Parsedown a bit better under the hood, but I am not seeing why a list block renders the contents but a code block does not.

I have already tried changing the ```pre``` into ```div``` and even the ```code``` into ```div``` as well, but that still does not parse the contents of the block.

How can I tell my extension to parse the contents of a fenced block? Or should I use a different type of block for this?

Thanks!

**Comment by cebe** [comment]
code blocks are ment to be taken as is and nothing inside them will be threated as markdown. thats the whole point of a code block ;)

**Comment by jerry1970** [comment]
You're right, but symantically there is a difference between a fenced block and a code block. I was talking about a fenced block.

I solved this by creating an extension to make a fenced block that does not other than adding a wrapper DIV with a class, so I can target it using CSS and JS. I decided to use a triple period for this:

     ... gallery
     ![](image1.jpg)
     ![](image2.jpg)
     ![](image3.jpg)
     ...

Seems to work! I forced it to be a true fenced block, so blank lines do not end it (as is the case with a quote).

**Comment by MichielioZ** [comment]
Might be nice to add that option to parsedown-extra ?
You could add a pull request over there.
I'm interested to see how robust your implementation is...

**Comment by jerry1970** [comment]
Good idea. I'll do some more testing before I add a pull request, though. ;)

**Comment by jerry1970** [comment]
This seems to work but I need some more test cases, see if I can break it...

```
    protected function blockFencedCode($Line)
    {
        // $pattern = '/^(['.$Line['text'][0].']{3,})[ ]*([\w-]+)?[ ]*$/'; // works only on a single class name
        $pattern = '/^(['.$Line['text'][0].']{3,})[ ]*(.+)?$/'; // everything after the fence is the class
        if (preg_match($pattern, $Line['text'], $matches)) {
            $Element = array(
                'name' => 'code',
                'text' => '',
            );

            $blockName = 'pre';

            if (isset($matches[2])) {
                // removed this from the Parsedown way, since DPRP doesn't have language blocks
                //$class = 'language-'.$matches[2];
                $class = $matches[2];

                $Element['attributes'] = array(
                    'class' => $class,
                );

                // when a class is given, the block is a DIV and not a CODE block
                $blockName = 'div';
                $Element['name'] = 'div';
            }

            $Block = array(
                'char' => $Line['text'][0],
                'element' => array(
                    'name' => $blockName,
                    'handler' => 'element',
                    'text' => $Element,
                ),
            );

            return $Block;
        }
    }
```

When using just three backticks it will parse into a PRE tag, but with one or more class names, it is a DIV with those class names.

**Comment by jerry1970** [comment]
Ah pity, the contents are not parsed...

**Comment by jerry1970** [comment]
Oops, I think this should belong in the Parsedown Extra section...

**Comment by hkdobrev** [comment]
@jerry1970 You can create a repo for the extension and add it here: https://github.com/erusev/parsedown/wiki/Extensions-and-Related-Libraries

I think Parsedown Extra is mostly meant to conform to Markdown Extra.

**Comment by jerry1970** [comment]
Damn, I didn't even know about that, silly me...
