### ISSUE TITLE
Difference with HR inside UL between MarkdownExtra and ParsedownExtra

### ISSUE THREAD

**Issue by jerry1970** [erusev/parsedown#332]
This code:

    * a
    * b
      ---
    * c

Gives different results in MarkdownExtra and ParsedownExtra.
MDE parses the line as a HR, PDE makes **b** into a header.

When using ```***``` for HR, MDE and PDE render the same.

**Comment by erusev** [comment]
This is expected and in compliance with the CommonMark spec. It happens because it recognises a setext header.
