### ISSUE TITLE
Parsedown returning plain html tags to browser

### ISSUE THREAD

**Issue by timgithinji** [erusev/parsedown#335]
I've installed parsedown and when I run it it is changing the markdown to html but the browser is plainly showing the parsed markdown instead of applying those particular styles for example when I run the following

`{{Parsedown::instance()->text('Hello _Parsedown_!')}}`

I expect when I run it in the browser: 
Hello _Parsedown_!

but instead am getting the following:
`<p>Hello <em>Parsedown</em>!</p>`
and when I view the browsers page source I get the following
```
&lt;p&gt;Hello &lt;em&gt;Parsedown&lt;/em&gt;!&lt;/p&gt;
```
What could be the problem?﻿

**Comment by vluzrmos** [comment]
This is Blade Template Engine?

You need to use that {!! !!} sintax to not escape the contents.

**Comment by timgithinji** [comment]
Thank you so so so much vluzrmos.
