### ISSUE TITLE
Headings inconsistent with the original Markdown renderer

### ISSUE THREAD

**Issue by goblindegook** [erusev/parsedown#337]
I found a trio of issues with the rendering of headers where Parsedown is inconsistent with the original Markdown implementation:
- `####### not an h7` is rendered as a paragraph, while the original Markdown interprets it as `<h6># not an h7</h6>`.
- `# # of levels` (mind the space) is rendered as `<h1>of levels</h1>`.  The original Markdown retains the extra hash as `<h1># of levels</h1>`.
- `# # of levels # #` is also rendered as `<h1>of levels</h1>`.  The original Markdown retains the extra hashes both at the start and the end, `<h1># of levels #</h1>`.

These inconsistencies can be resolved by removing only the first _n_ characters from the start of the string, _n_ being the heading level.  An additional `trim(rtrim($line, '#'))` should be performed --- the original Markdown implementation doesn't seem to care about the heading level when removing trailing hashes.

**Comment by erusev** [comment]
Thanks! The first is supposed to work like this. This is is dictated by the CommonMark spec. The second and the third, however, aren't. I'll see what i can do.

**Comment by bkuhl** [comment]
https://github.com/erusev/parsedown/issues/337 is also a PR related to streamlining headers and if both are implemented, would be paired well with a new release.
