### ISSUE TITLE
Option or extensibility to parse blocks into <p> tags instead of using <br /> tag

### ISSUE THREAD

**Issue by jaw-sh** [erusev/parsedown#339]
Is there any way to achieve this:

Original

```
>the quick brown fox
>jumps over the
>lazy dog
```

Rendering

> the quick brown fox
> jumps over the
> lazy dog

HTML

```
<blockquote>
<p>the quick brown fox<br>
jumps over the<br>
lazy dog</p>
</blockquote>
```

Desired HTML

```
<blockquote>
<p>the quick brown fox</p>
<p>jumps over the</p>
<p>lazy dog</p>
</blockquote>
```

Alternative desired HTML

```
<blockquote>
<p><span>the quick brown fox</span><br />
<span>jumps over the</span><br />
<span>lazy dog</span></p>
</blockquote>
```

I desire that the greater than signs that produce the blockquote remain in the rendered HTML. I'd like to do this with CSS pseudo-elements and the `content: '>';` definition, if possible.

**Comment by kminchev** [comment]
To me, what you want doesn't make sense unless you add empty lines in between.

**Comment by erusev** [comment]
have a look at the `setBreaksEnabled` option

**Comment by jaw-sh** [comment]
@kminchev @erusev The goal of this is to mix HTML and classic, email-style quote blocks. This is for a mixture of stylizing CSS things (color) and having a traditional output that my users will be familiar with.

The application I'm working on is a 4chan-style imageboard. If you're unfamiliar with 4chan, you've definitely seen "greentext stories". These are essentially quote blocks that retain the greater-than sign while also being stylized via CSS.

I took a hatchet to the code to get this working and this is what I've come up with. I'd like to share it for review in case anyone familiar with the project has any input.

My input:
```
1
2 3
>4 5 6
>>7 8 9
>>>10 11 12
```

This is what the output is:
![](http://i.imgur.com/jKfo9mq.png)

And this is the output HTML.
```
<p>1<br>
2 3</p>
<blockquote>
<p>&gt;4 5 6<br>
&gt;&gt;7 8 9<br>
&gt;&gt;&gt;10 11 12</p>
</blockquote>
```

This is _pretty good_. I'd prefer it if it retained nesting, but it's the best I could do.

This is my hacked code of Parsedown.

```
    protected function blockQuote($Line)
    {
        if (preg_match('/^>[ ]?(.*)/', $Line['text'], $matches))
        {
            $Block = array(
                'element' => array(
                    'name' => 'blockquote',
                    'handler' => 'lines',
                    'text' => (array) ("&gt;" . $matches[1]),
                ),
            );

            return $Block;
        }
    }

    protected function blockQuoteContinue($Line, array $Block)
    {
        if ($Line['text'][0] === '>' and preg_match('/^>[ ]?(.*)/', $Line['text'], $matches))
        {
            if (isset($Block['interrupted']))
            {
                $Block['element']['text'] []= '';

                unset($Block['interrupted']);
            }

            $Block['element']['text'] []= "&gt;" . $matches[1];

            return $Block;
        }

        if ( ! isset($Block['interrupted']))
        {
            $Block['element']['text'] []= "&gt;" . $Line['text'];

            return $Block;
        }
    }
```

As you can see, I just clumsily stuck in a `&gt;` prefix before each line. This replaces the first `>` character and the Parsedown code converts the rest to entities.

This is a _pretty shitty hack_, but it works, and I desperately need this to work as I've described. It's better to have it like this for me than it is to have blockquotes. Those stupid arrows absolutely need to exist. If I can have proper HTML blocking too, all the better.

**Comment by erusev** [comment]
I'll have more time next week. Hopefully, I'll be able to help.

p.s. Your extension looks pretty good.

**Comment by jaw-sh** [comment]
@erusev That's because you wrote 99% of it, probably. I just added "&gt;" in front of the text concatenations and put the methods almost verbatim into a class that inherits Parsedown.

**Comment by aidantwoods** [comment]
As already seen, this custom behaviour is relatively easily achieved with an extension :)
