### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'inc/lib/parsedown/Parsedown.php'

### ISSUE THREAD

**Issue by xXxBobDolexXx** [erusev/parsedown#343]
I'm a little new at this type of thing, I keep seeing this error in my server error.log

Fatal error: require_once(): Failed opening required 'inc/lib/parsedown/Parsedown.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/infinity/inc/functions.php on line 25

I used composer to install, but I'm new to both composer and parsedown and can't quite tell what the issue is.

**Comment by cebe** [comment]
you are trying to include a file that does not exist. if you are using composer, you should just include the composer autoloader, there should be no need to include parsedown class file.

**Comment by xXxBobDolexXx** [comment]
The file did exist though. I ended up figuring it out to some degree. I moved all the files from the parsedown install directory to the location the error was pointing to, not just Parsedown.php.

That seems to have resolved it, or rather I have stopped getting these errors at least.
