### ISSUE TITLE
Parsedown doesn't recognize markdown inside of custom inline elements

### ISSUE THREAD

**Issue by Flibio** [erusev/parsedown#347]
Is their a way to make Parsedown recognize other formatting(such as **bold**) inside of custom inline elements?

Example:

I have a custom inline element, `{m} {/m}`, but when I but any other markdown inside Parsedown doesn't recognize it. Is there a way to make Parsedown recognize markdown inside of custom inline elements?

**Comment by erusev** [comment]
Yes, the element needs to have a `'handler' => 'line'` - this will make the parsers call the `line` method on its text.

**Comment by Flibio** [comment]
Thanks, it works perfectly now!
