### ISSUE TITLE
Inline markup to block in extension

### ISSUE THREAD

**Issue by lazlo-bonin** [erusev/parsedown#348]
I'm trying to make some inline markup become a block (I believe that's the right terminology) for pull quotes.

For example, my input:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque rhoncus odio, accumsan bibendum nunc interdum quis. $$ Fusce quis ullamcorper diam, sit amet luctus libero. $$ Maecenas in felis sagittis, rhoncus nunc ut, molestie tortor. Vivamus mollis libero non facilisis mollis. 
> 
> Pellentesque condimentum pellentesque mi ac venenatis. Nullam ornare a nisi eu molestie. Vivamus eleifend, risus sed consectetur ultricies, orci elit iaculis mauris, pulvinar pellentesque elit eros ullamcorper neque. Aliquam erat volutpat.

(Notice the $$s in the first paragraph)

And the desired HTML output:

```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque rhoncus odio, accumsan bibendum nunc interdum quis. Fusce quis ullamcorper diam, sit amet luctus libero. Maecenas in felis sagittis, rhoncus nunc ut, molestie tortor. Vivamus mollis libero non facilisis mollis. </p>

<div class="pullquote">Fusce quis ullamcorper diam, sit amet luctus libero.</div>

<p>Pellentesque condimentum pellentesque mi ac venenatis. Nullam ornare a nisi eu molestie. Vivamus eleifend, risus sed consectetur ultricies, orci elit iaculis mauris, pulvinar pellentesque elit eros ullamcorper neque. Aliquam erat volutpat.</p>
```

Basically, I want to detect an inline element and append its content in a block.

Is this possible? If so, how?

**Comment by erusev** [comment]
this seems like it'd be hard to implement

parsedown is based on the fact that in markdown, block-level elements can be identified based on the first characters of their lines

the element that you describe is not consistent with this fact

**Comment by aidantwoods** [comment]
I'm not sure I see why this needs to be a block? I think you can achieve the output you're looking for with just an inline.
