### ISSUE TITLE
Double empty line (\n\n) to give you larger empty space? 

### ISSUE THREAD

**Issue by ataiya** [erusev/parsedown#349]
Hi guys, I am wondering why you don't have what is described [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lines)

I use markdown to generate HTML automatically, but often I need to insert a raw 
     
    </br>

 
Note I've already enabled this the \n extension (why wasn't it on by default!?):

     $Parsedown->setBreaksEnabled(true); // \n becomes <br>

Thanks!

**Comment by erusev** [comment]
could u provide expected vs actual output, thanks

**Comment by ataiya** [comment]
Ok, nvm. I think I misunderstood something.
Still crazy that in markdown there is not an equivalent of latex's \vspace{...}
