### ISSUE TITLE
it support Latex?

### ISSUE THREAD

**Issue by jockchou** [erusev/parsedown#350]
when i write Latex like this:

$log_2 n$$log_2 n$

it's parsed to:

$log<em>2 n$$log</em>2 n$

ok, no, my god!!!!

**Comment by GrahamCampbell** [comment]
Latex is not supported.

**Comment by cebe** [comment]
what do you expect the output to be instead? are you writing abou LaTeX or do you want the output to be LaTeX instead of HTML?

**Comment by jockchou** [comment]
$log_2 n$$log_2 n$

I must use "$log\_2 n$$log\_2 n$"

cant it don't parse to <em> tag where in LaTeX like "$.....$"

**Comment by hkdobrev** [comment]
@jockchou This sounds like a duplicate of #107.

**Comment by jockchou** [comment]
AND it supported [TOC]
