### ISSUE TITLE
Different type of reference link?

### ISSUE THREAD

**Issue by STrRedWolf** [erusev/parsedown#351]
I know of `[url links](http://markdown.org)` and `[in-page references][top]` but is there a way to extend that, so I can translate `[a text reference like]{MediaWiki}` into a linked URL (a la `http://example.com/wiki/index.php?q=MediaWiki`)?  I didn't see any good way of doing that with ParseDown.

**Comment by erusev** [comment]
Check out the wiki for a tutorial on extensibility.

**Comment by STrRedWolf** [comment]
I've looked at the tutorial, and it looks like I have to override the starting `[` which is rather heavy-handed.  I'm looking to keep the original meaning, and just add `[]{}` for the wiki purposes.

**Comment by erusev** [comment]
No need to override anything - just add another inline type.
