### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by smsteel** [erusev/parsedown#353]
You're suggesting using this to make an extensions:

    class Extension extends Parsedown
    {
        protected function blockHeader($Line)
        {
            return;
        }

        protected function blockSetextHeader($Line)
        {
            return;
        }
    }

And this to use your library:

    Extension ::instance()->parse($text);

This will not work due to `$instance = new self();`:

    static function instance($name = 'default')
    {
        if (isset(self::$instances[$name]))
        {
            return self::$instances[$name];
        }

        $instance = new self();

        self::$instances[$name] = $instance;

        return $instance;
    }

Must be `$instance = new static();`

**Comment by hkdobrev** [comment]
See #336, it was merged, but not yet tagged.

**Comment by smsteel** [comment]
Oh, okay.
