### ISSUE TITLE
Composer package auto loading working?

### ISSUE THREAD

**Issue by codemagician** [erusev/parsedown#354]
I ran `composer require erusev/parsedown`

Then made a file as per the README

    <?php
        $parsedown = new Parsedown();

I always get the error message:

    PHP Fatal error:  Class 'Parsedown' not found in

Do I need to use some namesapce to get this class to load, or is there a problem with the composer packaging?

**Comment by hkdobrev** [comment]
@codemagician You need to require `vendor/autoload.php` which registers the Composer autoloader.

**Comment by codemagician** [comment]
@hkdobrev I have this already

**Comment by codemagician** [comment]
@hkdobrev Overlooked this. Thanks
