### ISSUE TITLE
BAG if we have html comment right after html close tag

### ISSUE THREAD

**Issue by doiftrue** [erusev/parsedown#366]
Found such bug. Here is a screen where you can see it: http://c2n.me/3qjDTYh

here is the text for parse, in order you test it yourself:

```
foo ``text``
## title11
foo text

## title22
foo ``text``

<ul>
    <li>22222222222222
        <ul>
            <li>1111111111</li>
        </ul><!-- second ul -->
    </li>
</ul>

### title33

And hire, any **markdown** text is no `work`!!!
```

It's because of `<!-- second ul -->` comment after `</ul>`. I was looking for it for several hours and finally found :)

**Comment by aidantwoods** [comment]
This should be fixed in the next release :)

**Comment by aidantwoods** [comment]
<img width="837" alt="screen shot 2018-03-28 at 00 20 32" src="https://user-images.githubusercontent.com/3288888/38000098-da6c061a-321d-11e8-81a2-51a55d045a96.png">
