### ISSUE TITLE
MathJax?

### ISSUE THREAD

**Issue by sbrl** [erusev/parsedown#369]
Does parsedown support Math equations?

In [stackedit.io](//stackedit.io), I can include math equations like this:

```markdown
Here is a math equation that includes $x$:

$$
y=3x^2+4x+5
$$
```

Does parsedown support something similar? If not, how would I go about extending parsedown to include this?

**Comment by kminchev** [comment]
No. That's not part of the original specification. You could request this functionality in Parsedown Extra.

**Comment by sbrl** [comment]
@kminchev Right. I'll copy this issue over there and close this one then. Thanks for the advice!

**Comment by sbrl** [comment]
Update: I've posted parsedown-extra#81 requesting this feature.
