### ISSUE TITLE
Not working (when placed within div)

### ISSUE THREAD

**Issue by prnvrna** [erusev/parsedown#376]
![shouldn t this one work](https://cloud.githubusercontent.com/assets/1384615/12074610/15177de4-b183-11e5-9dfe-9efcec0b9e8f.png)

**Comment by erusev** [comment]
hi, can u be a bit more specific and provide: input, expected output and actual output

thanks

**Comment by SignpostMarv** [comment]
Presumably they're expecting:
```markdown
<div>**test**</div>
**test**
```
to come out as
```html
<div><strong>test</strong></div>
<p><strong>test</strong></p>
```

instead of
```html
<div>**test**</div>
<p><strong>test</strong></p>
```

**Comment by erusev** [comment]
this would be in conflict with the specification

**Comment by SignpostMarv** [comment]
close as won't fix?

**Comment by erusev** [comment]
i'd wait to see if @prnvrna wants to comment

**Comment by angelov-todor** [comment]
I also have this problem.
This is the example actually ( I am not sure those specs you refer to ):
http://spec.commonmark.org/0.23/#example-108 & http://spec.commonmark.org/0.23/#example-123

http://spec.commonmark.org/dingus/?text=

`<div>

markdown
* test1
* test2

</div>

`
This parses the markdown inside the div.

**Comment by djbusby** [comment]
+1 ; In my case I was trying this:

    <div style="flex: 1 1 auto;">
    
    ![Factory Reset](/img/hardware/socket-reset.png "Factory Reset")
    
    </div>

The images were not being processed; from example 108 it seems this markdown should be

**Comment by choregus** [comment]
I found a solution to this by accident!!! 👍 

I just added a trailing forward slash to the opening div tag and it worked. I had been trying everything.

Here is an example of the code i have used successfully:

    <div style="-webkit-column-width: 400px;-moz-column-width: 400px;column-width: 400px;"/>
    ##  title
    blah blah blah
    </div>


note the trailing slash at the end of the opening div tag. All the content then rendered correctly, no matter how complicated i made it.

This fixes example 108 for me.

**Comment by PhrozenByte** [comment]
Parsedown isn't fully compatible to CommonMark (yet), see `README.md` for details. Parsedown (still) mostly focuses on the original Markdown specification, in which this is invalid. Please note that the original Markdown reference parser never met its own specs, that's the reason why CommonMark exists. However, you can achieve this by using [Parsedown Extra](https://github.com/erusev/parsedown-extra):
```html
<div markdown="1">

**test**

</div>
**test**
```
Outputs as of [Parsedown Extra's demo](http://parsedown.org/extra/):
```html
<div>
<p><strong>test</strong></p>
</div>
<p><strong>test</strong></p>
```
