### ISSUE TITLE
Invalid HTML output

### ISSUE THREAD

**Issue by francisbesset** [erusev/parsedown#384]
Hello,
I used this library on my open source projet [Gitiki](https://github.com/gitiki/Gitiki).

An user reported an issue (https://github.com/gitiki/Gitiki/issues/7) and after investigating, the problem is in your parsedown library.

This markdown code generate an invalid HTML:
```
[http://gitiki.org](http://gitiki.org)
```

Actual output:
```
<a href="http://gitiki.org"><a href="http://gitiki.org">http://gitiki.org</a></a>
```

Expected output:
```
<a href="http://gitiki.org">http://gitiki.org</a>
```

**Comment by cebe** [comment]
duplicate of #358

**Comment by francisbesset** [comment]
Oh sorry. I close this issue.
