### ISSUE TITLE
Custom Configurations

### ISSUE THREAD

**Issue by tovic** [erusev/parsedown#385]
Hi,

Do you have any plans to add some custom configuration parameter in **Parsedown( Extra)?**?

Because there are some things that can be customized:

 - Optional to add dot prefix in fenced code block class name
 - Optional to put class name in `<pre>` element
 - Optional to ommit the `language-` prefix in code block class name
 - Optional to use class name instead of inline style for table alignment
 - Optional to set custom classes in footnotes
 - Optional to create custom footnotes hash pattern
 - Predefined URL, titles and abbreviations?

Thanks.

**Comment by kminchev** [comment]
This issue belongs to Extra repository.

**Comment by tovic** [comment]
https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions#change-element-markup

**Comment by tovic** [comment]
Endeded up with my own Extension for **Parsedown Extra**: https://github.com/tovic/parsedown-extra-plugin
