### ISSUE TITLE
Support for inline images

### ISSUE THREAD

**Issue by Yirg** [erusev/parsedown#390]
I'd like to be able to write illustrated guides with inline images, but it seems Parsedown always pushes images to the bottom of the post. Is there a way to embed images inline, and if not, may I suggest it as an enhancement?

Thank you!

**Comment by cebe** [comment]
All images should be inline by default. Can you show your markdown and the parsed output HTML?

**Comment by Yirg** [comment]
See for example the text in [this](http://www.steamgifts.com/giveaway/ZwVfI/heroes-legends-conquerors-of-kolhar) giveaway description on steamgifts.com.

Both images appear after both paragraphs, but the second paragraph is actually after the first image. This is the code:

```
Paragraph #1

![Image #1](http://cdn.akamai.steamstatic.com/steam/apps/318570/header_292x136.jpg)

Paragraph #2

![Image #2](http://cdn.akamai.steamstatic.com/steam/apps/306950/header_292x136.jpg)
```

And this is the resulting order:

> Paragraph #1
> Paragraph #2
> View attached image.
> View attached image.

**Comment by cebe** [comment]
This is not a problem with parsedown but with the site you are using. The above markdown renders as expected on  http://parsedown.org/demo :

```html
<p>Paragraph #1</p>
<p><img src="http://cdn.akamai.steamstatic.com/steam/apps/318570/header_292x136.jpg" alt="Image #1" /></p>
<p>Paragraph #2</p>
<p><img src="http://cdn.akamai.steamstatic.com/steam/apps/306950/header_292x136.jpg" alt="Image #2" /></p>
```

**Comment by Yirg** [comment]
Thank you for helping, cebe. I'll discuss this with the site admin.

Have a great weekend!
