### ISSUE TITLE
PHP 5.2 Error

### ISSUE THREAD

**Issue by robi09** [erusev/parsedown#394]
Hi guys, i'm using your library on our project and i get this issue in PHP 5.2.

Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in ./core/libs/Parsedown.php on line 1489

**Comment by cebe** [comment]
PHP 5.2 is no longer supported: see #286, #297, https://github.com/erusev/parsedown/commit/5f40cab3e796235a3bf6dfd2bddd451ca1019860

**Comment by cebe** [comment]
Also: http://php.net/supported-versions.php

**Comment by hkdobrev** [comment]
Yes, support for PHP 5.2 was removed since Parsedown version 1.6.0. You could use an earlier version if you must use such old PHP version, but I urge to update your servers.

PHP 5.2 was released almost 10 years ago and declared EOL (end of life) 5 years ago.

**Comment by hkdobrev** [comment]
I think we can safely close this one.
