### ISSUE TITLE
Multi-line link not detected

### ISSUE THREAD

**Issue by cweiske** [erusev/parsedown#399]
A link that is split onto two lines is not detected:

```
[foo]
(http://example.org/)
```

GitLab renders this fine.

Use case for this readability when e.g. the "foo" text is an image, and the link also has a title:

```
[![Youtube-Screenshot-Link](path/to/uploads/09be07d94465827fdeba9b232fd30500/Bildschirmfoto_2015-12-09_um_09.50.49.png)]
(https://youtu.be/hzZO7sKkDZc "DECT IP How To Transfer (en)")
```

**Comment by svivian** [comment]
That is expected behaviour as per the CommonMark spec (see [test here](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D%0A(http%3A%2F%2Fexample.org%2F))). There cannot be any space between `]` and `(`.
