### ISSUE TITLE
Code breaks parsing

### ISSUE THREAD

**Issue by veselfil** [erusev/parsedown#405]
I have encountered this issue today, where the parser breaks bellow code. I think this image will illustrate the issue well.

http://imgur.com/OfVL3kO

**Comment by finwo** [comment]
From what I'm seeing in the image, you're not placing your html tags in the correct order.
When you're opening a new tag within an other tag, you'll need to close the last-opened tag first.

Your code:
```
<pre><code>
...
</pre></code>
```

Proposed code:
```
<pre><code>
...
</code></pre>
```

**Comment by ArkayCZ** [comment]
Yes, I know I swapped the order of the tags, but considering it works in the other parser (+ web services like Dillinger.io, editors like MarkPad) I think that it should work in this parser too.

**Comment by erusev** [comment]
@ArkayCZ Can u please provide the text in question? Tnx

**Comment by funtaps** [comment]
```
<pre><code>
</pre></code>

Title
---------------
```

**Comment by aidantwoods** [comment]
This will work as expected in the next release :)
