### ISSUE TITLE
Parser includes next html element inside <p></p>

### ISSUE THREAD

**Issue by alanaasmaa** [erusev/parsedown#408]
My blade.php
`{!! str_limit($article->body_html, $limit = 200, $end = '...') !!} <a href="{{url('article/'.$article->slug)}}">Read More</a>`

I'm using laravel. I tryed to use andreasindal/laravel-markdown

I tryed without str_limit.. what i am doing wrong or is this a feature ? If it's a feature how could i use it ?

I can fix it by adding a href into div.

**Comment by alanaasmaa** [comment]
Okei i got it working by adding </p> to the end. 
`{!! str_limit($article->body_html, $limit = 200, $end = '...') !!}</p>
            <a class="readmore" href="{{url('article/'.$article->slug)}}">Read More</a>`

It seems like a feature ? :dancer:

**Comment by tovic** [comment]
Markdown parser should be executed after string cut. Your solution will break if the snippet cropped until `<pre><code>foo bar baz`

**Comment by alanaasmaa** [comment]
@tovic Hello, im pretty new to php what do you mean by string cut ?

**Comment by tovic** [comment]
@alanaasmaa It is about the `str_limit()` function.

~~~ .php
$raw_body_data = <<<EOL
foo

bar

baz
EOL;

$parser = new Parsedown;
echo $parser->text(str_limit($raw_body_data, 100, '...')); // good (parse after string limit: you are cropping a plain text)
echo str_limit($parser->text($raw_body_data), 100, '...'); // bad (string limit after parse: you are cropping a HTML text)

**Comment by alanaasmaa** [comment]
@tovic Thanks. Got it working now :) 

I close the ticket.
