### ISSUE TITLE
How can I make it so pressing enter once creates a new paragraph?

### ISSUE THREAD

**Issue by EthanHannah** [erusev/parsedown#410]
Right now if I type these 2 lines

this is a paragraph
this is a different paragraph

it returns 

`<p>this is a paragraph<br>this is a different paragraph</p>`

How can I make it so it outputs:

`<p>this is a paragraph</p><p>this is a different paragraph</p>`

Without having to press the enter button twice?

**Comment by kminchev** [comment]
No idea why this got closed, but you have two options:

* https://github.com/erusev/parsedown/wiki/Tutorial:-Get-Started (4th paragraph)
* https://github.com/erusev/parsedown/blob/master/Parsedown.php#L58 (rewrite that as `protected $breaksEnabled = true;`
