### ISSUE TITLE
remove markdown

### ISSUE THREAD

**Issue by basith374** [erusev/parsedown#413]
can we get this feature? i want parsedown to remove markdown & convert to plain text

**Comment by Exagone313** [comment]
The Parsedown code is easy to read and extendable (see the wiki), just do your own extension for that kind of features.

**Comment by 7php** [comment]
@basith374 you probably need something similar, but in PHP. You reuse the logic in there though and implement it in PHP.

I agree with @Exagone313 that you could just implement this logic as an extension for your use-case and probably sharing it with the parsedown community as well.

**Comment by kjdion84** [comment]
Using PHP:

	function remove_markdown($value)
	{
		$parsedown = new Parsedown();
		$html = $parsedown->text($value);

		return strip_tags($html);
	}

**Comment by aidantwoods** [comment]
Interestingly once #576 is ready, as an extension it will be possible to traverse the AST after markdown parsing is finished and pick out only text, or even other relevant bits of data too (e.g. if you wanted to include image descriptions, say). This should be relatively easy to implement once the AST is available.
