### ISSUE TITLE
it can not parse "==" to hightlight?

### ISSUE THREAD

**Issue by iamMarkchu** [erusev/parsedown#414]
i use this class in my project, but it can parse "==". is there anyone who can tell me why?

**Comment by cebe** [comment]
what do you mean with "it can not parse "==" to hightlight"? what do you want to highlight?

**Comment by iamMarkchu** [comment]
i use a markdown editor named [YouDao Note](http://note.youdao.com/), i can parse "==hello world" to ![helloworld](https://cloud.githubusercontent.com/assets/14805449/17471493/382ac2d2-5d77-11e6-9f94-e4520d0f79cc.png)..
anyway, can you tell me , if i want to highlight something , what should i do?

**Comment by erusev** [comment]
You need to write an extension - go to the [wiki](https://github.com/erusev/parsedown/wiki) to see how

**Comment by iamMarkchu** [comment]
thx,  i would have a try !
