### ISSUE TITLE
Formatting already sanitized inputs

### ISSUE THREAD

**Issue by whimsicaldreamer** [erusev/parsedown#420]
Well I am using this lib in my chat app and the problem I am facing is formatting sanitized inputs.

For ex: If the user sends **> text** it doesn't change to blockquote but shows up as **> text** where **>** is the html entity code in the html inspector and also in the db. 

Is there any way it could be done to get it to work as expected?

**Comment by cebe** [comment]
Why does `> text ` not convert to a blockquote for you? is should if you use the library correctly.

**Comment by whimsicaldreamer** [comment]
@cebe, its because when I save the data to db I use **htmlspecialchars** to sanitize the input, and then upon fetching it and parsing them with the lib doesn't work as the lib skips **&lt;**. So what can be done?

**Comment by tovic** [comment]
~~~ .php
$parser->text(htmlspecialchars_decode($content));
~~~

**Comment by cebe** [comment]
sanitizing input should be done on output, not when saving to the database.

**Comment by whimsicaldreamer** [comment]
But shouldn't data be saved into database only after sanitization?

**Comment by cebe** [comment]
no, the way of sanitization depends on the output medium, see e.g. http://stackoverflow.com/a/2326629/1106908

**Comment by whimsicaldreamer** [comment]
Okay. Thanks. Just a bit more to ask, what to do if I want to add a css class to some of the elements? Like for ex the inline image element?

**Comment by tovic** [comment]
The original [Parsedown Extra](https://github.com/erusev/parsedown-extra) extension has the ability to add custom classes with braces. [My extension](https://github.com/tovic/parsedown-extra-plugin#advance-attribute-parser) also has support for adding custom attributes with normal HTML syntax.

**Comment by whimsicaldreamer** [comment]
@tovic Parsedown Extra doesnt support predefined classes whereas your one does? Am I right?

**Comment by whimsicaldreamer** [comment]
@tovic and according to your reply about `$parser->text(htmlspecialchars_decode($content));`, won't it decode something like `&lt;script&gt;alert('xss'); &lt;/script&gt;` to `<script>alert('xss');</script>` and cause trouble?

**Comment by tovic** [comment]
@whimsicaldreamer Unfortunately yes :(

**Comment by tovic** [comment]
@whimsicaldreamer The `$parser->images_attr` option allows you to set predefined attributes like this:

~~~ .php
$parser->images_attr = array(
    'style' => 'width: 100%;'
);
~~~

**Comment by cebe** [comment]
> @tovic and according to your reply about $parser->text(htmlspecialchars_decode($content));, won't it decode something like &lt;script&gt;alert('xss'); &lt;/script&gt; to <script>alert('xss');</script> and cause trouble?

see also #418

**Comment by whimsicaldreamer** [comment]
@cebe, htmlPurifier is slow. I read somewhere.

**Comment by whimsicaldreamer** [comment]
@tovic, I was looking for adding a class attribute directly instead of styles. Plus a documentation about this feature (may be I have missed) would be beneficial.

**Comment by tovic** [comment]
~~~ .php
$parser->images_attr = array(
    'class' => 'foo-bar'
);
~~~

:\

**Comment by whimsicaldreamer** [comment]
@tovic , thanks. And as I will be using `setMarkupEscaped(true)` so I would need to create an instance of the main Parsedown class. Right?

```
$Parsedown = new Parsedown();
$Parsedown->setBreaksEnabled(true);

$parser = new ParsedownExtraPlugin;
$parser->images_attr = array(
    'class' => 'foo-bar'
);
echo $parser->text($content);
```

**Comment by whimsicaldreamer** [comment]
@tovic whenever I send a link like `[simple link](https://www.google.com)` I get an error in my log file as 

> Notice:  Undefined index: HTTP_HOST in C:\wamp\www\php-js-chat_myEdition\vendor\erusev\parsedown\ParsedownExtraPlugin.php on line 96

**Comment by tovic** [comment]
http://stackoverflow.com/a/13352023/1163000

**Comment by whimsicaldreamer** [comment]
@tovic I understand the fact that it is not set. So first thing, how to set it? And secondly why is the difference that the same format gets parsed when using the basic lib but on extending the lib with the extension it breaks?

**Comment by tovic** [comment]
My extension has some URL checking process to decide whether it is an external or internal URL (that is one of the extension feature). Normally, the `HTTP_HOST` should return `localhost` in your environment. Other than that, I have no idea.

I think we should focus on the original topic (the title) or just create a new thread.
