### ISSUE TITLE
Using sethtmlescaped function prevents emojis to form

### ISSUE THREAD

**Issue by whimsicaldreamer** [erusev/parsedown#421]
I am using EmojiOne lib for generating emojis but as `sethtmlescaped()` escapes all html, the img tags with the emojis are not formed. Is there any workaround for it?

**Comment by tovic** [comment]
Run **EmojiOne** parser after markdown parsing.

**Comment by whimsicaldreamer** [comment]
Ok, and does `sethtmlescaped()` not allow manual `<br>` tag to be entered?

**Comment by whimsicaldreamer** [comment]
@erusev can we prevent the above from happening?

**Comment by erusev** [comment]
Hm, can you generate the emojis after the file has been parsed with Parsedown?

**Comment by whimsicaldreamer** [comment]
Yes. Definitely I can generate emojis(both ascii like :) :( and shortnanes like :smile: :disappointed: only using the emoji parser or if I use parsedown parser(without sethtmlescaped()) with emoji parser

**Comment by whimsicaldreamer** [comment]
Using this `$this->parseEmojiToImage($this->markdownHTML($threadToSave));` only shortnames are converted to emojis but ASCII codes are not.
But in the reverse order if it is done, the whole html gets displayed as output.

**Comment by whimsicaldreamer** [comment]
@erusev what do you think about it?

**Comment by aidantwoods** [comment]
Parsedown shouldn't be escaping colons in any mode, was that the issue here?

**Comment by whimsicaldreamer** [comment]
Probably yes.
