### ISSUE TITLE
Embed video

### ISSUE THREAD

**Issue by blakeaholics** [erusev/parsedown#422]
In an attempt to allow users to embed YouTube videos I added my own code to differentiate between an image (`![title](image link)`) and a video (`!![title](video link)`) **which successfully inserts a video into the page but also causes Parsedown to cease functioning.**

I inserted these lines into inlineImage, just below the "is this an image" check (`if ( ! isset($Excerpt['text'][1]) or $Excerpt['text'][1] !== '[')`) below:

```
if (substr($Excerpt['text'], 0, 2 ) === "!!") {
    $t = $this->inlineVideo($Excerpt);

    if ($t === null)
    {
        return;
    } else {
         return $t;
    }
}
```

around line 1190

And here is inlineVideo:

```
protected function inlineVideo($Excerpt)
    {
        $Excerpt['text']= substr($Excerpt['text'], 2);

        $Element = array(
            'name' => 'object',
            'text' => null,
            'attributes' => array(
                'data' => null,
            ),
        );

        $extent = 0;

        $remainder = $Excerpt['text'];

        if (preg_match('/\[((?:[^][]|(?R))*)\]/', $remainder, $matches))
        {
            $Element['text'] = $matches[1];

            $extent += strlen($matches[0]);

            $remainder = substr($remainder, $extent);
        }

        if (preg_match('/^[(]((?:[^ ()]|[(][^ )]+[)])+)(?:[ ]+("[^"]*"|\'[^\']*\'))?(?:[ ]+("[^"]*"|\'[^\']*\'))?[)]/', $remainder, $matches))
        {
            $Element['attributes']['src'] = $matches[1];
            //echo "<br> SRC : " . $Element['attributes']['src'] ." <br><br><hr>";
            $extent += strlen($matches[0]);       
        }

        $Inline = array(
            'extent' => $extent + 1,
            'element' => array(
                'name' => 'object',
                'attributes' => array(
                    'data' => str_replace("http:", "https:", str_replace("watch?v=", "embed/", $Element['attributes']['src'])),
                ),
            ),
        );

        return $Inline;
    }
```

I'm fairly new to PHP but have managed to successfully modify Parsedown to detect valid Twitter @user and resize an image according to user so far.
I just feel I'm missing something obvious here.

I'm sure this isn't exactly the correct place to ask this but oh well.

**Comment by kminchev** [comment]
I think this should be in Extra repo.

**Comment by hkdobrev** [comment]
I think this is just about resolving a problem when writing an extension.

Just to highlight the problem from the OP:
> which successfully inserts a video into the page but **also causes Parsedown to cease functioning**.

**Comment by blakeaholics** [comment]
@hkdobrev is correct, the issue here is it ceases to function.
Does anyone have any ideas?

**Comment by aidantwoods** [comment]
@blakeaholics are you still having trouble?

**Comment by jh62** [comment]
use an embed like this: https://stackoverflow.com/questions/18726480/embed-html5-youtube-video-without-iframe
