### ISSUE TITLE
image tag fails to render when surrounded by <center></center>

### ISSUE THREAD

**Issue by csharpgh** [erusev/parsedown#428]
if you surround a image reference such as ![Image](http://github/image.jpg) with <center></center> it fails to convert the tag into an html reference to the image file.

**Comment by kminchev** [comment]
<center> is deprecated.

**Comment by otaka-san** [comment]
@kminchev this may be true, however, img will always fail to render when wrapped into a block element. So, also if you wrap an img in a figure tag, it won't be rendered.

Another rendering parser ([Text::Markdown](http://search.cpan.org/~bobtfish/Text-Markdown-1.000031/lib/Text/Markdown.pm)) works similarly and argues:

> Markdown is not interpreted in HTML block-level elements, in order for chunks of pasted HTML (e.g. JavaScript widgets, web counters) to not be magically (mis)interpreted. 

But, they allow for a work-around: 

> For selective processing of Markdown in some, but not other, HTML block elements, add a markdown attribute to the block element and set its value to 1, on or yes.

Maybe such a thing could be implemented in parsedown as well?

**Comment by cebe** [comment]
@otaka-san there is https://github.com/erusev/parsedown-extra for that.

**Comment by otaka-san** [comment]
@cebe Oh, great! I should have checked that before obviously … thanks! Didn't know.

**Comment by aidantwoods** [comment]
HTML will prevent markdown processing if it is included on the same line and the line starts with HTML (per CommonMark spec)
