### ISSUE TITLE
The state of the master branch?

### ISSUE THREAD

**Issue by CriseX** [erusev/parsedown#438]
I have used Parsedown for a while, I can't help but to notice that while development is active there hasn't been a release in a year.

What is the current state of the development branch in regards to using it in a production environment.

**Comment by erusev** [comment]
The project is very much alive - I've been busy with other things, but I have very realistic plans for future improvements and releases.

**Comment by aidantwoods** [comment]
There have been a couple new releases recently, and one around the corner too :)
