### ISSUE TITLE
Escape Not Working

### ISSUE THREAD

**Issue by Mazux** [erusev/parsedown#442]
setMarkUpEscaped is not working.

Example of code
`$parsedown = new Parsedown(); $parsedown->setMarkupEscaped(true)->text($PostMBody);`

PostMBody is just a textarea, formatted like so:
`$PostMBody = $db->real_escape_string(strip_tags(stripslashes($_POST["PostBody"]))); // Body of the post
`

The page just goes blank and responds with a 500 error.

I'm including Parsedown like so (latest version)
`include $_SERVER["DOCUMENT_ROOT"]."/_INCLUDES/MarkdownParser/markdown.php"; // Parser for markdown to DB` (the latest Parsedown.php file) - the same error happens when I try the break line function.

What am I doing wrong?!

**Comment by 7php** [comment]
Hey you are using the Parsedown class and is including MarkdownParser? :)
I think you got the wrong library there and hence your server is not finding that class and faulting...
(cross-check please)

can you do:

1) `print_r($_SERVER["DOCUMENT_ROOT"]."/_INCLUDES/MarkdownParser/markdown.php");`
and make sure the file is indeed found at the printed path?

2) Can you confirm that you get the 500 error when `$parsedown->setMarkupEscaped()` is call and not even before that?

Out of curiosity, **why are you** including the file and not using composer autoloader?

**Comment by aidantwoods** [comment]
Is this issue still occurring @Mazux?
