### ISSUE TITLE
Parsedown never generates <br> break tags / empty lines

### ISSUE THREAD

**Issue by vivaladav** [erusev/parsedown#448]
Hi,

I tried to generate empty lines both in your demo and in a test page on my server with the same result. Parsedown never generates `<BR>` tags.

I tried to follow the markdown syntax which says:

> When you do want to insert a break tag using Markdown, you end a line with two or more spaces, then type return.

but it seems Parsedown just ignores the spaces at the end of a line.

For example testing this [text](http://pastebin.com/raw/WQm9FASP) I get this [parsed output](http://pastebin.com/raw/JEScE52Z) in your demo whereas I would expect at least a break tag between the second and the third lines.

**Comment by cebe** [comment]
Whitespace before and after a paragraph is ignored. But inside of a paragraph you can add a `<br>`:

```markdown
## par 1
This is a line.  
And this is after the break.
```

parsed as 

```html
<h2>par 1</h2>
<p>This is a line.<br />
And this is after the break.</p>
```

by the parsedown demo.

**Comment by vivaladav** [comment]
Yes I know, but that's not what I am looking for.

Basically I want to generate an empty line and it seems there's no way to get that with Parsedown.

**Comment by cebe** [comment]
well, you can just insert a `<br />` in markdown itself:

```markdown
this is a line<br />
```

will result in:

```html
<p>this is a line<br /></p>
```

**Comment by tovic** [comment]
Try:

~~~ .markdown
Foo.

&nbsp;

&nbsp;

Bar.
~~~

**Comment by vivaladav** [comment]
@cebe yes, that's a possible workaround, but it doesn't work when HTML is escaped.

@tovic that works too, but it's just another workaround.

It would be nice if Parsedown could follow the markdown syntax for breaks.

**Comment by cebe** [comment]
It does follow the markdown syntax for breaks. breaks are allowed inside of paragraphs. between paragraphs no breaks are allowed in markdown, this is consistent with all markdown parsers: http://johnmacfarlane.net/babelmark2/?normalize=1&text=Line+1++%0ALine+2++%0A%0Anew+par

**Comment by vivaladav** [comment]
> between paragraphs no breaks are allowed in markdown

I can't find that statement in the [paragraphs and line breaks](http://daringfireball.net/projects/markdown/syntax#p) section of the markdown syntax.

**Comment by aidantwoods** [comment]
It's not a very big change, so if you want the functionality here's how to do it:
```diff
@@ -57,6 +57,15 @@ function setBreaksEnabled($breaksEnabled)
 
     protected $breaksEnabled;
 
+    function setLiteralBreaks($literalBreaks)
+    {
+        $this->literalBreaks = $literalBreaks;
+
+        return $this;
+    }
+
+    protected $literalBreaks;
+
     function setMarkupEscaped($markupEscaped)
     {
         $this->markupEscaped = $markupEscaped;
@@ -121,7 +130,7 @@ protected function lines(array $lines)
 
         foreach ($lines as $line)
         {
-            if (chop($line) === '')
+            if ( ! $this->literalBreaks and chop($line) === '')
             {
                 if (isset($CurrentBlock))
                 {
@@ -184,7 +193,15 @@ protected function lines(array $lines)
 
             # ~
 
-            $marker = $text[0];
+            if (isset($text[0]))
+            {
+                $marker = $text[0];
+            }
+            elseif ($this->literalBreaks)
+            {
+                $marker = '\n';
+                $text = '  ';
+            }
 
             # ~
```

Enable the behaviour with
```php
$Parsedown->setLiteralBreaks(true);
```

So the following
```markdown
## par 1
This is a line.  
  
 
 
   
**par 2**

And this is another one **WOW!**
```

Will be parsed as:
```html
<h2>par 1</h2>
<p>This is a line.<br />
<br />
<br />
<br />
<br />
<strong>par 2</strong>
<br />
And this is another one <strong>WOW!</strong></p>
```

I think @cebe is correct in this being off syntax for markdown though (it breaks the ability for you to interrupt a paragraph with several new lines).


As a point of reference, the [commonmark reference parser](http://spec.commonmark.org/dingus/) is consistent with Parsedown's behaviour for this one.

**Comment by vivaladav** [comment]
I still believe the syntax is a bit ambiguous there, but it seems every parser is doing the same, so maybe that is what people expect anyway.

Thank you for the patch @aidantwoods , I'll try it in my project.
