### ISSUE TITLE
How can I input ` in a InlineCode environment

### ISSUE THREAD

**Issue by vc12345679** [erusev/parsedown#449]
**Q1**

e.g., what should I type in an InlineCode environment to show this line of code ?
```
eval `dircolors -b /etc/dircolors/dircolors.ansi-dark`
```

**Q2**

Another question is similar, how can I input a trible ` in BlockCode environment ?

**Q3**

in `protected function inlineCode($Excerpt)`, line 1077，there's a sentence,
```
preg_match('/^('.$marker.'+)[ ]*(.+?)[ ]*(?<!'.$marker.')\1(?!'.$marker.')/s', $Excerpt['text'], $matches)
```

why put `(?!'.$marker.')` at the end of the regular expression ?

---
THX for your attentions.

**Comment by erusev** [comment]
you can do something like ``` `` eval `dircolors -b /etc/dircolors/dircolors.ansi-dark` `` ```

**Comment by vc12345679** [comment]
wow, bravo ! THX @erusev 

so in fenced code block, i can use four ` or more to make a treble ` display directly.

** Q2 ** and ** Q3 ** are also solved. thx again for your brilliant work.

**Comment by erusev** [comment]
you can use `~~~` as fences
