### ISSUE TITLE
Add spoiler (detail & summary) support

### ISSUE THREAD

**Issue by CallMeMantas** [erusev/parsedown#451]
## Why?

I can’t ditch bbCode or WYSIWYG editors when there’s no way to add spoilers. They are an essential feature for forum users. And, in general, I think this feature would be quite beneficial for many people.

## Demo

<details>
    <summary>Spoiler</summary>
   <p>Boop dee doop.</p>
</details>

### In Markdown

I’ve seen that [this syntax is in use](http://meta.stackexchange.com/questions/1191/add-markdown-support-for-hidden-until-you-click-text-aka-spoilers):

```
>! Boop dee doop.
```

### Conversion to HTML

I propose using the new `<details>` and `<summary>` elements.

+ They are [supported well by modern browsers](http://caniuse.com/#feat=details).
+ Polyfills for Internet Explorer and Edge [are available](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#details-and-summary).
+ [Microsoft’s Edge Status site](http://status.modern.ie/detailssummary) states that the summary/details elements are “under consideration.”
+ This feature is semantically corrected and [it’s now a part of the HTML 5.1 spec](https://www.w3.org/TR/html51/interactive-elements.html#the-details-element)!

Here’s how the code would look like:

```html
<details>
    <summary>Spoiler</summary>
    <p>Boop dee doop.</p>
</details>
```

**Comment by erusev** [comment]
That's a cool feature, but it should be implemented as an extension - you could see instructions on how to create one in the wiki.

**Comment by aidantwoods** [comment]
Pretty sure this should do it

Branch: https://github.com/aidantwoods/parsedown/tree/spoiler
Diff: https://github.com/aidantwoods/parsedown/commit/cde18507dd4d2c844f66f553edf53e4245a28c11

**Comment by CallMeMantas** [comment]
Lovely. That’s just what I wanted, thank you, @aidantwoods!
