### ISSUE TITLE
Thank you - Not an issue

### ISSUE THREAD

**Issue by cavo789** [erusev/parsedown#453]
*Thank you Emanuil*

Just to inform you that I've written a small (at this time) interface for displaying .md files on my computer and render them in HTML (thanks to your class).   If you've interest with it, the script is free and available here : https://github.com/cavo789/markdown

Thank you for having take time to write your class, maintain it and making its use free.

Bye.

**Comment by erusev** [comment]
Thanks Christophe, I appreciate it :)
