### ISSUE TITLE
Image Markdown in Wrapping <div> Fails to Render...

### ISSUE THREAD

**Issue by purplegriffon** [erusev/parsedown#455]
When you have an image reference in markdown that is within wrapping HTML, for example a div, it fails to render to HTML and simply outputs the markdown. For example:

    <div class="test">
        ![Image Alt](/image.jpg)
    </div>

This will simply output `![Image Alt](/image.jpg)` to the browser.

**Comment by PhrozenByte** [comment]
This is expected behavior. Try [`erusev/parsedown-extra`](https://github.com/erusev/parsedown-extra) and
```html
<div class="test" markdown="1">
![Image Alt](/image.jpg)
</div>
```

**Comment by purplegriffon** [comment]
Ah, OK. Thanks for the heads up and the recommendation.

**Comment by erusev** [comment]
I'm closing this.
