### ISSUE TITLE
Parsing URL inside <a> tag

### ISSUE THREAD

**Issue by adam-boduch** [erusev/parsedown#456]
Parsedown MUST NOT parse URL inside `<a>` tag. 
Input text:

`<a href="http://www.google.com">http://www.google.com</a>`

Correct output (original Markdown PHP 1.3):

`<p><a href="http://www.google.com">http://www.google.com</a></p>`

Incorrect output (Parsedown):

`<p><a href="http://www.google.com"><a href="http://www.google.com">http://www.google.com</a></a></p>`

**Comment by cebe** [comment]
duplicate of #432
