### ISSUE TITLE
Changing the image sizes in parsedown?

### ISSUE THREAD

**Issue by tasmanwebsolutions** [erusev/parsedown#460]
Hello, In parsedown how to alter the  image sizes when use reference links for image

```
![enter image description here][1]
[1]: https://www.allaboutbirds.org/guide/bbimages/aab/images/blue-winged-warbler.jpg 100%x300
```

Then the out put would be 

```
<img src="https://www.allaboutbirds.org/guide/bbimages/aab/images/blue-winged-warbler.jpg" width="100%" height="300">
```
Not sure what I need for php side of things to enable it?

**Comment by wolfgang1983** [comment]
This may help any one who interested http://stackoverflow.com/questions/41561684/parsedown-set-image-width-and-height/41609464#41609464

**Comment by aidantwoods** [comment]
This is probably best achieved by an extension (as mentioned in the link) :)
