### ISSUE TITLE
Maximum nesting level reached

### ISSUE THREAD

**Issue by YLivay** [erusev/parsedown#462]
Heya!

We have weird users submitting weird strings - and one of them triggered a fatal error for "Maximum function nesting level of X reached, aborting!"

There isn't a way to catch and handle the error or detect it before starting to parse so I'm hoping Parsedown could have a fail-safe in that case that'll allow us to choose how to handle these cases.

The string is:
```_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________.EXE```

I suggest tracking the depth when parsing inner elements and being able to specify a limit before parsing. Optionally, just before the limit is reached it could use another option to tell it what to do: either throw an exception or attach the raw, unparsed inner element.

By the way, really appreciate your work on this lib! We've been using it for quite a while now and it's been mostly good to us :)

**Comment by aidantwoods** [comment]
Does this issue still occur for you? I can't replicate it locally
<img width="822" alt="screen shot 2018-03-28 at 03 00 29" src="https://user-images.githubusercontent.com/3288888/38004457-3c2bb326-3234-11e8-877d-46960f391fa7.png">

**Comment by cebe** [comment]
> Maximum function nesting level of X reached, aborting!

sounds like you have xdebug enabled.
