### ISSUE TITLE
Trimming indentation in block code

### ISSUE THREAD

**Issue by adam-boduch** [erusev/parsedown#466]
Input contains Python code:

![image](https://cloud.githubusercontent.com/assets/10835050/22205059/75a6e3c0-e175-11e6-92f3-b575148b47df.png)

Output:

```
<ol>
<li>foobar
<pre><code>class IInterface:
def show(self): raise NotImplementedError</code></pre></li>
<li>foobar</li>
</ol>
```

![image](https://cloud.githubusercontent.com/assets/10835050/22205073/86c33398-e175-11e6-8b2d-57b48e3613a0.png)

As you can see, indentation is lost. Correct output:

1. foobar
```
class IInterface:
    def show(self): raise NotImplementedError
```
2. foobar

**Comment by aidantwoods** [comment]
Closing and tracking underlying issue directly: https://github.com/erusev/parsedown/issues/707
