### ISSUE TITLE
Parsedown does not convert markdown to html in this case

### ISSUE THREAD

**Issue by OussamaElgoumri** [erusev/parsedown#468]
The markdown that did not convert

```
في المثال التالي: `+` أو `%20` يتم تحويلها إلى فراغ أو space

<asciinema-player src="/storage/asciinema/1ed3ebca171211e8a7f276cae2dc835f681d805e.json" cols="auto" rows="20" poster="npt:10"></asciinema-player>

وسيط ConvertEmptyStringsToNull
========================

أظن أن الإسم هنا يشرح نفسه، فهذا الوسيط يقوم بتحويل الجمل الفارغة إلى null، حتى لايتم وضع `""` في حقل معرف بـ `null` بقاعدة البيانات.

<asciinema-player src="/storage/asciinema/a1f9ad8616d079d38602a091db04f8166cc70c9c.json" cols="auto" rows="20" poster="npt:10"></asciinema-player>
```

The results

![](http://sec4ar.com/storage/4f/82/0c/f2/5d/43/e9/84/0f/3d/fe/68/f5/80/4a/4b/62/be/eb.png "")

You can see the results with the broken converted markdown here 

http://sec4ar.com/%D9%85%D8%A7-%D8%A7%D9%84%D8%AC%D8%AF%D9%8A%D8%AF-%D9%81%D9%8A-laravel-5-4-sanitizing-middleware

Thank you for your support.

**Comment by aidantwoods** [comment]
Hi there, I tried running the input above though Parsedown and I didn't see anything immediately broken about the output.

If the issue is still happening please feel free to reopen with some more info :)
