### ISSUE TITLE
I cant use syntax highlighting for bash scripts

### ISSUE THREAD

**Issue by sajadabasi** [erusev/parsedown#470]
Dear,
I can't use syntax highlighting for bash scripts.
Is it supported or I did some thing wrong?
Thanks.

**Comment by aidantwoods** [comment]
Parsedown doesn't do this, but you could create (or use) an extension that does. @JonasDoebertin included a code snippet which should outline the general idea for making one in https://github.com/erusev/parsedown/issues/568#issuecomment-373321810
