### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by sajadabasi** [erusev/parsedown#472]
I cant add syntax highlighting there is no css.... how can I add css to have highlighting and style like the demo website?

**Comment by aidantwoods** [comment]
Taking a quick glance at the demo page, looks like it's using [google-code-prettify](https://code.google.com/archive/p/google-code-prettify/wikis/GettingStarted.wiki).

Parsedown produces a language hint if you specify a language in your markdown, e.g.

~~~markdown
```php

<?php
    
foreach ($foo as $bar)
{
    echo $bar;
}
```
~~~

goes to

```html
<pre><code class="language-php">
&lt;?php

foreach ($foo as $bar)
{
    echo $bar;
}</code></pre>
```

Syntax highlighting isn't a feature of Parsedown though.

**Comment by sajadabasi** [comment]
the output of web site is different is has many span but output of the code do not have
> and adds <span>s to colorize keywords, strings, comments, and other token types.

**Comment by aidantwoods** [comment]
These aren't produced by parsedown, these'll be inserted by the JavaScript so that styles can be applied to specific words etc...

**Comment by Francesco-Rizzi** [comment]
Yes, in their demo website they use http://prismjs.com/

BTW >>> I think **_would be really useful if they integrate something like pygments to make syntax highlight_** server side (then you just need to include a 'standard' pygment compliant css and you are gone)

**Comment by o0oke** [comment]
agree to adding Syntax Highlight feature

**Comment by BourgeoisBear** [comment]
I've implemented a pygments solution for fenced code blocks that specify the language.  Since it has an external dependency of the Python pygments script, I'm not sure if it makes more sense to package it, or to just put it in the documentation as an example that can be re-worked for different highlighting solutions?

**Comment by daybugging** [comment]
Packaging it would be great - especially shared hosting people could use this

**Comment by aidantwoods** [comment]
This is probably out of scope for now – even as an optional feature it would involve either adding a lot of code or taking on library dependency, of which Parsedown currently doesn't have any (so would be a pretty major change). As mentioned in #470, I think this would be better implemented as an extension to Parsedown that can focus on maintaining syntax highlighting for various languages.
