### ISSUE TITLE
how to use parsedown in laravel 5.4

### ISSUE THREAD

**Issue by arjilm** [erusev/parsedown#476]
### how to use parsedown in laravel 5.4
in laravel 5.4 have include composer package "erusev/parsedown": "~1.6" https://github.com/laravel/framework/blob/5.4/composer.json#L22
But how I can use erusev/parsedown class in controller?

**Comment by cebe** [comment]
did you try it as described in the readme: https://github.com/erusev/parsedown#example ?

**Comment by aidantwoods** [comment]
Closing as I think the question was answered?
