### ISSUE TITLE
Markdown is unable to parse correctly with multi-level quoted text

### ISSUE THREAD

**Issue by jllano** [erusev/parsedown#478]
When rendering quoted text with multiple levels of indentation, the markdown is not dealing well with multiple levels of indentation without newlines between levels

```
> > some text
>  more text
```

Renders as:
> > some text
>  more text

This is normal based on the current [CommonMark spec](http://spec.commonmark.org/0.27/#block-quotes) due to the so-called "Laziness rule", but it is a problem when rendering legacy text in Mantis.

Ideally, I would expect the above to render like this:
> > some text
>
>  more text

**Comment by dregad** [comment]
@jllano I'm not convinced this is an issue with parsedown.

See http://spec.commonmark.org/0.27/#example-212

**Comment by jllano** [comment]
right, github behave the same way as well

>>> foo
> bar
>>baz

**Comment by jllano** [comment]
closing this issue since its not an issue in any way.
