### ISSUE TITLE
Markdown is not exactly follows with # characters as ATX headings

### ISSUE THREAD

**Issue by jllano** [erusev/parsedown#479]
An ATX heading consists of a string of characters, parsed as inline content, between an opening sequence of 1–6 unescaped # characters and an optional closing sequence of any number of unescaped # characters. The opening sequence of # characters must be followed by a space or by the end of line. The optional closing sequence of #s must be preceded by a space and may be followed by spaces only. The opening # character may be indented 0-3 spaces. The raw contents of the heading are stripped of leading and trailing spaces before being parsed as inline content. The heading level is equal to the number of # characters in the opening sequence.

http://spec.commonmark.org/0.27/#atx-heading

```
#this is not H1 
```
but it shows as: `<h1>this is not H1</h1>`

**Comment by cebe** [comment]
see https://github.com/erusev/parsedown/issues/265

**Comment by jllano** [comment]
Thank you @cebe for sharing the reference, it looks like the issue wont get fix anytime soon I think.

Anyway, there's a fix solution for this by overriding the `blockHeader` extension instead.
