### ISSUE TITLE
Simple ascii emojis throw error

### ISSUE THREAD

**Issue by paulschwarz** [erusev/parsedown#481]
When I run `$renderer->text(':)')` I get 

```
  [ErrorException] Undefined index: name

#1  /var/www/vendor/erusev/parsedown/Parsedown.php:1404
#2  /var/www/vendor/erusev/parsedown/Parsedown.php:1044
#3  /var/www/vendor/erusev/parsedown/Parsedown.php:1425
#4  /var/www/vendor/erusev/parsedown/Parsedown.php:271
#5  /var/www/vendor/erusev/parsedown/Parsedown.php:39
#6 ...
```

**Comment by aidantwoods** [comment]
I can't seem to reproduce on `master` branch
<img width="362" alt="screen shot 2017-03-02 at 23 02 48" src="https://cloud.githubusercontent.com/assets/3288888/23531055/67634322-ff9c-11e6-8368-6574d63b78e7.png">

**Comment by paulschwarz** [comment]
Terribly sorry, my bug was elsewhere. Please mark this as invalid.
