### ISSUE TITLE
Excuse an amateur -- what do I upload where?

### ISSUE THREAD

**Issue by philipca** [erusev/parsedown#483]
I am not a developer, but I want to understand how Parsedown would work on my Linux shared hosting.

Given that I know how to FTP files and edit them: 

* what do I have to upload to my server?
* where do I put it?
* what commands do I then put into an index.php file to make use of Parsedown?

Again, please excuse the fact that I don't understand what to do, or if there is a "Dummies" guide to this kind of stuff, please point me to it!

**Comment by cebe** [comment]
@philipca depends on what you want to do with Parsedown. I doubt it would be of any use if you do not know how to write php.

**Comment by philipca** [comment]
But how would somebody who **_does_** know how to 'write PHP' install it on my site. I like to understand how things work before I pay such a person to make use of it for me.

I know where and how to create and edit css files, I know where to install javascript files and how to call them.  Is using Parsedown very much different from those??

**Comment by cebe** [comment]
Parsedown is a library that can convert Markdown to HTML, it comes as a PHP class without any frontend or user interface. It can be used as part of other software to provide some functionality, it does not make sense to use it alone.

**Comment by philipca** [comment]
So, if a PHP file (ie a webpage) is going to call Parsedown, where does it find Parsedown?
I thought something was uploaded to the server, or is it dynamically loaded like javascript?

**Comment by AffanIndo** [comment]
Correct me if I wrong. I still learn PHP.
I think you should reference the parsedown.php using "require"
![1](https://cloud.githubusercontent.com/assets/18306510/23858987/d2f22090-0834-11e7-84e4-2a1b9bf97463.JPG)

**Comment by jonathanbell** [comment]
@philipca This is not really an "issue". 

Anyways, an absolute "bare bones", just-make-it-work example would look like this: 

1. [Download the Parsedown.php](https://raw.githubusercontent.com/erusev/parsedown/master/Parsedown.php) class file.
1. Upload it to your server.
1. Place ```index.php``` file in the same directory as ```Parsedown.php``` and include this code in ```index.php```:
```
<?php

require 'Parsedown.php';

$Parsedown = new Parsedown();

$theText = file_get_contents('EXAMPLE.md');

echo $Parsedown->text($theText); 
```
4. Write some markdown and save the content as ```EXAMPLE.md``` in the same directory as the other files.
5. View ```index.php``` in the browser.

However, as others have said, some knowledge of PHP and classes will go a long way - but this will get you a "Hello World" example.

**Comment by philipca** [comment]
Thank you, Jonathan Bell. A clear and polite instruction, which I could follow easily.
Parsedown now works for me, and so I understand better how it can be invoked and used.
Thank you for making this clear to me.

**Comment by philipca** [comment]
Actually, now I understand Parsedown (and Markdown) more fully, it looks like a better fit for my needs would be the 'editor' supplied on this GitHub page that I am typing in now!!
Could somebody please explain to me what it is, and where I could obtain it??
