### ISSUE TITLE
<kbd> HTML tag breaks parsing

### ISSUE THREAD

**Issue by adam-boduch** [erusev/parsedown#486]
Input:

```
<kbd>C</kbd> `foo`
```

Expected result:

```
<p><kbd>C</kbd> <code>foo</code></p>
```

Parsedown:

```
<kbd>C</kbd> `foo`
```

As you can see, parsedown does not parse text after `<kbd>` tag. It's wired because it works with other html tags.

![image](https://cloud.githubusercontent.com/assets/10835050/24069802/4b70f792-0bb1-11e7-9080-ce3956490ce0.png)

**Comment by aidantwoods** [comment]
Seems this no longer occurs, but please reopen if you're still having the same issue in the latest version.

<img width="837" alt="screen shot 2018-03-27 at 21 16 45" src="https://user-images.githubusercontent.com/3288888/37992631-2df15dfe-3204-11e8-9565-912539781260.png">
