### ISSUE TITLE
Bug with inlineUrl method - not consider already wrapped anchor with the same URL

### ISSUE THREAD

**Issue by doiftrue** [erusev/parsedown#487]
Example text

```
foo <a href="http://seoso.ru/services.html">http://seoso.ru/services.html</a> bar
```

We have the same URL in href attribute and in link anchor. And what we get in output?

![](http://savepic.net/9076449.png)

how fix it correctly?

**Comment by doiftrue** [comment]
For now I fix it so:

original method code - https://github.com/erusev/parsedown/blob/master/Parsedown.php#L1337

fixed

```
	protected function inlineUrl($Excerpt)
	{
		if ($this->urlsLinked !== true or ! isset($Excerpt['text'][2]) or $Excerpt['text'][2] !== '/')
		{
			return;
		}

		if (preg_match('/\bhttps?:[\/]{2}[^\s<]+\b\/*(.{4})/ui', $Excerpt['context'], $matches, PREG_OFFSET_CAPTURE))
		{
			if( $matches[1][0] == '</a>' ) return; // not process text like 'foo <a href="http://seoso.ru/services.html">http://seoso.ru/services.html</a> bar'

			$Inline = array(
				'extent' => strlen($matches[0][0]),
				'position' => $matches[0][1],
				'element' => array(
					'name' => 'a',
					'text' => $matches[0][0],
					'attributes' => array(
						'href' => $matches[0][0],
					),
				),
			);

			return $Inline;
		}
	}
```

add `(.{4})` at the end of regular expression and then check if there is `</a>` after URL for not process inline URL if it is already in A tag...

**Comment by aidantwoods** [comment]
@erusev merging https://github.com/erusev/parsedown/pull/433 would fix this issue 😃

**Comment by doiftrue** [comment]
Not works :( I update parsedown code and what I need to add to inlineUrl() method?

**Comment by aidantwoods** [comment]
If you use this version of parsedown (https://github.com/aidantwoods/parsedown/blob/3aef89b3994d942d4eb85d6df0c8c43a157ac5d7/Parsedown.php)
Or apply the changes from the PR linked to it should prevent a tags being nested
