### ISSUE TITLE
Invalid parsing syntax in HTML tag

### ISSUE THREAD

**Issue by piotrooo** [erusev/parsedown#488]
I have following text:

```
<div class="alert alert-warning">
**bold**

# h1
## h2

> quote1
> quote2

* uno
* due

1. one
2. two

[foo.bar](http://foo.bar)
</div>
```

And parer won't parse syntax into `div` wrapper.

**Comment by kminchev** [comment]
Expected. See [other reports](https://github.com/erusev/parsedown/search?q=div&type=Issues).

**Comment by aidantwoods** [comment]
If Parsedown is aiming to be CommonMark compliant then this is a [bug](http://spec.commonmark.org/0.27/#example-118).

Though a single blank line should follow the initial `<div>` in order for the first `**bold**` to be parsed correctly.
