### ISSUE TITLE
Link Target Blank

### ISSUE THREAD

**Issue by ajmerainfo** [erusev/parsedown#494]
Hello,

How can we use target blank on each links?

**Comment by perryflynn** [comment]
Just extend Parsedown or ParsedownExtra.

Here is a snippet from a project of mine.

```php
class ParsedownExtensions extends \ParsedownExtra
{
   protected $newtablink = false;

   public function setAllLinksNewTab($b)
   {
      $this->newtablink = $b===true;
   }

   protected function applyOwnLinkStuff(&$link)
   {
      // **snipp**
      if($this->newtablink===true)
      {
         $link['target'] = "_blank";
      }
      // **snipp**
   }

   // overwritten methods from parsedown
   protected function inlineLink($Excerpt) {
      $temp = parent::inlineLink($Excerpt);
      if(is_array($temp))
      {
         if(isset($temp['element']['attributes']['href']))
         {
            $this->applyOwnLinkStuff($temp['element']['attributes']);
         }
         return $temp;
      }
   }

   protected function inlineUrl($Excerpt)
   {
      $temp = parent::inlineUrl($Excerpt);
      if(is_array($temp))
      {
         if(isset($temp['element']['attributes']['href']))
         {
            $this->applyOwnLinkStuff($temp['element']['attributes']);
         }
         return $temp;
      }
   }

}
```

**Comment by tovic** [comment]
My [extension](https://github.com/tovic/parsedown-extra-plugin) can automatically set `rel="nofollow"` and `target="_blank"` attributes to a link when it is detected as an external link. You can also set those attributes manually through the attribute block:

~~~
[text](http://example.com) {rel="nofollow" target="_blank"}
~~~

**Comment by thierry-bugeat** [comment]
I found a bug in the interpretor...
[test](http://example.com/test/"target="_blank)
This link opens a new window.

**Comment by aidantwoods** [comment]
> I found a bug in the interpretor...
> `[test](http://example.com/test/"target="_blank)`
> This link opens a new window.

This should be fixed when #495 is merged.

**Comment by aidantwoods** [comment]
As mentioned by others, this particular feature lends itself quite well to being implemented via an extension so I'll close because there is an easy way to add the behaviour

**Comment by pokono** [comment]
@aidantwoods Would be good though to have maybe a list of official extensions that are maintained?
