### ISSUE TITLE
PSR-4 compliant

### ISSUE THREAD

**Issue by fahmilatib** [erusev/parsedown#506]
Is there any plan to make this package a PSR-4 compliant?

**Comment by cebe** [comment]
see https://github.com/erusev/parsedown/pull/328

**Comment by cebe** [comment]
However, I do not see an argument for changing, this package provides exactly one class, that is not namespaced. It does not really matter if you choose PSR-4 or PSR-0 for loading it.

**Comment by fahmilatib** [comment]
Ah didn't realize there's already a PR for that. My apology.
