### ISSUE TITLE
Cap drop syntax with Parsedown

### ISSUE THREAD

**Issue by Flerex** [erusev/parsedown#507]
Hello,

I'm trying to create a new syntax to format paragraphs. What I'm trying to achieve is to have a paragraph's first letter as a cap drop. The syntax I'd expect the user to use is the following, where, of all the accents, only the first one would make the E a cap-drop.

> ^Et rerum sint laudantium eaque veritatis sunt id. Eos vero architecto molestiae facere blanditiis. Consectetur iure error et fugit quasi. Quaerat maxime tenetur eu^m possimus sunt ea maxime. Inventore impedit similique perferendis illum earum ^nam magnam rerum. Qui ut non voluptatem.

I tried to accomplish this following the "color" code of the Extension tutorial, but the following code would work with all the ^, even if they don't strictly start a paragraph.

```
public function inlineDropCap($excerpt)
{

	if (preg_match('/^\^(.{1})/', $excerpt['text'], $matches)) {
		return [
			'extent'  => strlen($matches[0]),
			'element' => [
				'name' => 'span',
				'text' => $matches[1],
				'attributes' => [
					'class' => 'drop-cap',
				],
			],
		];
	}
	
}
```

Can anyone help me with this?

Thank you in advance.

**Comment by aidantwoods** [comment]
Have you added `^` as a new marker near the top of the Parsedown file?

**Comment by aidantwoods** [comment]
Also, this might be better implemented as a block structure if you only want it to apply at the start of a paragraph

**Comment by Flerex** [comment]
I just tried to change inline to block in the function name and modify a little the function. It is working now, but I found some weird behavior that I guess it's caused because the code is not correctly modified.

If the accent is at the begining of more than one paragraphs. Every cap drop is shown only in the first paragraph with a cap drop. Like this:

```
## Lorem Ipsum

^Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

^Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation *ullamco* laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

![screen shot 2017-05-27 at 16 56 54](https://cloud.githubusercontent.com/assets/3910120/26522296/82a260ba-42fd-11e7-8bc4-9218592f9c4b.png)


The code is the following:

```
public function blockDropCap($line, $block)
	{

		if (preg_match('/^\^(.{1})/', $line['text'], $matches)) {
			return [
				'extent'  => strlen($matches[0]),
				'element' => [
					'name' => 'span',
					'text' => $matches[1],
					'attributes' => [
						'class' => 'drop-cap',
					],
				],
			];
		}
		
	}
```

**Comment by aidantwoods** [comment]
Could you post the html being output by your Parsedown extension?

**Comment by Flerex** [comment]
Yes, of course. Here you go:

```
<h2>Lorem Ipsum</h2>
<span class="drop-cap">L</span>
<span class="drop-cap">L</span>
<h2>Ut enim ad minim</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis <code>nostrud</code> exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
```

**Comment by aidantwoods** [comment]
So with block structures, you'd need to capture everything you're given in `$line`, and then pass all the content (except first two characters I guess) off to the `line` hander so that inline elements can be recognised.

You'd want something similar to blockquote https://github.com/erusev/parsedown/blob/master/Parsedown.php#L601 , except on subsequent lines you should only use something like this https://github.com/erusev/parsedown/blob/master/Parsedown.php#L633-L638 since you'll only care that the block is continuous and won't have any requirements on markers.

The `extent` in the above is only useful for inline structures.

---

From the posted html, it looks as expected for the first four lines (where text from the middle two is lost because the current block handler for this is dropping the data)

```html
<h2>Lorem Ipsum</h2>
<span class="drop-cap">L</span>
<span class="drop-cap">L</span>
<h2>Ut enim ad minim</h2>
```

But I can't quite see why the text is parsed again to yield 

```html
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis <code>nostrud</code> exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
```

Unless you have some more test data going through Parsedown in addition to what you've posted?

**Comment by Flerex** [comment]
No, I don't have anything more. This is the whole class:

```
class Markdown extends Parsedown {
	
	function __construct()
	{
		$this->BlockTypes['^'][]= 'DropCap';
	}

	public function blockDropCap($line)
	{

		if (preg_match('/^\^(.{1})/', $line['text'], $matches)) {
			return [
				'element' => [
					'name' => 'span',
					'text' => $matches[1],
					'attributes' => [
						'class' => 'drop-cap',
					],
				],
			];
		}
	}

	public function blockDropCapContinue($line, $block)
	{
		if(!isset($block['interrupted'])) {
			$block['element']['text'][] = $line['text'];
			return $block;
		}
	}

}
```

I tried to do the "continue" version of the function but tbh I don't understand pretty well how Parsedown works and it's still happening the same.

**Comment by aidantwoods** [comment]
Hmm... regarding
> But I can't quite see why the text is parsed again to yield

I can't replicate those additional paragraphs using the file above, so I'm not sure what's going on there.

Try this:
https://gist.github.com/aidantwoods/e7ac888c7c7316e9c76424e759f210b5

```markdown
## Lorem Ipsum

^Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

^Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation *ullamco* laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Ut enim ad minim
```

```html
<h2>Lorem Ipsum</h2>
<p>
<span class="drop-cap">L</span>
<p>orem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</p>
<p>
<span class="drop-cap">L</span>
<p>orem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation <em>ullamco</em> laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</p>
<h2>Ut enim ad minim</h2>
```

**Comment by aidantwoods** [comment]
Note I changed your regex slightly: `{1}` is implied, and I figured you probably didn't want `.` (for any char – including whitespace), so I switched it to `\w` for wordy chars – you might want to further restrict to alphanumerics, or just letters though.

**Comment by Flerex** [comment]
I just tried your code and it works but the output of a paragraph is:

```
<p><span class="drop-cap">L</span></p>
<p>orem Ipsum</p>
```

And it should be:

`<p><span class="drop-cap">L</span>orem Ipsum</p>`

I'm also trying to understand how you did it but I'm having a hard time. Isn't there some kind of documentation of Parsedown?

**Comment by Flerex** [comment]
If I modify your function like the following, I get the expected output but I don't know if hardcoding a span element directly is a good practice. 

```
public function blockDropCap($line)
    {

        if (preg_match('/^\^(\w)/', $line['text'], $matches)) {
            return [
                'element' => [
                    'name' => 'p',
                    'handler' => 'elements',
                    'text' => [
                        [
                            'name' => 'p',
                            'handler' => 'line',
                            'text' => '<span class="drop-cap">'. $matches[1] . '</span>' . substr($line['text'], 2),
                        ]
                    ],
                ],
            ];
        }
    }
```

**Comment by aidantwoods** [comment]
> And it should be:
> 
> `<p><span class="drop-cap">L</span>orem Ipsum</p>`

Hmm, you could try using another span there possibly if you don't want a `<p>`, (as far as I know) currently not possible in Parsedown to have a plain-text element at the block level (i.e. text next to an element at the same nesting).

I.e. you could do

```html
<p>
<span class="drop-cap">L</span>
<span>orem Ipsum</span>
</p>
```

Simply adjust this line https://gist.github.com/aidantwoods/e7ac888c7c7316e9c76424e759f210b5#file-parsedownextension-php-L29

so that `'p'` is changed to 'span'.

**Comment by aidantwoods** [comment]
> If I modify your function like the following, I get the expected output but I don't know if hardcoding a span element directly is a good practice.

Yeah, don't do that (it'll break when my anti-xss PR is merged #495 😉)

**Comment by aidantwoods** [comment]
> I'm also trying to understand how you did it but I'm having a hard time. Isn't there some kind of documentation of Parsedown?

Not so much for the internals, I've just have to read the source really.

Roughly, every block should have an element in it (`$Block['element']`), each element has a handler `$Block['element']['handler']` (which is just the function some data will be passed it), and the `$Block['element']['text']` should only ever be text if the handler isn't specified, otherwise it should be the argument to pass to the handler.

**Comment by Flerex** [comment]
> currently not possible in Parsedown to have a plain-text element at the block level (i.e. text next to an element at the same nesting).

I found having the rest of the paragraph inside another HTML tag unnecessary, but if it's not possible I'll just have to live with it. It's not that big of a problem haha.

I appreciate all your help @aidantwoods and I'm sorry for bothering you with this. Thank you very much!

**Comment by aidantwoods** [comment]
@Flerex no worries, glad I could help! 👍 

---

@erusev Perhaps the Wiki needs updating with some description on how to navigate things like custom handlers, `$Block['element']['text']` is certainly a bit confusingly named when the handler is `elements` and `$Block['element']['text']` is an array for example (used like this internally too e.g. with blockList).

**Comment by erusev** [comment]
@aidantwoods 

I agree - I don't have much time to do it right now, but I'd appreciate it if someone did it.
