### ISSUE TITLE
PhpStorm complains about class_alias in tests' bootstrap

### ISSUE THREAD

**Issue by krotovic** [erusev/parsedown#509]
Hi @erusev, I love Parsedown and I really appreciate your work. But there is small annoying "issue" (lets call it issue). I'm using PhpStorm for almost all my PHP projects development and when I require Parsedown through Composer I get a warning in my PHPUnit tests that there are multiple implementation of class TestCase. I have read your test's bootstrap file and figured out that you are using `class_alias`. Is that really necessary? Cannot you just require specific version of PHPUnit in your composer.json file and count on that?

**Comment by sebastiaanluca** [comment]
See https://github.com/erusev/parsedown/issues/490. Requested quite a while ago, but no fix yet.

**Comment by krotovic** [comment]
Ah, ok, thank you, didn't find that one. So closing this.
