### ISSUE TITLE
Conflicts With MathJax

### ISSUE THREAD

**Issue by estoquodaudes** [erusev/parsedown#510]
If I want to include some math formulas in LaTex, I can't avoid using "_".
And sometimes Parsedown will translate them into "<em> </em>",which stops MathJax from interpreting

**Comment by aidantwoods** [comment]
Could you post an example?

**Comment by cebe** [comment]
you'd need to extend Parsedown to handle formulas included in `$` in a special way, i.e. not interpret the content as markdown. That means adding  `$` as an inline element. Normal markdown does not treat  `$` as a special character so that should be done in an extension imo.

**Comment by aidantwoods** [comment]
If you like, you can grab https://github.com/aidantwoods/parsedown/blob/mathjaxlatex/ParsedownExtensionMathJaxLaTeX.php

Which overloads a single `` ` `` to be inline math, and adds special handling for the language `latex` when used in fenced code. You might want to make some changes to those markers to suit you though.

---

I'm a little intrigued as to the cases where Parsedown is turning `_` into spaces (as reported) though, smells like a bug if that is the case.

**Comment by aidantwoods** [comment]
As mentioned this would be best handled by an extension, also see #554
