### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function text() on null

### ISSUE THREAD

**Issue by D14RAP** [erusev/parsedown#518]
Fatal error: Uncaught Error: Call to a member function text() on null in (INCLUDE LOCATION) Stack trace: #0 {main} thrown in (INCLUDE LOCATION) on line 26

```<?php
include("partials/Parsedown.php");
echo $Parsedown->text($row["content"]);
?>
```

The content is there as can echo out normally

**Comment by aidantwoods** [comment]
You just need to instanciate Parsedown

Simply add
```php
$Parsedown = new Parsedown;
```

Between lines 1 and 2. 

You may also find this useful reading :)
https://stackoverflow.com/questions/2206387/what-is-a-class-in-php

**Comment by D14RAP** [comment]
Thanks for the assistance, works a treat now!
