### ISSUE TITLE
Wrong converting of md to html code

### ISSUE THREAD

**Issue by refeaime** [erusev/parsedown#519]
So, here is original .md file http://paste.ubuntu.com/25163892/
Here is code result : http://paste.ubuntu.com/25163897/
Using Fico flat cms, which uses parsedown to convers md to html as class. I thouht, maybe this is Pico issue, and changed parsedown.php class from github. But nothing changed. 
What is going on? 
Thank you.

**Comment by aidantwoods** [comment]
I think this is a bug in the CMS. 

Try putting the text into http://parsedown.org/, if it renders correctly then the problem is unlikely with Parsedown. Looks like the markdown is being processed correctly and then html encoded by something afterward going by those links provided.

**Comment by PhrozenByte** [comment]
It's very unlikely that this is an issue with Pico 😉 The most likely cause is an issue with @refeaime's custom theme. @refeaime, join us on [#picocms on Freenode](https://webchat.freenode.net/?channels=%23picocms) so that we can solve your problem.

**Comment by aidantwoods** [comment]
I shall take your word for it! That does sound reasonable though, I'd be very surprised if this was happening in the default install 😉

**Comment by refeaime** [comment]
thanks guys! =)
