### ISSUE TITLE
Unbalanced <?php

### ISSUE THREAD

**Issue by jmparatte** [erusev/parsedown#522]
Please, add a final `?>` at end of Parsedown.php file because the `<?php` is unbalanced.

Thank's.

**Comment by atrol** [comment]
There is a good reason to omit the closing tag, see [this Note](http://php.net/manual/en/language.basic-syntax.instruction-separation.php).

**Comment by jmparatte** [comment]
Thank's atrol, you are right with the mentionned note.
But I disagree with this syntax because we are unsure about if the file is inadvertently truncated.
And I was wrong with my sentence about uHTTPd of Yún implementation, that's of no problem.
Parsedown.php is a great job!
