### ISSUE TITLE
Tutorial: getting started is missing the "require " line

### ISSUE THREAD

**Issue by nickdos** [erusev/parsedown#526]
I'm a very occasional PHP developer who codes in Java and JS most of the time. I tried using this module and followed the [getting started wiki page](https://github.com/erusev/parsedown/wiki/Tutorial:-Get-Started) but I got an interupted html output. It was only after I read issue #483, did I see I had not included the `require 'Parsedown.php';` line. 

Please add this line to both the getting started page and the README.md file.

**Comment by PhrozenByte** [comment]
This is already in the `README.md`, check the `Installation` section. I've explicitly added it to the wiki, too.

**Comment by nickdos** [comment]
Thanks for the quick reply. I found the README file to be ambiguous. I did read it before starting but I interpreted the "include" text to mean you simply download (include) the file in the same directory as the php file, which I did. Maybe explicitly show code example with and without the include line, depending on whether the composer package is used(?).
