### ISSUE TITLE
String with multiple tabs breaks Parsedown

### ISSUE THREAD

**Issue by conorhub** [erusev/parsedown#527]
I'm having trouble obtaining any error logs for this so please excuse the lack of finer detail, but I'll explain the scenario:

A user was complaining that a page of theirs was blank. While debugging it, I discovered that the `php` page was refusing to render after the following:

`$textBody = $Parsedown->text($text);`

which had worked for every other user. I checked the string they had entered (`$text`), which was being sanitised with: `htmlspecialchars($text, ENT_QUOTES | ENT_HTML5)` and saw nothing obviously wrong. There were some characters with accents but I thought these would not stop *Parsedown* from working.

I then performed a find a replace of tabs to spaces in the string. *Parsedown* now worked fine and produced a `$textBody` string, and the page finished rendering.

There were a lot of tabs (it was unfortunately copied and pasted from a *Word* document and many of these were adjacent). Is this a bug?

**Comment by conorhub** [comment]
In the meantime I'm running a `preg_replace` of tabs to spaces before the string ever reaches `Parsedown`, like so:

`$text = trim(preg_replace('/\s+/g', '', $text));`

**Comment by aidantwoods** [comment]
Is there a particular input sample you can give that that causes the issue? I'm not able to replicate
<img width="822" alt="screen shot 2017-08-31 at 20 35 53" src="https://user-images.githubusercontent.com/3288888/29941946-17e12baa-8e8c-11e7-87c4-258678874aef.png">

**Comment by conorhub** [comment]
Unfortunately I cannot, both due to privacy for the client (it was a biography) and because the string now has no tabs after being repaired. I'm aware this is pretty unfortunate not to be able to provide a source that actually caused the issue in question.

Given that your own testing placed multiple tabs beside each other, it's clearly not the sole requirement to cause the issue. All I can confirm are the following factors:

Any user-entered string had caused no issue up until today using:

```
$text = htmlspecialchars($userinput, ENT_QUOTES | ENT_HTML5);
$Parsedown = new Parsedown();
$text = $Parsedown->text($text);
echo $text;
```

I was getting no `PHP` errors but my page stopped rendering right at this line:
`$text = $Parsedown->text($text);`

I began to debug with trial-and-error, thinking it was a rogue character that was incompatible with *Parsedown*. It was only when I ran a find-and-replace with tabs to spaces that the page ran ok again with the same code.

I confirmed only this string was causing this problem and I could render the page fine with all previous strings used.

Which leads me to think that some combination of tabs were the culprit as the biography was swarming with them (it was a copy and paste from a Word document) and I noticed that many odd spacings were multiple tabs together.

Obviously this isn't conclusive, but I'm afraid it's all I have.

**Comment by aidantwoods** [comment]
> Unfortunately I cannot, both due to privacy for the client (it was a biography) and because the string now has no tabs after being repaired. I'm aware this is pretty unfortunate not to be able to provide a source that actually caused the issue in question.

If you encounter another string that causes the problem, perhaps try and strip it down to the smallest failing example (removing any sensitive data of course!). At present, I'm not really sure how best to proceed – unless you have any idea of other characters in there that might've caused it? I've tried a few whitespace chars alongside standard latin, and slightly odder chars, no crash as of yet:

<img width="822" alt="screen shot 2017-09-01 at 00 11 39" src="https://user-images.githubusercontent.com/3288888/29949123-7d895b26-8eaa-11e7-9a3d-13e07055de45.png">

**Comment by conorhub** [comment]
Yes, I've left this in an unfortunately tricky position to solve. I imagine that it's not good etiquette to close these issues if they're unresolved so I'll comment back should the issue arrise again. Otherwise it may act as a useful starting point should this issue occur to anybody else.

> unless you have any idea of other characters in there that might've caused it?

Replacing all tabs in the string with spaces fixed the problem but I can't see anything unusual in the string. There's a few characters with accents that I believe were created by `htmlspecialchars` as substitutes for displayed characters. There's some more noticeable ones, like a quotation mark and three periods being substituted by `htmlspecialchars` as `ââ¦` (which doesn't display here correctly, due to obvious reasons).

I believe the user copied and pasted the text from a *Word* Document so any formatting that may be converted to plain text in that conversion may also be culprits.

**Comment by aidantwoods** [comment]
There's been a bit of work refactoring the internals over in #685, so I'll close this for now—but please reopen if you have any luck reproducing the issue.
