### ISSUE TITLE
Different result parsedown vs original due to new line

### ISSUE THREAD

**Issue by Snoozerworks** [erusev/parsedown#528]
Hi,
Noticed a difference between the original parser and parsedown. 

This markdown fail because "## Last heading" is not converted

`##&nbsp;First&nbsp;heading
&lt;ul&gt;&lt;li&gt;Hoo
&lt;ul&gt;
&lt;li&gt;Hoo&lt;/li&gt;
&lt;/ul&gt;&lt;/li&gt;
&lt;/ul&gt;

##&nbsp;Last&nbsp;heading`

However,&nbsp;it&nbsp;works&nbsp;if&nbsp;adding&nbsp;a&nbsp;newline&nbsp;after&nbsp;the&nbsp;nested&nbsp;list&nbsp;like&nbsp;this&nbsp;
`##&nbsp;First&nbsp;heading
&lt;ul&gt;&lt;li&gt;Hoo
&lt;ul&gt;
&lt;li&gt;Hoo&lt;/li&gt;
&lt;/ul&gt;
&lt;/li&gt;
&lt;/ul&gt;

##&nbsp;Last&nbsp;heading`

Or&nbsp;removing&nbsp;the&nbsp;newline&nbsp;before&nbsp;the&nbsp;nested&nbsp;list,&nbsp;like&nbsp;this
`##&nbsp;First&nbsp;heading
&lt;ul&gt;&lt;li&gt;Hoo&lt;ul&gt;
&lt;li&gt;Hoo&lt;/li&gt;
&lt;/ul&gt;&lt;/li&gt;
&lt;/ul&gt;

##&nbsp;Last&nbsp;heading`

**Comment by aidantwoods** [comment]
This is fixed in #514 :)

<img width="837" alt="screen shot 2018-03-27 at 13 27 39" src="https://user-images.githubusercontent.com/3288888/37967244-b1814f68-31c2-11e8-8a1e-69fe249e6220.png">
