### ISSUE TITLE
Cross-site scripting vulnerability in ParseDown

### ISSUE THREAD

**Issue by ProDigySML** [erusev/parsedown#530]
```php
<?php

include("parsedown/Parsedown.php");

echo Parsedown::instance()->text('Hello ![google" onerror="alert(1)](http://google.com)'); 
````

The code above simply creates an instance of your Parsedown parser and then creates an image in markdown. This creation of the image is vulnerable to XSS. I would advice something like HTML encoding some of the input in certain places (especially for things like quotes).

**Comment by cebe** [comment]
duplicate of https://github.com/erusev/parsedown/issues/161

**Comment by aidantwoods** [comment]
Fixed in #495 if you’d like to test it.

**Comment by embluk** [comment]
@aidantwoods Can I ask why this has not been merged into master yet, as this XSS vulnerability is quite serious?

**Comment by aidantwoods** [comment]
> Can I ask why this has not been merged into master yet, as this XSS vulnerability is quite serious?

@embluk I'd love to see it merged into master, but unfortunately I don't have write rights on this repo.

If you're a composer user you can take a look at https://packagist.org/packages/aidantwoods/secureparsedown, or https://github.com/aidantwoods/SecureParsedown otherwise to apply the patch via a class extension.

**Comment by embluk** [comment]
@aidantwoods Thanks for all your great work on this!

However, I cannot seem to get it working. I'm pretty sure its nothing on your side and something with the way I'm setting it up.

I have the following:
```
      require_once("scripts/php/Markdown/parsedown.php");
      require_once("scripts/php/Markdown/SecureParsedown.php");

      use Aidantwoods\SecureParsedown\SecureParsedown;

      $parsedown = new SecureParsedown;
      $parsedown->setSafeMode(true);
```
And I get this error: `Parse error: syntax error, unexpected 'use' (T_USE) `

**Comment by aidantwoods** [comment]
From the error it looks like you're perhaps declaring this within a function in the surrounding context?

PHP's `use` is a little weird, and it can have three (thus far) different meanings depending on where it is used.

In the desired case, it is for importing – so you'd need to place the `use` statement outside of any classes and methods ([more info](https://php.net/manual/en/language.namespaces.importing.php))

Alternatively if that's not practical, just instantiate the class by using its fully qualified name, i.e. change `new SecureParsedown;` to `new Aidantwoods\SecureParsedown\SecureParsedown;`

**Comment by embluk** [comment]
Ohh yeah I had my previous code block within a wrapper class, inside a function.

It now works with using the fully qualified name.

Thanks for your rapid response and support! Keep up the good work!

**Comment by erusev** [comment]
It's been a busy couple of months for me, I'll merge it as soon as I have some time to get my head around the code.

**Comment by embluk** [comment]
@aidantwoods I know this is not the right place at all to ask questions, but I could not find I way to contact you.

Just a short one, even though your patch fixes the issues with XSS, I am always still a little concerned with just running it through this parse down class, its nice to use something like HTML Purifier but it messes up the output. Should anyone using this class be running their input through any other filters before hand to remove any XSS attacks? What do you recommend?

**Comment by jamesgraham** [comment]
Anyone using the [`roave/security-advisories`](https://github.com/Roave/SecurityAdvisories/blob/master/composer.json#L42) will be unable to use this package as it's marked unsafe.
