### ISSUE TITLE
blockquote not work on my site

### ISSUE THREAD

**Issue by neecride** [erusev/parsedown#537]
I have a question, the parser works well on the demo when i want to do a `<blockquote> >quote` 

but it does not work on my site.

the parser does not interpret it

and for the tag `<code>` i want to replace it with `<pre>` i use googlePrettify

translated by Google

**Comment by embluk** [comment]
How are you outputting your marked down HTML? Are you just outputting the marked down HTML directly or parsing it through some XSS filter such as HTML Purifier?

**Comment by neecride** [comment]
My form before BDD use `htmlspecialchars($input) ` and return after SQL `<?= $Parsedown->text($user->content); ?>` i not use html purifier

**Comment by embluk** [comment]
Are you using 'htmlspecialchars' before inputting into the database? - If you there is no need to perform this action before inserting into a database, only when outputting?

Maybe the use of 'htmlspecialchars' is affecting the output when using the parser...

**Comment by neecride** [comment]
yes it comes from `htmlspecialchars()` but I can not leave my input without any filter

**Comment by embluk** [comment]
@neecride  Well try it all without the use of `htmlspecialchars` and see if it works as a test, then if it does you have some things to consider.

As of now this parser is vulnerable to an XSS attack if you were to just use not filter for XSS. Read more about it here #495 #536 #497 
So to get around this for now, one of the contributors has released a patch, can be found here: https://github.com/aidantwoods/SecureParsedown

Then after applying the patch I suggest using HTML Purifier http://htmlpurifier.org/ to filter output and only allow HTML which you want to output.

You could use something such as: 
```
$purifierConfig = HTMLPurifier_Config::createDefault();
          $purifierConfig->set('Core.Encoding', 'UTF-8');
          $purifierConfig->set('HTML.Allowed', 'p, a[href|title], blockquote[cite], table[style], thead, tr, th[style], td[style], tbody, pre, code[class|style], hr, em, strong, ul, li, img[src|alt], br, ol, del, h1, h2, h3, h4, h5, h6');
          $Purifier = new HTMLPurifier($purifierConfig);
          $input = $Purifier->purify($input);
```

For applying the patch linked above:
```
require_once("scripts/php/Markdown/parsedown.php");
      require_once("scripts/php/Markdown/SecureParsedown.php");

      $parsedown = new Aidantwoods\SecureParsedown\SecureParsedown;
      $parsedown->setSafeMode(true);
```

**Comment by neecride** [comment]
let's see if I did not go wrong

Include : 

```
require_once ('lib'.DIRECTORY_SEPARATOR.'htmlpurifier'.DIRECTORY_SEPARATOR.'library'.DIRECTORY_SEPARATOR.'HTMLPurifier.auto.php');
require_once ('lib'.DIRECTORY_SEPARATOR.'Parsedown.php');
require_once ('lib'.DIRECTORY_SEPARATOR.'SecureParsedown.php');
```

initialization variables : 

```
//htmlpurifier
$purifierConfig = HTMLPurifier_Config::createDefault();
$purifierConfig->set('Core.Encoding', 'UTF-8');
$purifierConfig->set('HTML.Allowed', 'p, a[href|title], blockquote[cite], table[style], thead, tr, th[style], td[style], tbody, pre, code[class|style], hr, em, strong, ul, li, img[src|alt], br, ol, del, h1, h2, h3, h4, h5, h6');
$Purifier = new HTMLPurifier($purifierConfig);

//parsedown
$parsedown = new Aidantwoods\SecureParsedown\SecureParsedown;
$parsedown->setSafeMode(true);
$Parsedown = new Parsedown();
```
before BDD
Input `$content = $Purifier->purify(trim($_POST['f_topic_content']));` 

After BDD
echo `<?= $Parsedown->text($Purifier->purify($reps->f_topic_reponse)); ?>`

my blockquote `<p>> ce critère que nous proposons une solution avec cet outil qui générant </p>` it does not return the blockquote just that `> text`

**Comment by embluk** [comment]
Because you need to perfrom the purifying after using the parser like:

`<?= $Purifier->purify($Parsedown->text($reps->f_topic_reponse)); ?>`

As you want the parser to produce the output first then finally parse it to HTML Purifier which will guard/ prevent against XSS attacks and only allow HTML you wish to allow...

Also what does BDD stand for?

**Comment by neecride** [comment]
Ok sorry 

BDD = base de donnée 
in English it's database 

So when I insert in database I do not do that ?
`$content = $Purifier->purify(trim($_POST['f_topic_content']));`

**Comment by embluk** [comment]
@neecride Ohh right I thought it was :)

Yeah you only need to ever escape user generated data/ text/ content when you output to the browser, because XSS attacks only happen within the browser and not the database (BDD).

So only ever escape/ filter user content when your about to output anything to the browser or something that will eventually reach the browser, such as the HTML generated from the parsedown.

You could still do the processing or formatting of the user data before going into the database, like you have done there with the `trim()` function but not the filtering for XSS. The formatting of the data can either be done before or after the database.

Hope that makes sense for you.      :)

**Comment by neecride** [comment]
OK thanks for the follow-up !!!

that says the Parsedown works well continue in this way :)

**Comment by aidantwoods** [comment]
> Yeah you only need to ever escape user generated data/ text/ content when you output to the browser, because XSS attacks only happen within the browser and not the database (BDD).

I'd second that. Also for reasons of recovering from missing doing escaping somewhere – if you miss escaping on input somewhere in your app then you would need to fix it, as well as track down all input that was stored in the database and not correctly escaped. Whereas if you miss escaping on output, you only need to fix where escaping wasn't applied.

---

Also, you shouldn't need to use *both* the purifier and safe mode – but hey it can't hurt ;-)

One thing to note is that generally speaking, **currently** safe mode should be stricter than HTML purifier – as in, it looks like you permit things like user written tables etc... with the purifier. Safe mode will only allow tables that are expressed in markdown syntax, but won't permit manually pure HTML written tables. And the same applies for other HTML elements.

**Comment by neecride** [comment]
@aidantwoods 
thank you for the clarification 👍

**Comment by embluk** [comment]
> Also, you shouldn't need to use both the purifier and safe mode – but hey it can't hurt ;-)

Yes it could be a little overkill but for me it was an added extra step to make sure only what the parsedown should generate gets out, and from my testing it did stop the XSS issue running it through the purifier before your patch. But running your patch as well as HTML Purifier makes me feel safer :)

I guess I overlooked the HTML Purifier allowing pure HTML tables being written ;D

**Comment by embluk** [comment]
Could this issue be closed as I think OP's problem was solved?

**Comment by neecride** [comment]
Yes you can close this topic
