### ISSUE TITLE
More Maintainers

### ISSUE THREAD

**Issue by bkuhl** [erusev/parsedown#543]
@erusev you've done a great job building this tool.  4.5k+ stars is quite an achievement.  It can be very time consuming contributing/maintaining open source I know.  With 55 open PRs there's quite a backlog of reviews, quality control, etc.  Have you considered granting some additional rights to other developers who have contributed to this project before to keep it moving forward?

**Comment by karllhughes** [comment]
Duplicate? https://github.com/erusev/parsedown/issues/516

**Comment by erusev** [comment]
@bkuhl I've been working on 2.0 and it has a different, more modular architecture, it should make it easier for people to contribute and easier for me to merge PRs.

**Comment by bkuhl** [comment]
Very cool, sounds great!
