### ISSUE TITLE
Problem with &

### ISSUE THREAD

**Issue by avlysenko** [erusev/parsedown#547]
Hi!

Text in:

<pre>
.header
===

Очередной кавер «Клевого микрофона»

.body
===

wed wed & w we
 
# Очередной кавер «Клевого микрофона»
</pre>

Text out:
<pre>
.header
Очередной кавер «Клевого микрофона»

.body
wed wed
</pre>

What could be the problem?

**Comment by avlysenko** [comment]
Understood. Our problem

**Comment by sebazza** [comment]
``
```
wjefwenrfnew
eqrfjierwfmeq
[erfiqefrq](url)
```
[[]()]( #url)

1. yuo

- njnniom

- nununu


`lmkgmtkgt`
```
rtogomrtg
igmrt]
tg]rgnrt
```

o44okr4
======

# r4mro4mr4

#122
