### ISSUE TITLE
[Question] Is it possible to ignore certain items such as headers?

### ISSUE THREAD

**Issue by bkuhl** [erusev/parsedown#550]
I'm using this library to mimic functionality of another site, but it's parsing headers, which this other site doesn't support.  So I'd like to be able to disable the parsing of headers.  Is this possible?

**Comment by Mecit** [comment]
This is explained [here](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions#disable-element).

**Comment by aidantwoods** [comment]
Closing as I think the question was answered?
