### ISSUE TITLE
Only # in text parsedown generate a error 

### ISSUE THREAD

**Issue by 20pro** [erusev/parsedown#552]
Hi all,
when i write a text with only '#' caracter i have an error with PhP 7.2 ("Argument 1 passed to Parsedown::element() must be of the type array, null given, called in /var/www/www/application/vendor/erusev/parsedown/Parsedown.php on line 271") 

Is a new version planned for php 7.2 ?

**Comment by aidantwoods** [comment]
Could you give an example of some text that produces this error? Just including a `#` doesn't seem to replicate on php 7.2 on my end.

**Comment by 20pro** [comment]
yes, i solved it

**Comment by aidantwoods** [comment]
What ended up being the issue? If this is a bug in Parsedown it would be good to solve it :)
