### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by aidantwoods** [erusev/parsedown#553]
As of right now there are 126 open issues, and 57 open pull requests for the library. That number only seems to be going upwards.

I've selected (so far) 6 pull requests (and there will no doubt be more) that are either in major need of merging, or are simple bugfixes, or sensible changes that should have probably been merged a while ago, or just closed if they are not desired.

My hope is that the selection can be merged into this repo in a single shot (we can reference everything that should be closed in this single PR and GitHub should close everything relevant automatically).

@erusev I know you've mentioned Parsedown 2.0 a few times, while that would be great for drawing a line and making improvements that require BC breaks, IMO there are some issues that that will not solve – namely, things like XSS issues *should* still be fixed in `1.x`. It also seems a shame to waste the work that some have done towards fixing bugs in `1.x` when it's just a case of merging the changes.

@erusev I also know you're quite busy – which is why I am applying the above criteria to try and minimise the review effort: (major need of merging, or simple bugfixes/sensible small changes).

So far, this list mainly includes a subset of my own pull requests (they're easier for me to look at quickly), but if @erusev is happy with the goal of identifying and merging finished bugfixes and sensible small changes than I can look through some more PRs (this would require a bit more effort than just looking back at ones I've made – hence this initial list). Additionally, if there is a desire to merge this list then perhaps those who have opened pull requests would be happy to update them for current `master` where merge conflicts exist.

---

I have created a [new fork of parsedown](https://github.com/aidanwoods/parsedown), and am creating pull requests using the original commits from the respective PRs to this main repo. If anyone would like to help with this effort then I can add you as a maintainer. Or feel free to just target PRs and I will merge them and update this list.

---

This list so far is as follows, (all changes can be found on [the pull-request page on the fork](https://github.com/aidanwoods/parsedown/pulls?utf8=%E2%9C%93&q=is%3Apr)):

### #495: Prevent various XSS attacks by @aidantwoods
Merging this should close the following: #161, #497, #276, #403, #530, #495.

### #545: Test against PHP 7.2 by @carusogabriel
Merging this should close the following: #545.

### #475: Loose lists by @aidantwoods
Merging this should close the following: #474, #529, #551, #427, #475.

### #423: Fix CommonMark test by @PhrozenByte
Merging this should close the following: #423

### #433: Preventing double nested links by @aidantwoods
Merging this should close the following: #358, #487, #432, #417, #504, #433

### #525: Properly support fenced code block infostring by @aidantwoods
Merging this should close the following: #524, #525

---

This collation of 6 pull requests, when merged, should allow the closing of (at least) 21 issues and pull requests.

**Comment by aidantwoods** [comment]
I've sent some previous contributors invites to https://github.com/aidanwoods/parsedown in hope that we can get some new development going right away. This perhaps can permit some changes and bug fixes to happen, with the hope that any work done there can be merged back into this repo eventually. @erusev I've also sent you an invite, given that the intent is for the changes to end up back here, it would be good to keep you involved.

If anyone else that wants to help, let me know.

**Comment by aidantwoods** [comment]
So far I've gone through the issues page and attempted to categorise all the bugs, as well as trying to determine which require additional attention.

This list is in https://github.com/aidanwoods/parsedown/issues/10

**Comment by erusev** [comment]
@aidantwoods 

Awesome work as always. I made you a contributor. You'll be able to push without my permission. You've been a great contributor and I trust you completely.

**Comment by aidantwoods** [comment]
@erusev thank you ❤️

Are you happy for me to merge in everything listed above?

**Comment by erusev** [comment]
Sure, all of these look good.

**Comment by PhrozenByte** [comment]
Thank you @erusev  for adding @aidantwoods, excellent choice, the project made a huge leap forward in just a few hours! Thank you! :heart: 

There's just one small wish left: Can you please add @aidantwoods (if he agrees, what do you say?) to [`erusev/parsedown-extra`](https://github.com/erusev/parsedown-extra), too? There are many bugfixes awaiting review, many of them can be merged virtually immediately. :smiley:

**Comment by erusev** [comment]
@PhrozenByte Done.
