### ISSUE TITLE
Package blacklisted on roave/security-advisories

### ISSUE THREAD

**Issue by simonschaufi** [erusev/parsedown#555]
https://github.com/Roave/SecurityAdvisories is a repository to block packages which are insecure. The version constraint of this package is: `"erusev/parsedown": "<=1.6.4",`, so it is not possible to install this package with security-advisories active. Whats the reason for the insecurity? I didn't see any commits about it.

**Comment by prisis** [comment]
Hey
https://github.com/erusev/parsedown/search?q=xss&type=Issues&utf8=%E2%9C%93

**Comment by aidantwoods** [comment]
If you up your composer version to `"erusev/parsedown": "^1.7.0"`, or even just run `composer update` this should now be resolved :)
