### ISSUE TITLE
Remove <p>

### ISSUE THREAD

**Issue by NightYoshi370** [erusev/parsedown#562]
I want to remove the line breaks on my local version. How do I do so?

**Comment by NightYoshi370** [comment]
Whoops, I mean <p>

**Comment by mohnjatthews** [comment]
Do you have an example that could help explain what you're trying to do?

**Comment by cebe** [comment]
the following should parse only inline markdown:

```php
$Parsedown = new Parsedown();
echo $Parsedown->line('Hello _Parsedown_!');
```

could be added to the README here: https://github.com/erusev/parsedown#example

**Comment by NightYoshi370** [comment]
Oh hey! the line thing worked. Thanks!
