### ISSUE TITLE
Restore pre-1.7.0 escaping behavior for fenced code blocks

### ISSUE THREAD

**Issue by JonasDoebertin** [erusev/parsedown#568]
In a project I have created a custom extension of the `Parsedown` class that overrides the `Parsedown::blockFencedCodeComplete()` method to add "compile time" syntax highlighting to fenced code blocks. This worked pretty well in 1.6.4 and earlier releases.

Since the element text that is created contains HTML (to apply the classes for the syntax highlighting), I intentionally left out the call to `htmlspecialchars()` in my overridden method. This is the resulting markup for an example fenced code block:

```html
<pre><code><span class="hljs-comment">// baz.php</span>

<span class="hljs-meta">&lt;?php</span>

$foo = <span class="hljs-string">"bar"</span>;</code></pre>
```

With the 1.7.0 release though this broke because now the call to `htmlspecialchars()` doesn't seem to happen in the single element methods but rather in `Parsedown::element()` where every element is passed through. This is the markup I get now:

```html
<pre><code>&lt;span class="hljs-comment"&gt;// baz.php&lt;/span&gt;

&lt;span class="hljs-meta"&gt;&amp;lt;?php&lt;/span&gt;

$foo = &lt;span class="hljs-string"&gt;"bar"&lt;/span&gt;;</code></pre>
```

My question is: with the latest changes, is there a way to restore the previous behavior? Don't get me wrong, I know sanitation is a serious topic and I think the changes are the right way to go. I just want to disable them for fenced code block in a project where I have complete control over the markdown passed through Parsedown.

**Comment by aidantwoods** [comment]
You should be able to create HTML using the same method that Parsedown does, i.e. by modifying `$Block` that your function receives as an argument.
The escaping changes only ensure that the intended HTML structure is preserved when outputting (i.e. context borders aren't crossed). For example, if your write something into an attribute, it shouldn't leak out into the DOM because it contains quotes.

This shouldn't prevent you doing anything however, if you want a different HTML structure then simply write a different one to `$Block` and return it :) the changes only ensure that you represent your HTML as an array, rather than directly outputting it into a string.

**Comment by aidantwoods** [comment]
There would have been one restriction with using the array structure compared to HTML-as-a-string representation, in that in the current release elements would not be permitted to lie adjacent to text (it looks like you would want to use this based on your example).

I've just merged #511 which removes this restriction :)

**Comment by JonasDoebertin** [comment]
My current code looks like this (simplified, there's additional checks and error handling in place):

```php
protected function blockFencedCodeComplete($block)
{
    $language = array_get($block, 'element.text.attributes.class', '');
    $code = array_get($block, 'element.text.text', '');

    $code = $this->highlighter->highlight($language, $code)->value;

    array_set($block, 'element.text.text', $code);
}
```

Where `$this->highlighter->highlight($language, $code)->value` takes the code blocks content as a string and returns the finished markup as a string.

Now, instead of just setting `block.element.text.text` I would need to inject the finished markup in the same array structure that Parsedoen uses?

**Comment by aidantwoods** [comment]
Does your highlighter give you any representation of the highlighted text other than as a string value?

**Comment by JonasDoebertin** [comment]
The highlighter is [highlight.php](https://github.com/scrivo/highlight.php) a port of highlight.js. 

Unfortunately, it just returns the result as a single string value.

**Comment by PhrozenByte** [comment]
@aidantwoods: I don't think that it would be desirable to create a Parsedown AST representation of the highlighter's result. I guess the only solution here is to introduce a separate `trustedText` key that isn't escaped, and putting the extension's developer in charge to make the contents safe.

**Comment by aidantwoods** [comment]
Yeah, I was thinking the same thing too – I hadn't previously considered that extensions might use external parsers (and thus not really have a good way of knowing the structure of what was produced). I'll put together a PR, brb :)

**Comment by aidantwoods** [comment]
Check out #569 for the changes.

As kind of intended for this sort of thing – if a user of your extension enables safe mode then the unsafe behaviour goes away (which kind of acts to enforce that the user of the extension and the author agree on the trustworthiness of input).

**Comment by aidantwoods** [comment]
@JonasDoebertin you can take a look at https://github.com/erusev/parsedown/pull/569/files#diff-02ec1fcc68993c0203f25e1b4ae8af44 for the test examples. Essentially what you want to do is:

* copy the value of and unset the `'text'` key from the element
* put the output of your highlighter into a new key `'rawHtml'` instead. 
* if you're confident that the highlighter you're using is capable of handling user input safely, then additionally set the  `'allowRawHtmlInSafeMode'` key to true. Though if you're not going to be using safe mode then leaving it as is would also work (if safe mode is ever enabled the rawHtml will be escaped unless it's explicitly marked as safe via setting that key).

**Comment by JonasDoebertin** [comment]
Thanks for your quick solution!

Do you know when you'll tag a release with this changes?

**Comment by aidantwoods** [comment]
Planning to release this as part of 1.8, in-which I'd like to include the handler changes from #576. So once that's done I'll tag a new feature release with this as part of it :)
