### ISSUE TITLE
Conflict with custom BBCode parser

### ISSUE THREAD

**Issue by NightYoshi370** [erusev/parsedown#572]
Hello again. I'm NightYoshi370, and I do have another bug with this.

So I do have this own custom PHP BBCode parser that I run alongside this, but there is a problem: the URL BBCode tag (paired up with parsedown) is completely broken. I'll show you an example

> [url]https://mariomods.net/[/url]
> [url=https://mariomods.net/]hoi[/url]

Should produce the following:

> <a href="https://mariomods.net/">https://mariomods.net/</a>
> <a href="https://mariomods.net/">hoi</a>

Actual result differs though.

> <a href="&lt;a href=&quot;https://mariomods.net/[/url&quot;&gt;https://mariomods.net/&lt;/a&gt;"></a> <a href="https://mariomods.net/[/url">https://mariomods.net/</a>

The second link just repeats the word hoi

> <a href="&lt;a href=&quot;https://mariomods.net/">hoi</a>hoi.

Any way I could patch this without having to remove my BBCode parser?

**Comment by NightYoshi370** [comment]
Actually, github just messes up the formatting, so I'll just shove everything into a .txt files.
[new 2.txt](https://github.com/erusev/parsedown/files/1823031/new.2.txt)

**Comment by NightYoshi370** [comment]
Whoops, NVM. I'm an idiot, who forgot to read the wiki.

**Comment by aidantwoods** [comment]
In this case you could do something like `$parsedown->setUrlsLinked(false);` to disable autolinking.

Though, in general BBCode and markdown syntax might not be compatible together.

Both results you're trying to achieve here in BBCode could be achieved with pure markdown too :)

```markdown
https://mariomods.net/
[hoi](https://mariomods.net/)
```

**Comment by NightYoshi370** [comment]
Yeah, I realised. Just that my board members love BBCode more than Markdown, but we like having markdown on the wiki.

Also, uh, another thing I've realised:

> Posted by &quot;DestroyerXL44&quot; id=&quot;3297&quot;

I've tried `->setMarkupEscaped(false)`, but it didn't fix that.

For reference, below is my configuration:
```php
	$text = Parsedown::instance()
		->setUrlsLinked(false)		# prevents automatic linking of URLs
		->setMarkupEscaped(false)
		->line($text);
```

**Comment by NightYoshi370** [comment]
Edited above post: Now shows that setSafeMode(true) also doesn't work.

**Comment by aidantwoods** [comment]
Could you open this as a separate issue? :) I'll make a PR with a fix for this in a few mins

**Comment by NightYoshi370** [comment]
Sure
