### ISSUE TITLE
List indentation problem

### ISSUE THREAD

**Issue by ozgrozer** [erusev/parsedown#581]
When I use something like this in GitHub,

```
- level 1
  - level 2
    - level 3
      - level 4
        - level 5
```

I get this view.

- level 1
  - level 2
    - level 3
      - level 4
        - level 5

But in the Parsedown, I get this one.

![screen shot 2018-03-27 at 9 33 02 am](https://user-images.githubusercontent.com/651938/37950609-e409fa3c-31a1-11e8-87ed-1ad8adf31025.jpg)

Is there any feature to set the space amount?

**Comment by aidantwoods** [comment]
So it looks like @PhrozenByte and I actually fixed this a while ago in #439, but it never got merged. It's now merged and you'll see the fix in the next version :)

I've added your input here as a test case too to make sure: https://github.com/erusev/parsedown/pull/439/commits/f594d4c18b686294ccc3e162ba0eb84c4b45fb3b
