### ISSUE TITLE
Emit Markdown

### ISSUE THREAD

**Issue by westy92** [erusev/parsedown#585]
Use case:

I have a custom extension that doctors URLs:
```php
class MyParsedown extends Parsedown
{
   protected function inlineLink($excerpt)
   {
      $link = parent::inlineLink($excerpt);
      $link['element']['attributes']['href'] = Util::expandAndDoctorUrl($link['element']['attributes']['href']);
      return $link;
   }
}
```

I want to parse the Markdown using Parsedown, doctor the URLs (transform relative links to full paths, add query parameters to certain domains for referrals, etc.), and the re-emit Markdown.

The Markdown would then be sent over the wire to another device for a platform-specific rendering.

Example input:
```
Test [link](/path?query=param).
```

Example output:
```
Test [link](https://domain.com/path?query=param).
```

Is something like this possible?

**Comment by aidantwoods** [comment]
Your implementation looks good. Is the query whether implementing the `Util::expandAndDoctorUrl` function is possible?

[`parse_url`](http://php.net/manual/en/function.parse-url.php) might help?

**Comment by westy92** [comment]
I already have that function implemented and working.

The inquiry is whether this library could parse and validate the Markdown, and the re-emit the validated and doctored Markdown.

The example input and output would be what is passed into and the emitted by Parsedown.

**Comment by aidantwoods** [comment]
Ah I see what you mean.

You could try disabling all the blocks and inlines apart from `inlineLink`, but have that output the desired markdown instead of HTML?

**Comment by aidantwoods** [comment]
You can output text only by unsetting the `name` key of the element, and writing the desired text (output markdown) into the `text` key. I think that outputting text isn't in the latest release, but is in current master if you wanted to use that. Otherwise it'll be in the next release.

**Comment by aidantwoods** [comment]
Just overload the other blocks and inlines with a function that is just `return null;` to disable them

**Comment by westy92** [comment]
Thanks for being super responsive! I'm extremely close.
I am using the latest master commit.

```php
class ReemitParsedown extends Parsedown
{

   // TODO generate dynamically
   protected function blockCode($Line, $Block = null) { return; }
   protected function blockCodeContinue($Line, $Block) { return; }
   protected function blockCodeComplete($Block) { return; }
   protected function blockComment($Line) { return; }
   protected function blockCommentContinue($Line, array $Block) { return; }
   protected function blockFencedCode($Line) { return; }
   protected function blockFencedCodeContinue($Line, $Block) { return; }
   protected function blockFencedCodeComplete($Block) { return; }
   protected function blockHeader($Line) { return; }
   protected function blockList($Line) { return; }
   protected function blockListContinue($Line, array $Block) { return; }
   protected function blockListComplete(array $Block) { return; }
   protected function blockQuote($Line) { return; }
   protected function blockQuoteContinue($Line, array $Block) { return; }
   protected function blockRule($Line) { return; }
   protected function blockSetextHeader($Line, array $Block = null) { return; }
   protected function blockMarkup($Line) { return; }
   protected function blockMarkupContinue($Line, array $Block) { return; }
   protected function blockReference($Line) { return; }
   protected function blockTable($Line, array $Block = null) { return; }
   protected function blockTableContinue($Line, array $Block) { return; }
   protected function inlineCode($Excerpt) { return; }
   protected function inlineEmailTag($Excerpt) { return; }
   protected function inlineEmphasis($Excerpt) { return; }
   protected function inlineEscapeSequence($Excerpt) { return; }
   protected function inlineImage($Excerpt) { return; }
   protected function inlineMarkup($Excerpt) { return; }
   protected function inlineSpecialCharacter($Excerpt) { return; }
   protected function inlineStrikethrough($Excerpt) { return; }
   protected function inlineUrl($Excerpt) { return; }
   protected function inlineUrlTag($Excerpt) { return; }

   protected function inlineLink($excerpt)
   {
      $link = parent::inlineLink($excerpt);
      unset($link['element']['name']);
      $link['element']['text'] = '[' . $link['element']['text'] . '](' . Util::expandAndDoctorUrl($link['element']['attributes']['href']) . ')';
      print_r($link);
      return $link;
   }

}
```

`print_r($link)` output:
```
Array
(
    [extent] => 43
    [element] => Array
        (
            [handler] => line
            [nonNestables] => Array
                (
                    [0] => Url
                    [1] => Link
                )

            [text] => [complex](https://tester.domains.com/this/is.php?the=path&right=here)
            [attributes] => Array
                (
                    [href] => /this/is.php?the=path&right=here
                    [title] => 
                )

        )

)
```

Actual output:
```
[complex](https://tester.domains.com/this/is.php?the=path&amp;right=here)
```

Expected output:
```
[complex](https://tester.domains.com/this/is.php?the=path&right=here)
```

Notice `&amp;` vs. `&`.

**Comment by westy92** [comment]
After inspecting the Parsedown source, I got it to work with these modifications. Is this the best way to achieve this?
```php
   protected function inlineLink($excerpt)
   {
      $link = parent::inlineLink($excerpt);
      $link['element']['rawHtml'] = '[' . $link['element']['text'] . '](' . Util::expandAndDoctorUrl($link['element']['attributes']['href']) . ')';
      unset($link['element']['name']);
      unset($link['element']['text']);
      unset($link['element']['handler']);
      print_r($link);
      return $link;
   }
```

**Comment by aidantwoods** [comment]
Yes, this is probably the best way to do this :)

Btw, you should be able to omit overloading `*Continue` and `*Complete`, since these won't be called if the original method (without these postfixes) returns null

**Comment by westy92** [comment]
I was getting an error with the text: `This [isn't] a link!`

```
Undefined index: extent

vendor/erusev/parsedown/Parsedown.php:1202
vendor/erusev/parsedown/Parsedown.php:1131
```

I fixed it by wrapping my code in an `isset()` check:

```php

   protected function inlineLink($excerpt)
   {
      $link = parent::inlineLink($excerpt);
      // https://github.com/erusev/parsedown/issues/585
      if (isset($link['element']['handler']['argument'])) {
         $linkText = $link['element']['handler']['argument'];
         $linkLocation = Util::expandAndDoctorUrl($link['element']['attributes']['href']);
         $link['element']['rawHtml'] = "[$linkText]($linkLocation)";
         unset($link['element']['name']);
         unset($link['element']['handler']);
      }
      return $link;
   }
```

**Comment by aidantwoods** [comment]
Yes I think if `$link` were ever null, then `$link['element']['rawHtml'] = ...` would convert it to an array with those indices, but then `$link` would end up being returned without the `extent` key set (which is expected by the line method that calls it).

I'm hoping errors like these can be avoided completely when #685, since it'll require the source to pass static type checks to force things like this to be dealt with without assuming structure. It'll also make implementing something like you've done here (where you remove all the blocks and inlines and use your own custom one) substantially easier :)
