### ISSUE TITLE
extending inline image causing all server memory to be consumed

### ISSUE THREAD

**Issue by runrevben** [erusev/parsedown#613]
```
private $baseImagePath = 'http://cdn.example.com/';

    protected function inlineImage($excerpt)
    {
        $image = parent::inlineImage($excerpt);

        $image['element']['attributes']['src'] = $this->baseImagePath . $image['element']['attributes']['src'];

        return $image;
    }
```

This is the example code from the site. I've created a class extending parsedown with the above code. It's consuming all php memory on the server until it throws a:

```Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /srv/xxxxxx/includes/Parsedown.php on line 1828```

I upped the php memory limit to 1024mb as a test and it still consumed it. Any thoughts?

I've tried with parsdown v17 and the latest.

Seems to be tripping out in the pregReplaceElements function.

**Comment by aidantwoods** [comment]
Is there a particular input you could give that causes this?

**Comment by runrevben** [comment]
Thanks, I'm just looking now. I've been able to run one file through it successfully.. so let me run each file until I find the offending article. I'll post back shortly. Must be a specific URL that is causing issue.

**Comment by runrevben** [comment]
OK, so here is the offending file:

https://raw.githubusercontent.com/livecode/livecode/9.0.0/docs/guides/HTML5%20Deployment.md

It doesn't have any images, but it does have an ! mark at the end of a line roughly half way down the document. Removing that ! allows the doc to parse correctly. As I understand it, markdown doesn't require special characters to be escaped. Additionally, it parses fine as long as I'm next extending ```inlineImage```.

**Comment by aidantwoods** [comment]
This reminds me a little of https://github.com/erusev/parsedown/issues/546, if you check for `$image` being `null` and return early does this have any affect (as described in https://github.com/erusev/parsedown/issues/546#issuecomment-351102485)?

Otherwise I'll try debug this later today :)

**Comment by runrevben** [comment]
Hey, that's perfect. That worked.. and it makes sense why it works too.

**Comment by aidantwoods** [comment]
Awesome, feel free to update the Wiki with the bugfix too :) (I've just noticed that's where this example is coming from!) otherwise I'll fix it later when not on mobile.

**Comment by runrevben** [comment]
Thanks. Added fix to https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions

**Comment by aidantwoods** [comment]
Thanks! 🎉
