### ISSUE TITLE
best way to wrap pre-element with div and classes

### ISSUE THREAD

**Issue by Regna91** [erusev/parsedown#622]
Hi
I want to wrap the `pre`-Element with an div. How can i do this?
thanks in advance
Here an example
```
{columns}

{col}
fooo
{/col}

{col}
fooo
{/col}
{/columns}

**Comment by aidantwoods** [comment]
You could get something similar by writing:
```markdown
Header     | Header
---------- | ----------
`Col 1`    | `Col 2`
**Footer** | **Footer**
```

To give:
```html
<table>
<thead>
<tr>
<th>Header</th>
<th>Header</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>Col 1</code></td>
<td><code>Col 2</code></td>
</tr>
<tr>
<td><strong>Footer</strong></td>
<td><strong>Footer</strong></td>
</tr></tbody></table>
```

Which is rendered as:

Header     | Header
---------- | ----------
`Col 1`    | `Col 2`
**Footer** | **Footer**

---

If you want the exact result you described you'd need to write an extension to parse this custom table style. It might help to look at how the table demonstrated above is [currently implemented](https://github.com/erusev/parsedown/blob/1f69f7e69797104e73fdceaae22a4b4e3978f0a4/Parsedown.php#L872), but you'd need to write some custom logic to interpret it in the way you're wanting.

There's some information about writing extensions here: https://github.com/erusev/parsedown/issues/625#issuecomment-386809430
