### ISSUE TITLE
Line breaks with ParsedownExtra

### ISSUE THREAD

**Issue by janstieler** [erusev/parsedown#626]
Hi,

I want to use ParsedownExtra with linebreaks but if I set the paramter 
```$Parsedown = new ParsedownExtra();
 $Parsedown->set_breaks_enabled(true);```
I will get an error:
`Fatal error:  Uncaught Error: Call to undefined method ParsedownExtra::set_breaks_enabled() in …`

How can I enable line breaks with ParsedownExtra?

Best

**Comment by aidantwoods** [comment]
The method name in your code should be `setBreaksEnabled` (camel case), not `set_breaks_enabled` (snake case) :)

For future reference, ParsedownExtra has its own issue tracker: https://github.com/erusev/parsedown-extra/issues – this repo is for Parsedown :)

**Comment by janstieler** [comment]
Thank you very much.
And sorry for the wrong repo.
