### ISSUE TITLE
make internal links with this library

### ISSUE THREAD

**Issue by MahdiPishguy** [erusev/parsedown#633]
after installing erusev/parsedown library package i want to make internal links with `Markdowns` like with this code:

    $Parsedown = new Parsedown();
    echo $Parsedown->text("* [Hello](#hello)  
                                * [Hello World](#hello-world)
                                * [Another section](#new-section)
                                
                                ## Hello
                                ### Hello World
                                ## New section");

in this code i expect `## New section` must be have `id`, but after show this markdown this part of text doesn't have any `id` to make simple internal link

**Comment by tovic** [comment]
Try `ParsedownExtra` extension then do this:

~~~ .markdown
### New Section {#new-section}
~~~

**Comment by aidantwoods** [comment]
Headers being given IDs while useful in some contexts (e.g. a `*.md` file as rendered by GitHub), isn't desirable in others (e.g. a comment as rendered by GitHub). The default (by spec) is not to have these, but the option is there to have them via an extension as @tovic has mentioned :) (see also: [how would we make the ID a useful format for everyone?](https://github.com/erusev/parsedown/issues/306#issuecomment-377683857) – not having it by default is a decent way of avoiding having to make a choice on someones behalf).
