### ISSUE TITLE
Use PHP Variables when uploading Parsedown?

### ISSUE THREAD

**Issue by WillWammer** [erusev/parsedown#635]
For instance, I'm trying to do:

`echo $parsedown->text('<div class="flol"><h1>' . $row[0] . '</h1>
    <br>
    <h3>By: ',
    $row[1], '<br><br><img height="600" width="800" src="', $row[2], '"><br><br><br><h3>"', $row[3], '</h3>');`

How would I do this?

**Comment by aidantwoods** [comment]
`->text` accepts a single string in markdown, so I think you could achieve what it looks like you're trying to do by changing the `,`s to `.`s?
