### ISSUE TITLE
image scale

### ISSUE THREAD

**Issue by ebal** [erusev/parsedown#637]
Hi, 
I was wondering if there is a way to scale / resize an image with **parsedown**? 
It seems that the most common way is something like this:

    ![alt(/home/ebal/img/image.png =250x250)

thanks in advance,

**Comment by aidantwoods** [comment]
There isn't currently a "markdown sanctioned" way to do this other than to use HTML to create the image directly (though if using safe-mode is important, then there isn't really a way to do this unfortunately).
