### ISSUE TITLE
Add Multi-Line Element (Documentation)

### ISSUE THREAD

**Issue by fabswt** [erusev/parsedown#639]
Using the sample code from the documentation about [adding multi-line elements](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions#add-multi-line-element).

The following Markdown code:

```
**
oh

ah

[text](http://example.com)

{aaa}(ooo)
**
```

will cause an `Undefined index: text` notice in PHP, referring to line:

        $block['element']['text'] .= "\n" . $line['body'];

This occurs in both 1.8.0-beta-4 but also in older versions (e.g.: 1.6.0.)

**Comment by aidantwoods** [comment]
It looks like the Wiki was just doing the wrong thing there, I'm surprised it's gone unnoticed for so long 🤷‍♂️ .
Here's the [diff](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions/_compare/75a879e20b11a16644589a68a9924650dc6e92b7...c340933181afd0aaa14851e657af9846faeaa3e6) of the correction so you can fix what you copied.

Thanks for pointing this out :)
