### ISSUE TITLE
Created a new extension to Parsedown / ParsedownExtra

### ISSUE THREAD

**Issue by BenjaminHoegh** [erusev/parsedown#643]
I have created a new extension there contain a lot of the requested features called [ParsedownExtreme][1]

**Its require:**
- Parsedown - 1.8.0-beta-4
- ParsedoenExtra - 0.8.0-beta-1

there are no knowing bugs at the moment but will update it and optimize it

[1]: https://github.com/BenjaminHoegh/parsedown-extreme

**Comment by aidantwoods** [comment]
Feel free to add this to the list over at https://github.com/erusev/parsedown/wiki/Extensions-and-Related-Libraries, I'll close this for now since it's not really an "issue" :)
