### ISSUE TITLE
How to add anchor to Header h1,h2...h4

### ISSUE THREAD

**Issue by engharb** [erusev/parsedown#659]
Hello,

is it possible to add anchor to headers i.e add ID for header? I have tried that in several ways but no success.

Example 
www.abc.com#My_header_1 
#  header text here # {#anchorName} // but this does not work

**Comment by pbuttelli** [comment]
Sorry for reviving this topic, but I have a question: is there any way, up to the date, to add anchors to headers without using any extra library?
Thanks in advance!
