### ISSUE TITLE
Hashtag mistakenly seen as headers

### ISSUE THREAD

**Issue by giuntim** [erusev/parsedown#666]
Parsedown translates hashtags like the following to h1:
#php 

But I think this is wrong. Titles should have a space between \# and the words:

# title
#tag 

PS: thx for your work! I really like the way you implemented everything in a simple to use class.

**Comment by giuntim** [comment]
Ops! Just realized that setting strict mode to true fixed my problem. :-)
Maybe you can add it to the docs?

**Comment by aidantwoods** [comment]
When strict mode is put in a release version it'll be documented :)
