### ISSUE TITLE
how to show formula in html using paserdown

### ISSUE THREAD

**Issue by allen-2014** [erusev/parsedown#683]

**Comment by aidantwoods** [comment]
What kind of formula?

**Comment by allen-2014** [comment]
math formula, and I'v used the sub-class to solve the problem, the beta version, thanks!






At 2019-02-22 23:58:44, "Aidan Woods" <notifications@github.com> wrote:


What kind of formula?

**Comment by BenjaminHoegh** [comment]
For math formular I will recommend that you use KaTeX together with parsedown

**Comment by allen-2014** [comment]
Yes.perhaps adding some codes related to katex to parsedown  class is better, just advice








At 2019-02-24 06:16:23, "Benjamin Høegh" <notifications@github.com> wrote:


For math formular I will recommend that you use KaTeX together with parsedown
