### ISSUE TITLE
TOC support

### ISSUE THREAD

**Issue by isecret** [erusev/parsedown#688]
Hi, Do you plan to add new features? I think it's really cool. I mean to support TOC.

**Comment by aidantwoods** [comment]
TOC: "Table of contents"?

**Comment by tristar500** [comment]
Like this 

[Introduction](#introduction)

**Comment by BenjaminHoegh** [comment]
I will upload a toc extention later today

**Comment by isecret** [comment]
@BenjaminHoegh That's great!

**Comment by BenjaminHoegh** [comment]
@isecret [parsedown-toc](https://github.com/BenjaminHoegh/parsedown-toc)
