### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by lrf141** [erusev/parsedown#692]
I wanna use "parsedown" supported to PHP 7.3.
Is there a plan there?

**Comment by BenjaminHoegh** [comment]
It should work on PHP 7.3. Do you have any issues?

**Comment by lrf141** [comment]
Thank you for your reply!
I think that this point should be specified in the README.

**Comment by JohJohan** [comment]
+1 readme says it supports php7.2 while composer saying `>5.3.0`
