### ISSUE TITLE
Change <del> to <s>

### ISSUE THREAD

**Issue by BenjaminHoegh** [erusev/parsedown#695]
I'm not sure you use the right option for strikethrough but this can off cause be personal but try to [read this article](1)

> - The \<del> element represents a removal from the document.
> - The \<s> represents contents that are no longer accurate or no longer relevant.
>
> That is to say that they actually represent different things semantically. Specifically \<del> would be used if you had an existing document and wanted to indicate text that was in the document, but has been removed. This would be different than text in a document that is no longer accurate, but that has not been removed (you could use \<s> for that).

[1]: https://stackoverflow.com/questions/16743581/what-is-the-difference-between-s-and-del-in-html-and-do-they-affect-website

**Comment by aidantwoods** [comment]
Reasoning for the current behaviour is to match the GFM spec: https://github.github.com/gfm/#strikethrough-extension-
