### ISSUE TITLE
It can't parse scientific formula...

### ISSUE THREAD

**Issue by luvvien** [erusev/parsedown#697]
It is a good parser, I hope it can also support scientific formula.

**Comment by BenjaminHoegh** [comment]
are you talking about Latex ?

**Comment by luvvien** [comment]
Yes😀

**Comment by BenjaminHoegh** [comment]
> Yes😀
> […](#)

I have made a extension there add support for this, if you got any issue let me know :)
[ParsedownLatex](https://github.com/BenjaminHoegh/parsedown-latex/tree/master)

**Comment by luvvien** [comment]
Thanks for your reply. It is so helpful to me.

**Comment by luvvien** [comment]
Moreover, if I want to add 'rel=nofollow' in href, how to do it. Can it
support amp.

**Comment by BenjaminHoegh** [comment]
> Moreover, if I want to add 'rel=nofollow' in href, how to do it. Can it support amp.
> […](#)

Default [Parsedown][1] only support flower markdown but `rel=nofollow ` are in [kramdown][2] and should not be hard to make a extension to [Parsedown][1] there add the support


  [1]: https://github.com/erusev/parsedown
  [2]: https://kramdown.gettalong.org
