### ISSUE TITLE
Parsing a markdown page to html page

### ISSUE THREAD

**Issue by mcuix** [erusev/parsedown#702]
What would the correct syntax be for parsing an entire markdown file to html output?
For example test.md --> test.html

**Comment by BenjaminHoegh** [comment]
Just to be sure, do you want it to export a html file or just show html code ?

if you just wanna paste a markdown file into a html you can use `echo $Parsedown->text(file_get_contents('myFile.md'));`

**Comment by mcuxdk** [comment]
I have a MD file that needs to be converted to html. Can parsedown be used for this purpose?

**Comment by mcuix** [comment]
Ok. Got it to work.

<?php
include 'Parsedown.php';
$Parsedown = new Parsedown();
echo $Parsedown->text(file_get_contents('test.md'));
?>
