### ISSUE TITLE
HTML tags cut if multiple in one line

### ISSUE THREAD

**Issue by malkow** [erusev/parsedown#709]
Parsing error with multiple appending html tags in a single line, which leads to a 'cut' after the first tag.

E.g.:
`<div class="foo"></div><div class="bar"></div>`

**Comment by malkow** [comment]
Closed because it's a Parsedown Extra issue. Will post it there.

**Comment by aidantwoods** [comment]
As I currently planned, this shouldn't happen in `2.0`—I'm not planning on keeping Parsedown extra's `markdown=1` (and its associated HTML parsing, which is probably the cause of this bug, see: https://github.com/erusev/parsedown/issues/657#issuecomment-410799834).

**Comment by aidantwoods** [comment]
Duplicate of #657
