### ISSUE TITLE
Add support for PHP 7.1+ and strict types

### ISSUE THREAD

**Issue by janbarasek** [erusev/parsedown#732]
Hello,

I suggest add support for all new PHP 7 features like strict types, input and return types, use new array syntax and more.

This upgrade can be released as new package master version and used in `composer.json`.

I think keep progress with current PHP is very important for new projects.

If you want upgrade this package, please let me know and I will send pull request.

Thank you and have a lovely day. :)

**Comment by aidantwoods** [comment]
See #708. 

I'd actually really appreciate a review of that PR, to avoid just making changes no one really wants or agrees with.

**Comment by janbarasek** [comment]
@aidantwoods Ok, I will check it. I think you can close this issue and we will continue in #708.

Thanks.
