### ISSUE TITLE
Links inside a p-tag does not work

### ISSUE THREAD

**Issue by jenstornell** [erusev/parsedown#739]
A link tag does not work when it's inside a html `<p>` tag.

I was discovering this when I went from converting html to yaml and don't wanted to spend more time than needed. Therefor I kept the p-tags but changed the link syntax. However, this combination does not work. Is it expected behavior?

**This does work**

```
Oat cake sugar plum cupcake powder jelly beans topping apple pie topping halvah. Tootsie roll candy canes danish bear claw caramels marshmallow croissant. Macaroon tiramisu brownie jujubes ice cream marshmallow tootsie roll. [A link](a/link).
```

**This does not work**

```text
<p>Oat cake sugar plum cupcake powder jelly beans topping apple pie topping halvah. Tootsie roll candy canes danish bear claw caramels marshmallow croissant. Macaroon tiramisu brownie jujubes ice cream marshmallow tootsie roll. [A link](a/link).</p>
```

**Comment by tovic** [comment]
~~~ .html
<p markdown="1"> … </p>
~~~

**Comment by Linnzh** [comment]
Yes, I have also encountered this situation. Also in the <p> tag, text bold (**) does not work.

**Comment by Linnzh** [comment]
@jenstornell , The strict markdown syntax does not seem to support nesting in HTML code. This library will skip the HTML code part.

**Comment by jenstornell** [comment]
`markdown="1"` solved it so I close this one now.
