### ISSUE TITLE
Error showing the blockquote in code tags

### ISSUE THREAD

**Issue by FilipSLO** [erusev/parsedown#792]
**_markup to show the output error:_**
    ******************************************
    This markup should turn into blockquote within code tags:
    
    > ```<script src="//some.website.org/js/"></script>
    > ```
    
    But doesn't.
    ******************************************
    
    **_Actual output in version 1.8.0-beta-7:_**
    ******************************************
    <p>This markup should turn into blockquote within code tags:</p>
    <blockquote>
    <pre><code class="language-<script"></code></pre>
    </blockquote>
    <p>But doesn't.</p>
    
    
    **_Expected output:_**
    ******************************************
    <p>This markup should turn into blockquote within code tags:</p>

        
    <blockquote>
      <p><code>&lt;script src="//some.website.org/js/"&gt;&lt;/script&gt;</code></p>
    </blockquote>
    
    <p>But doesn't.</p>

**Comment by taufik-nurrohman** [comment]
Add new line after the first ` ``` `

~~~ .markdown
> ```
> foo bar
> ```
~~~

**Comment by FilipSLO** [comment]
Thanks, Taufik Nurrohman. Is that markdown invalid? Nice workaround BTW.

**Comment by taufik-nurrohman** [comment]
Yes, your code is invalid because any string right after the opening ` ``` ` or ` ~~~ ` will be treated as code class name to be used by syntax highlighter feature if any.
