### ISSUE TITLE
Maximum image size?

### ISSUE THREAD

**Issue by HeadStudios** [erusev/parsedown#842]
Any way to set the maximum width of any images passed? I'm outputting to PDF and it gets messy when large images are linked to. Thnks!

**Comment by taufik-nurrohman** [comment]
Use [my plugin](https://github.com/taufik-nurrohman/parsedown-extra-plugin) then set `imageAttributes` property:

~~~ php
$Parsedown->imageAttributes = [
    'style' => 'height: auto; max-width: 100%;'
];
~~~

**Comment by HeadStudios** [comment]
Thank you so much! That was super quick too - much appreciated.
