### ISSUE TITLE
PHP 8.4 incompatibilities

### ISSUE THREAD

**Issue by timint** [erusev/parsedown#890]
Starting a topic to list incompatibilities with PHP 8.4:

> Deprecated: Parsedown::blockSetextHeader(): Implicitly marking parameter $Block as nullable is deprecated, the explicit nullable type must be used instead in ~/vendor/erusev/parsedown/Parsedown.php on line 715

> Deprecated: Parsedown::blockTable(): Implicitly marking parameter $Block as nullable is deprecated, the explicit nullable type must be used instead in ~/vendor/erusev/parsedown/Parsedown.php on line 853`

**Comment by joeworkman** [comment]
dup #889
