### ISSUE TITLE
John Gruber's test suite

### ISSUE THREAD

**Issue by wkpark** [erusev/parsedown#99]
This is a John Gruber's test suite
http://daringfireball.net/projects/downloads/MarkdownTest_1.0.zip

and the following example rendered incorrectly by the parsedown.

```
In Markdown 1.0.0 and earlier. Version
8. This line turns into a list item.
Because a hard-wrapped line in the
middle of a paragraph looked like a
list item.

Here's one with a bullet.
* criminey.
```

In Markdown 1.0.0 and earlier. Version
8. This line turns into a list item.
Because a hard-wrapped line in the
middle of a paragraph looked like a
list item.

Here's one with a bullet.
- criminey.

babelmark2 result:
http://johnmacfarlane.net/babelmark2/?text=In+Markdown+1.0.0+and+earlier.+Version%0A8.+This+line+turns+into+a+list+item.%0ABecause+a+hard-wrapped+line+in+the%0Amiddle+of+a+paragraph+looked+like+a%0Alist+item.%0A%0AHere%27s+one+with+a+bullet.%0A*+criminey.

**Comment by aidantwoods** [comment]
We now test against (but do not currently pass all of) the CommonMark examples. CommonMark is a bit more specific than John Gruber's original Markdown spec, so I think that testing against John Gruber's suite is probably no longer needed :)
